NeighborArray is now fixed size
apache/lucene pull request #11784
Opened 2022-09-18 20:16 UTC by msokolov

Remove the ability for `NeighborArray` to grow. Always allocates it one larger than requested, to reserve space for a temporary neighbor.

2022-09-18 20:17 UTC, msokolov commented
Fixes https://github.com/apache/lucene/issues/11783

2022-09-19 14:51 UTC, msokolov commented
> I was thinking a better approach would be to leave it to uses of NeighborArray to define maxSize, and not add +1 in the NeighborArray class itself as this PR suggests

I guess I was thinking that since this class only has a single use, it wouldn't matter? But it definitely is better encapsulation to move the sizing logic to the place where we know how many we need. +1 to have consumers do it, especially since at least in one place they already do :) I'll follow up with a patch

2022-09-19 15:01 UTC, msokolov commented
Also -- now that I see this I realize that most likely we are never exercising this resize capability, so removing it won't really help performance / memory usage as I was hoping. But it still seems like a good cleanup?

2022-09-23 07:16 UTC, danmuzi requested changes

2022-09-23 07:16 UTC, danmuzi commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +          || (scoresDescOrder == false && (previousScore <= newScore)));
It seems to be an [XNOR](https://en.wikipedia.org/wiki/XNOR_gate) operation.
(A & B) | (!A & !B) => A == B
So it can be changed to a simple form as follows:
```java
return (previousScore == newScore) || (scoresDescOrder == (previousScore > newScore))
```

2022-10-05 00:14 UTC, jtibshirani approved these changes
This seems like a nice clean-up, even if it doesn't lead to a performance improvement.

2022-10-05 00:14 UTC, jtibshirani commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +          || (scoresDescOrder == false && (previousScore <= newScore)));
Thanks for the insight @danmuzi. I actually find the current way easier to understand, since it reads like "if scores are descending, then previousScore should be >= newScore, otherwise previousScore should be <= newScore"

2022-10-05 07:33 UTC, danmuzi commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +          || (scoresDescOrder == false && (previousScore <= newScore)));
Thanks for checking, @jtibshirani 
That's why I set `(previousScore == newScore)` forward.
In the current code, it is unconditionally true if previousScore and newScore are equal because of `(scoresDescOrder && (previousScore >= newScore))`.
Therefore, that part can be pre-checked.
```
(scoresDescOrder && (previousScore >= newScore))
 ||
(scoresDescOrder == false && (previousScore <= newScore))
```
->
```
(previousScore == newScore)
||
(
 (scoresDescOrder && (previousScore > newScore))
    ||
 (scoresDescOrder == false && (previousScore < newScore))
)
```
And the conditional statement can be simplified by XNOR operation.
```
scoresDescOrder = X, (previousScore > newScore) = Y
(previousScore == newScore) || ((X && Y) || (!X && !Y))
->
(previousScore == newScore) || (X == Y)
->
(previousScore == newScore) || (scoresDescOrder == (previousScore > newScore))
```
Of course, it is a simple comparison operation, the performance difference will not be huge.
But I think the number of comparisons is clearly less than the previous code.

2022-10-05 16:11 UTC, mayya-sharipova approved these changes
Sorry, I missed the last changes, LGTM as well. Thank you.

2022-10-05 17:56 UTC, danmuzi requested changes
I left one more new comment after @jtibshirani 's reply.
It's not a huge improvement, but I think it's meaningful.

2023-11-02 11:39 UTC, mikemccand commented
Wow, lots of fun discussion here, including specifics of how Java conditionals are evaluated.  @msokolov is this still relevant?  The HNSW code has been red-hot lately; maybe this change was already effectively done?

2023-11-02 11:47 UTC, mikemccand commented
Thanks @msokolov.  This looks like a nice tool, helpful for giving demos of cool Lucene features at conferences, but it looks like consensus is we should not add it to Lucene?  Maybe luceneutil instead?

2024-01-09 13:51 UTC, closed without merging