gradle aggregated coverage console log and html location
apache/lucene pull request #11882
Opened 2022-10-27 06:27 UTC by zhaih

### Description

issue #11839

It's my first time really working on gradle script so I'm pretty uncertain whether I've done something wrong :) I tested with `./gradlew coverage` and it works as expected.

* Add `java` plugin to `:lucene` so that it will apply the "org.barfuin.gradle.jacocolog" plugin as well
* `coverage` depend on `jacocoAggregatedReport` so it will print aggregated coverage, for subproject it just print out the  coverage for that module
* Show html location only for parent project (which is only lucene?) because the printout for subproject also point to the same location, and the report is already aggregated.

2022-10-27 06:42 UTC, dweiss requested changes

2022-10-27 06:42 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
I don't know what that aggregate report task is doing but I would not apply the java plugin to the lucene module. Applying a plugin can mean a lot of other things will trigger automatically on that module - including things like validation, etc. I don't think we want that. 

I'm not familiar with jacoco (or this task) but it seems it should be possible to aggregate just a selected set of projects, like shown here, for example:

https://docs.gradle.org/7.4/samples/sample_jvm_multi_project_with_test_aggregation_standalone.html

2022-10-27 06:45 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
Seems to me like report aggregation is now built into gradle (since version 7.4) and we wouldn't need the org.barfuin.gradle.jacocolog plugin at all. First, however, we'd have to upgrade to gradle 7.4 (or newer).

2022-10-27 12:27 UTC, rmuir commented on lucene/build.gradle
> +apply plugin: 'java'
these are separate concerns. the jacocolog plugin is just about *printing what the thing is doing* which gradle never does... with anything :) So we still must keep this plugin, the whole purpose is to be able to see the coverage without browsing html.

2022-10-27 17:50 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
If so, fine, but I wouldn't want the java plugin to be applied to the top level lucene project just so that this single task works... has to be a different way to make it work without it.

2022-10-27 17:55 UTC, rmuir commented on lucene/build.gradle
> +apply plugin: 'java'
agreed, i dont know why `java` is needed here. its enough to just apply `org.barfuin.gradle.jacocolog`, right?

The docs say:
> If you are only interested in aggregated coverage, you only need to add
> org.barfuin.gradle.jacocolog to the parent project (whereever the aggregation should happen). It will then aggregate
> the coverage of all subprojects which have the jacoco plugin (where stuff was measured).

2022-10-27 20:34 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
I've removed plugin application and reorganized the logic there a bit - coverage shouldn't trigger all test tasks to run (it previously did), it should just finalize any test task that was otherwise invoked. So something like this works:
```
gradlew :lucene:analysis:kuromoji:test  -Ptests.coverage=true
```
I think the 'coverage' task is no longer strictly necessary... but I made it depend on the default 'test' task so that this also works:
```
gradlew :lucene:analysis:kuromoji:test  -Ptests.coverage=true
```

However, the problem with third party plugins is that they're hard to explain sometimes. I made a top-level coverage task that should just aggregate any other test coverage reports... but it triggers all test tasks to run (including those from hunspell that are not run by default!). I've no idea why this happens, eh.
```
gradlew :lucene:analysis:kuromoji:test :coverage -Ptests.coverage=true
```

2022-10-27 20:48 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
I've no idea why that plugin triggers all test tasks to be included in the execution graph. Looked at the code but it's beyond me. It's wrong though, shouldn't be happening.

2022-10-27 20:59 UTC, zhaih commented on lucene/build.gradle
> +apply plugin: 'java'
> I've no idea why that plugin triggers all test tasks to be included in the execution graph. Looked at the code but it's beyond me. It's wrong though, shouldn't be happening.

probably [this line](https://gitlab.com/barfuin/gradle-jacoco-log/-/blob/master/src/main/java/org/barfuin/gradle/jacocolog/JacocoAggReportConfigAction.java#L67)? Where it forces the aggregation task to run after all test task it can find.

2022-10-27 21:08 UTC, zhaih commented
Thanks @dweiss! I was having some hard time understanding the dependencies between plugins so thank you for jumping out and help! I tested the change and it looks good to me. 
> but it triggers all test tasks to run (including those from hunspell that are not run by default!)

Do you think this will become a problem? If not I guess we can just push it?

2022-10-27 23:52 UTC, rmuir commented on lucene/build.gradle
> +apply plugin: 'java'
> However, the problem with third party plugins is that they're hard to explain sometimes. I made a top-level coverage task that should just aggregate any other test coverage reports... but it triggers all test tasks to run (including those from hunspell that are not run by default!). I've no idea why this happens, eh.

I noticed this already happens with main branch today: I think it is unrelated to this change. It also seems to ignore the `--tests MyTest` if you do this... and still run all the hunspell tests (and possibly all the analyzers-common tests?) Maybe it would help if we moved these hunspell tests to a separate integration test subproject?

2022-10-28 05:16 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
Yeah, I think it's broken somewhere and it's because of this plugin. I'll take a look at this, sorry for turning your effort upside down, @zhaih - gradle workings are not easy to grasp at first. It sometimes seems closer to a declarative language than an imperative one.

2022-10-28 05:18 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
The 'mustRunAfter' is actually correct - it just schedules task ordering but not a dependency (dependsOn). So it shouldn't run tests automatically.

2022-10-28 13:21 UTC, rmuir commented on lucene/build.gradle
> +apply plugin: 'java'
> Yeah, I think it's broken somewhere and it's because of this plugin. I'll take a look at this, sorry for turning your effort upside down, @zhaih - gradle workings are not easy to grasp at first. It sometimes seems closer to a declarative language than an imperative one.

if we nuke the console printing and just use the built-in jacoco/aggregate tasks, maybe the buggy behavior goes away?

2022-10-28 13:46 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
I'll be looking at it later today - curious as to what's going on there. I didn't abandon it.

2022-10-28 15:19 UTC, dweiss commented on lucene/build.gradle
> +apply plugin: 'java'
Yeah - we were looking at the main branch; the plugin in version 2.0.0 adds an explicit dependency on all test tasks, hence the problems above.

2022-10-28 15:45 UTC, dweiss commented
Now task dependencies seem to work as I'd expect them to. I don't know how to read the coverage information at the top level when one only runs a set of subprojects. For example:
```
gradlew test -p lucene\analysis\kuromoji :jacocoAggregatedReport -Ptests.coverage=true
```
results in:
![image](https://user-images.githubusercontent.com/199470/198678521-7bcaaf05-e1eb-40b1-a74e-fa0eef44e444.png)

The "aggregated" view only makes sense when you actually run all the tests.... I think this may be weird to just me though, I wouldn't worry about it.

2022-10-28 15:48 UTC, dweiss commented
Now task dependencies seem to work as I'd expect them to. I don't know how to read the coverage information at the top level when one only runs a set of subprojects. For example:
```
gradlew test -p lucene\analysis\kuromoji :jacocoAggregatedReport -Ptests.coverage=true
```
results in:
![image](https://user-images.githubusercontent.com/199470/198678521-7bcaaf05-e1eb-40b1-a74e-fa0eef44e444.png)

The "aggregated" view only makes sense when you actually run all the tests.... I think this may be weird to just me though, I wouldn't worry about it.

2022-10-28 15:56 UTC, rmuir commented
> The "aggregated" view only makes sense when you actually run all the tests.... I think this may be weird to just me though, I wouldn't worry about it.

Maybe there is some way to detect that only specific project was run (e.g. the `-p xxx` flag was specified), and omit the aggregate report? If you only run tests for a single project you'll see the per-project coverage already and have what you need.

2022-10-28 19:32 UTC, dweiss commented
oh - it will work that way if you run coverage on a subproject (see my explicit top-level task above). even then it can be a bit weird if you use the filter (--tests) but I guess it's not going to be surprising if you're familiar with jacoco (I'm not that familiar, I admit).

2022-10-28 21:55 UTC, rmuir commented
Personally I don't think its confusing with the filter (`--tests`). When writing new functionality/tests, I like to iterate and see what branches etc of the code the new test is covering. jacoco also has plugins for IDEs that make that workflow easy too.

My basic assumption is that jacoco agent just makes a bitset with on/off bit corresponding to each bytecode, so you can't see fancy stuff like "how many times this line of app code was hit in tests" or "which tests tested this". Clover did some of that, but with insane resource usage. 

So for me being able to use it with --tests to see exactly what the specific test(s) covered is really useful, because you don't exactly have an alternate way to see that info with jacoco.

2022-10-29 06:28 UTC, dweiss commented
That's fine for me. And I think this patch also fixes the problem of test tasks running needlessly - I'm +1 to add it, I don't think I have anything else to contribute here (?).

2022-10-29 06:29 UTC, dweiss approved these changes

2022-10-29 06:31 UTC, zhaih commented
Again, thank you @dweiss a lot for helping! I'll push it.

2022-10-29 06:33 UTC, merged