Refactor part of IndexFileDeleter and ReplicaFileDeleter into a common utility class
apache/lucene pull request #12126
Opened 2023-02-03 07:06 UTC by zhaih

### Description

See #11885 

### Approach
I extracted mainly the ref counting part into the new `FileDeleter` so that both `IndexFileDeleter` and `ReplicaFileDeleter` will use it as a component. It does not provide any level of thread-safety since the `IndexFileDeleter` originally was implemented in a lock-free way, so the user of this new `FileDeleter` is responsible for the synchronization if necessary.

### Test
I haven't written any specific test for this since I feel like the existing tests (mainly `TestIndexFileDeleter`) should already provide a good coverage

2023-02-06 23:30 UTC, jimmykobe1171 commented on lucene/replicator/src/java/org/apache/lucene/replicator/nrt/CopyJob.java
> +      dest.deleter.deleteIfNoRef(prevJob.current.tmpName);
Seems like **deleteIfNoRef** is always safer than **deleteNewFile**. Do we still need the method deleteNewFile?

2023-02-08 00:27 UTC, zhaih commented on lucene/replicator/src/java/org/apache/lucene/replicator/nrt/CopyJob.java
> +      dest.deleter.deleteIfNoRef(prevJob.current.tmpName);
Ah I actually want to do it the opposite way, I'm not 100% sure why we need a `deleteNewFile` (force delete) here rather than `deleteIfNoRef` but I don't want to introduce a (possibly) different behavior in this change so I kept it. 
Altho the `deleteNewFile` is a bit misleading so I changed the name to `forceDeleteFile`

2023-02-13 21:37 UTC, sukiand commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +    fileDeleter.deleteFilesIfNoRef(toDelete);
we get toDelete from `fileDeleter` as well. should this part of code be encaptulated into `fileDeleter` as a whole. like call fileDeleter.clean() or sth.

2023-02-14 06:05 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +    fileDeleter.deleteFilesIfNoRef(toDelete);
Yeah I was struggling with this as well. The reason I put it like this is that I feel like the `IllegalStateException` here is quite important so I don't want to throw it away, but if I put it into say `fileDeleter.clean()`, then it does not always make sense too.

2023-03-07 18:38 UTC, mikemccand requested changes
Thank you for this refactor @zhaih!  It is very hairy code that was doing nearly the same thing in two different places.  The rote refactor is badly needed.

I left a few small comments... I think this is very close.

2023-03-07 18:38 UTC, mikemccand commented on lucene/CHANGES.txt
> +  FileDeleter. (Patrick Zhai)s
Is that trailing `s` by accident?

2023-03-07 18:38 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +          fileDeleter.getRefCount(fileName);
Kinda weird that a method starting with `get` has this set-like side effect, sigh.

2023-03-07 18:38 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +          fileDeleter.getRefCount(fileName);
We can maybe later / separately improve the naming, or add a dedicated `initRefCount(fileName)` method or so.

2023-03-07 18:38 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +    if (msgType == FileDeleter.MsgType.REF && VERBOSE_REF_COUNTS == false) {
Probably you could have just moved the `VERBOSE_REF_COUNTS` down into `FileDeleter`, but since this is a rote refactor it's good to separate / do that later.

2023-03-07 18:38 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/util/FileDeleter.java
> +public class FileDeleter {
Maybe `final`?  This is such a crazy expert class -- it should be used only, but not extended?

2023-03-07 18:38 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/util/FileDeleter.java
> + */
Can you add `@lucene.internal` javadocs tag?  Users should not rely on the future stability of this API?

2023-03-08 06:18 UTC, zhaih commented on lucene/CHANGES.txt
> +  FileDeleter. (Patrick Zhai)s
LOL yes a mistype

2023-03-08 06:30 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +          fileDeleter.getRefCount(fileName);
Yeah I don't like that part, it's quite tricky, good thing is we're not abusing the old `get` so I just followed your suggestion and created a `initRefCount`, feels better now LOL.

2023-03-08 06:34 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java
> +    if (msgType == FileDeleter.MsgType.REF && VERBOSE_REF_COUNTS == false) {
I think we could leave `VERBOSE_REF_COUNTS` as is, since `FileDeleter` is just responsible for throwing message out with it's type, and here `VERBOSE_REF_COUNTS` is the switch on the `IFD` side so I think it makes sense to let it stay there.

2023-03-08 06:34 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/FileDeleter.java
> +public class FileDeleter {
+1

2023-03-08 06:39 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/FileDeleter.java
> + */
Ah forgot that, will add!

2023-03-14 18:08 UTC, mikemccand approved these changes
Thank you for refactoring such a hairy part of Lucene @zhaih!

2023-03-16 03:51 UTC, merged