Github 10633 Update Javadoc comment to mention gradle instead of ant
apache/lucene pull request #12201
Opened 2023-03-10 20:03 UTC by shaikhu

I believe this is a fix for issue [10633](https://github.com/apache/lucene/issues/10633).

Although the path is slightly different, this is the only class I could find with the name `TestBackwardsCompatibility`.

2023-04-08 06:05 UTC, zhaih requested changes

2023-04-08 06:05 UTC, zhaih commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
> +  //  gradlew test -Dtestcase=TestBackwardsCompatibility -Dtests.bwcdir=/path/to/store/indexes
I don't think `-Dtestcase` works with gradle, please refer to this: https://stackoverflow.com/questions/22505533/how-to-run-only-one-unit-test-class-using-gradle

Also maybe give the command a try to verify your change?

2023-04-08 06:34 UTC, dweiss commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
> +  //  gradlew test -Dtestcase=TestBackwardsCompatibility -Dtests.bwcdir=/path/to/store/indexes
Even better, read this help guide:
https://github.com/apache/lucene/blob/main/help/tests.txt#L51-L69

2023-04-10 11:16 UTC, shaikhu commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
> +  //  gradlew test -Dtestcase=TestBackwardsCompatibility -Dtests.bwcdir=/path/to/store/indexes
> I don't think `-Dtestcase` works with gradle, please refer to this: https://stackoverflow.com/questions/22505533/how-to-run-only-one-unit-test-class-using-gradle
> 
> Also maybe give the command a try to verify your change?

Yes, you're correct it `-Dtestcase` doesn't work with Gradle. Testing locally the following command worked
```gradlew test --tests  TestBackwardsCompatibility```.

2023-04-10 11:17 UTC, shaikhu commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
> +  //  gradlew test -Dtestcase=TestBackwardsCompatibility -Dtests.bwcdir=/path/to/store/indexes
> Even better, read this help guide: https://github.com/apache/lucene/blob/main/help/tests.txt#L51-L69

Thanks. See 886a009

2023-04-11 06:31 UTC, zhaih requested changes

2023-04-11 09:03 UTC, shaikhu commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
> +  // gradlew test -Dtestcase=TestBackwardsCompatibility -Dtestmethod=testCreateSortedIndex
> Here needs to be updated as well?

Missed that! See 7a75d797fe

2023-04-13 05:53 UTC, zhaih approved these changes
LGTM, thanks! Please add an entry to CHANGES.txt :)

2023-04-13 09:46 UTC, shaikhu commented
> LGTM, thanks! Please add an entry to CHANGES.txt :)

Added entry with f81956b8

2023-04-14 18:23 UTC, zhaih requested changes

2023-04-14 18:23 UTC, zhaih commented on lucene/CHANGES.txt
> +* GITHUB#10633: Update javadocs in TestBackwardsCompatibility to use gradle and not ant. (Usman Shaikh)
Could you move it under Lucene 9.6?

2023-04-15 12:08 UTC, shaikhu commented on lucene/CHANGES.txt
> +* GITHUB#10633: Update javadocs in TestBackwardsCompatibility to use gradle and not ant. (Usman Shaikh)
> Could you move it under Lucene 9.6?

moved with 4efae16f93

2023-04-19 05:11 UTC, zhaih approved these changes

2023-04-19 05:14 UTC, merged

2023-04-19 05:16 UTC, zhaih commented
Thank you! Just merged and backported