Add ordering of files in compound files
apache/lucene pull request #12241
Opened 2023-04-25 13:33 UTC by cbuescher

Today there is no specific ordering of how files are written to a compound file.
The current order is determined by iterating over the set of file names in
SegmentInfo, which is unspecific. This PR proposes to change to an order based
on file size. Colocating data from files that are smaller (typically metadata
files like terms index, field info etc...) but accessed often can help when
parts of these files are held in cache.

In our particular case, the motivation is coming from reading larger compound
files from a remote object store through a caching layer that keeps chunks of
the file in pages. Keeping small files together can help improve the efficiency
of the cache because data that is read often (like metadata) is kept together.

2023-04-25 13:52 UTC, mikemccand commented
+1, cool idea!

2023-04-25 15:00 UTC, cbuescher commented
@romseygeek fyi

2023-04-26 10:01 UTC, romseygeek requested changes
This is great, thanks @cbuescher.  I left a couple of suggestions for changes, can you fix those up and add a CHANGES entry for 9.6?

2023-04-26 10:01 UTC, romseygeek commented on lucene/core/src/test/org/apache/lucene/codecs/lucene90/TestLucene90CompoundFormat.java
> +    si.setFiles(files);
Can we explicitly shuffle the `files` list to make it clear that things are in a random order within the segment info?  And maybe add a comment to the point that it's held internally as a set so there's no defined ordering in any case?

2023-04-26 10:38 UTC, cbuescher commented on lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90CompoundFormat.java
> +    String name;
done

2023-04-26 10:38 UTC, cbuescher commented on lucene/core/src/test/org/apache/lucene/codecs/lucene90/TestLucene90CompoundFormat.java
> +    si.setFiles(files);
I added something for that

2023-04-26 10:54 UTC, romseygeek approved these changes
LGTM! Thanks @cbuescher

2023-04-26 13:01 UTC, merged