Seal `IndexReaderContext`
apache/lucene pull request #12296
Opened 2023-05-15 22:49 UTC by JarvisCraft

### Description

`IndexReaderContext` is already effectively sealed since it's constructor does type check throwing `Error` if `this` is neither instance of `CompositeReaderContext` nor `LeafReaderContext`.

This PR simply makes this restriction explicit (codewise) turning it from a runtime error into a compile time one to extend this class.

2023-05-16 14:03 UTC, uschindler requested changes

2023-05-16 14:04 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/index/IndexReaderContext.java
> +  protected final Object identity = new Object();
Ah you mentioned it. I don't remember why this `identity` is there. Is it really needed to be public. I'd keep this as is.

2023-05-16 14:05 UTC, uschindler commented
Please run `gradlew tidy`.

2023-05-16 14:45 UTC, JarvisCraft commented on lucene/core/src/java/org/apache/lucene/index/IndexReaderContext.java
> +  protected final Object identity = new Object();
Done

2023-05-16 14:45 UTC, JarvisCraft commented
> Please run gradlew tidy.

All done :+1:

2023-05-16 15:06 UTC, uschindler approved these changes

2023-05-16 15:14 UTC, uschindler commented
Could you apply the same change to `IndexReader`; it should be sealed, too? https://github.com/apache/lucene/blob/f53eb28af053d7612f7e4d1b2de05d33dc410645/lucene/core/src/java/org/apache/lucene/index/IndexReader.java#L72-L76

2023-05-16 15:18 UTC, uschindler commented
Please remove the protected from consructor. We don't want to show it in javadocs.

2023-05-16 15:19 UTC, uschindler requested changes
Please fix hide constructor again, the Javadocs are broken and they should really not be possible!

Also apply same change for `IndexReader`.

2023-05-16 15:19 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/index/IndexReaderContext.java
> +  protected IndexReaderContext(
Please make it package protected again, as we don't want it to appear in Javadocs.

2023-05-16 15:21 UTC, uschindler commented
Please don't change public javadocs, so just make the classes sealed and keep documentation the same. Only remove runtime check.

2023-05-16 15:30 UTC, JarvisCraft commented
Ready:
* brought back package-private visibility;
* applied the same change to `IndexReader.

2023-05-16 15:45 UTC, uschindler approved these changes
Looks fine now. Do you want to add a CHANGES.txt entry in the 10.x section?

2023-05-16 16:11 UTC, JarvisCraft commented
> Do you want to add a CHANGES.txt entry

Done

2023-05-17 06:47 UTC, merged

2023-05-17 06:48 UTC, uschindler commented
Thanks @JarvisCraft, I merged it to main branch.

2023-05-17 12:23 UTC, uschindler commented
Javadocs look fine: https://ci-builds.apache.org/job/Lucene/job/Lucene-Artifacts-main/javadoc/core/org/apache/lucene/index/IndexReader.html

![image](https://github.com/apache/lucene/assets/1005388/513be077-c5a3-4521-b5a6-d2b18e3bc329)