Better paging when random reads go backwards
apache/lucene pull request #12357
Opened 2023-06-08 11:22 UTC by romseygeek

When reading data from outside the buffer, BufferedIndexInput always resets
its buffer to start at the new read position.  If we are reading backwards (for example,
using an OffHeapFSTStore for a terms dictionary) then this can have the effect of
re-reading the same data over and over again.

This commit changes BufferedIndexInput to use paging when reading backwards,
so that if we ask for a byte that is before the current buffer, we read a block of data
of `bufferSize` that ends at the previous buffer start.

2023-06-08 11:25 UTC, romseygeek commented
I've only implemented this on `readByte()` so far, as that seems to be the method that is effected most.  Random reads of short, int and long values are mostly done when binary searching which is a much less adversarial case than step-by-step backwards reading.

I ran a wikimedium10k benchmark using `NIOFSDirectory` for both baseline and competitor, and got the following results:
```
  TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
       BrowseDayOfYearTaxoFacets     2514.67      (5.2%)     2202.60      (7.0%)  -12.4% ( -23% -    0%) 0.000
       BrowseDayOfYearSSDVFacets     4397.09     (10.1%)     3875.61     (13.3%)  -11.9% ( -31% -   12%) 0.001
            BrowseDateTaxoFacets     2974.26      (6.5%)     2641.17      (6.0%)  -11.2% ( -22% -    1%) 0.000
     BrowseRandomLabelSSDVFacets     1189.01      (4.1%)     1067.62      (6.2%)  -10.2% ( -19% -    0%) 0.000
     BrowseRandomLabelTaxoFacets     1601.99      (5.7%)     1438.85      (6.2%)  -10.2% ( -20% -    1%) 0.000
           BrowseMonthTaxoFacets     2524.45      (8.1%)     2273.63      (7.1%)   -9.9% ( -23% -    5%) 0.000
            BrowseDateSSDVFacets     1754.54     (10.7%)     1616.39      (8.4%)   -7.9% ( -24% -   12%) 0.009
                          IntNRQ     1604.64      (7.7%)     1485.48      (8.9%)   -7.4% ( -22% -    9%) 0.005
           BrowseMonthSSDVFacets     4473.87     (11.2%)     4179.28     (10.4%)   -6.6% ( -25% -   16%) 0.053
                         Prefix3      568.51      (3.9%)      982.22     (14.0%)   72.8% (  52% -   94%) 0.000
                     MedSpanNear      262.90      (2.4%)      490.78     (10.3%)   86.7% (  72% -  101%) 0.000
                        Wildcard      496.50      (3.3%)     1031.86     (17.1%)  107.8% (  84% -  132%) 0.000
               HighTermMonthSort      583.14      (4.4%)     1263.09     (19.9%)  116.6% (  88% -  147%) 0.000
             MedIntervalsOrdered      353.37      (2.3%)      767.89     (11.9%)  117.3% ( 100% -  134%) 0.000
                     LowSpanNear      254.88      (3.1%)      624.77     (16.6%)  145.1% ( 121% -  170%) 0.000
                        PKLookup       10.23      (1.7%)       25.13      (8.6%)  145.6% ( 133% -  158%) 0.000
                      OrHighHigh      307.39      (3.1%)      762.93     (18.4%)  148.2% ( 122% -  175%) 0.000
                       OrHighMed      384.51      (3.3%)      958.60     (19.5%)  149.3% ( 122% -  178%) 0.000
                      HighPhrase      304.14      (2.9%)      765.04     (14.6%)  151.5% ( 130% -  174%) 0.000
                    HighSpanNear      317.72      (3.1%)      804.30     (18.0%)  153.1% ( 127% -  179%) 0.000
                     AndHighHigh      398.97      (3.4%)     1012.15     (21.7%)  153.7% ( 124% -  185%) 0.000
           HighTermDayOfYearSort      582.77      (2.7%)     1495.18     (23.5%)  156.6% ( 126% -  187%) 0.000
                        HighTerm      798.23      (2.8%)     2094.10     (22.5%)  162.3% ( 133% -  193%) 0.000
                 MedSloppyPhrase      414.51      (2.7%)     1089.03     (28.6%)  162.7% ( 127% -  199%) 0.000
                         Respell       68.25      (2.2%)      187.81     (14.7%)  175.2% ( 154% -  196%) 0.000
                          Fuzzy2       14.66      (1.7%)       41.38     (13.1%)  182.3% ( 164% -  200%) 0.000
                HighSloppyPhrase      331.71      (2.1%)      946.59     (22.2%)  185.4% ( 157% -  214%) 0.000
             LowIntervalsOrdered      823.97      (2.7%)     2387.93     (19.5%)  189.8% ( 163% -  217%) 0.000
                         MedTerm      770.00      (4.3%)     2234.31     (30.4%)  190.2% ( 149% -  234%) 0.000
                       LowPhrase      358.61      (3.0%)     1080.46     (26.5%)  201.3% ( 166% -  238%) 0.000
                       OrHighLow      365.95      (2.8%)     1106.13     (23.3%)  202.3% ( 171% -  235%) 0.000
                      AndHighMed      352.26      (2.5%)     1135.10     (26.1%)  222.2% ( 189% -  257%) 0.000
            HighIntervalsOrdered      295.50      (2.7%)      971.90     (32.3%)  228.9% ( 188% -  271%) 0.000
                       MedPhrase      317.77      (2.7%)     1083.18     (29.9%)  240.9% ( 202% -  281%) 0.000
                         LowTerm      932.40      (2.8%)     3290.65     (24.1%)  252.9% ( 219% -  287%) 0.000
                          Fuzzy1       37.84      (1.6%)      137.03     (17.0%)  262.1% ( 239% -  285%) 0.000
                 LowSloppyPhrase      313.05      (3.1%)     1253.27     (30.8%)  300.3% ( 258% -  344%) 0.000
                      AndHighLow      404.61      (2.6%)     1947.42     (38.5%)  381.3% ( 331% -  433%) 0.000
```

I'm not sure what's happening to slow down the facets implementation, so I will dig further into that, but it's a clear win for terms-based queries.

2023-06-08 11:43 UTC, jpountz requested changes
I see that you only changed the logic when reading data via the `RandomAccessInput` interface. I want to call out that this means that reading bytes via the `IndexInput` abstraction (like when reading postings or the BKD index) still expects forward reads. I think it's good.

> Random reads of short, int and long values are mostly done when binary searching which is a much less adversarial case than step-by-step backwards reading.

This sounds right, but I'd rather like to avoid making different assumptions in readByte/readShort/readInt/readLong, so let's make similar changes to these methods?

2023-06-08 11:43 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/BufferedIndexInput.java
> +  private final int bufferSize;
I had not realized that the bufferSize could no longer be updated. It's not directly related to your change but we could fix the `getBufferSize` javadocs to no longer link to `setBufferSize`?

2023-06-08 11:43 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/BufferedIndexInput.java
> +      bufferStart = index < 0 ? Math.min(pos, Math.max(0, bufferStart - bufferSize)) : pos;
Let's add a comment explaining that this is trying to avoid backward reading being an adversarial case?

2023-06-08 13:43 UTC, romseygeek commented
Updated to include readShort/Int/Long as well.  I was wondering if the interaction between different readXXX paging methods was causing the facet slowdown, but it seems to be real:
```
TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
     BrowseRandomLabelSSDVFacets     1173.63      (6.2%)     1020.59      (9.8%)  -13.0% ( -27% -    3%) 0.000
           BrowseMonthSSDVFacets     4522.06      (7.9%)     4060.36     (12.3%)  -10.2% ( -28% -   10%) 0.002
           BrowseMonthTaxoFacets     2669.49      (7.2%)     2397.32      (7.4%)  -10.2% ( -23% -    4%) 0.000
            BrowseDateSSDVFacets     1761.73     (12.7%)     1582.48     (13.0%)  -10.2% ( -31% -   17%) 0.012
     BrowseRandomLabelTaxoFacets     1592.70      (6.8%)     1454.41     (11.3%)   -8.7% ( -25% -   10%) 0.003
            BrowseDateTaxoFacets     2934.99      (7.1%)     2689.84      (8.3%)   -8.4% ( -22% -    7%) 0.001
       BrowseDayOfYearTaxoFacets     2480.61      (7.5%)     2304.31      (9.3%)   -7.1% ( -22% -   10%) 0.008
       BrowseDayOfYearSSDVFacets     4192.62      (9.8%)     3897.13     (10.2%)   -7.0% ( -24% -   14%) 0.026
                          IntNRQ     1172.01      (7.2%)     1104.12      (6.1%)   -5.8% ( -17% -    8%) 0.006
                        HighTerm     1336.10      (5.1%)     2027.68     (18.3%)   51.8% (  27% -   79%) 0.000
                        Wildcard      598.31      (3.9%)      955.95     (16.2%)   59.8% (  38% -   83%) 0.000
                      HighPhrase      225.44      (2.7%)      402.62     (15.8%)   78.6% (  58% -   99%) 0.000
                         Respell      103.12      (2.2%)      208.00     (10.2%)  101.7% (  87% -  116%) 0.000
                    HighSpanNear      299.66      (3.1%)      626.32     (25.2%)  109.0% (  78% -  141%) 0.000
                 MedSloppyPhrase      423.66      (3.6%)      903.18     (20.7%)  113.2% (  85% -  142%) 0.000
                         MedTerm     1113.95      (4.3%)     2447.59     (19.3%)  119.7% (  92% -  149%) 0.000
                HighSloppyPhrase      305.08      (3.2%)      685.40     (25.8%)  124.7% (  92% -  158%) 0.000
               HighTermMonthSort      541.93      (3.4%)     1274.43     (21.0%)  135.2% ( 106% -  165%) 0.000
                      OrHighHigh      310.93      (2.8%)      739.48     (22.4%)  137.8% ( 109% -  167%) 0.000
                         Prefix3      499.55      (3.3%)     1189.55     (17.7%)  138.1% ( 113% -  164%) 0.000
             MedIntervalsOrdered      452.98      (3.0%)     1102.66     (23.0%)  143.4% ( 114% -  174%) 0.000
                        PKLookup       10.48      (1.2%)       25.52     (13.9%)  143.6% ( 127% -  160%) 0.000
           HighTermDayOfYearSort      581.53      (3.5%)     1459.01     (25.1%)  150.9% ( 118% -  185%) 0.000
                     MedSpanNear      320.53      (3.4%)      812.85     (19.6%)  153.6% ( 126% -  182%) 0.000
                     AndHighHigh      321.86      (2.4%)      822.05     (24.0%)  155.4% ( 125% -  186%) 0.000
                       OrHighMed      365.66      (2.3%)      970.56     (19.6%)  165.4% ( 140% -  191%) 0.000
            HighIntervalsOrdered      312.18      (2.7%)      843.86     (26.8%)  170.3% ( 137% -  205%) 0.000
                     LowSpanNear      414.08      (2.7%)     1120.42     (26.5%)  170.6% ( 137% -  205%) 0.000
                       OrHighLow      371.86      (2.3%)     1010.30     (26.7%)  171.7% ( 139% -  205%) 0.000
                          Fuzzy2       15.13      (2.0%)       42.98     (17.2%)  184.0% ( 161% -  207%) 0.000
                       LowPhrase      546.26      (2.8%)     1591.06     (20.7%)  191.3% ( 163% -  221%) 0.000
                      AndHighMed      484.28      (1.6%)     1479.76     (26.3%)  205.6% ( 174% -  237%) 0.000
                       MedPhrase      348.29      (2.9%)     1195.46     (28.4%)  243.2% ( 205% -  282%) 0.000
                 LowSloppyPhrase      346.96      (2.9%)     1213.98     (31.2%)  249.9% ( 209% -  292%) 0.000
             LowIntervalsOrdered      392.74      (2.7%)     1415.39     (28.0%)  260.4% ( 223% -  299%) 0.000
                         LowTerm      766.17      (3.2%)     3113.86     (40.9%)  306.4% ( 254% -  361%) 0.000
                          Fuzzy1       25.43      (1.7%)      109.24     (24.0%)  329.6% ( 298% -  361%) 0.000
                      AndHighLow      389.62      (2.4%)     2053.68     (48.1%)  427.1% ( 367% -  489%) 0.000
```

2023-06-08 14:38 UTC, romseygeek commented
`wikimedium1m` is much happier for facets, and frankly ridiculous for AndHighLow

```
            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
            BrowseDateSSDVFacets       17.76      (7.3%)       17.97      (6.2%)    1.2% ( -11% -   15%) 0.587
       BrowseDayOfYearSSDVFacets       72.94      (5.4%)       74.08      (3.6%)    1.6% (  -7% -   11%) 0.281
     BrowseRandomLabelSSDVFacets       50.47      (5.5%)       51.35      (5.7%)    1.7% (  -8% -   13%) 0.326
           BrowseMonthSSDVFacets      108.47     (17.3%)      110.40      (9.5%)    1.8% ( -21% -   34%) 0.685
     BrowseRandomLabelTaxoFacets       51.54      (3.7%)       52.59      (3.6%)    2.0% (  -5% -    9%) 0.080
            BrowseDateTaxoFacets       56.20      (3.9%)       57.53      (3.0%)    2.4% (  -4% -    9%) 0.031
       BrowseDayOfYearTaxoFacets       57.25      (4.0%)       58.64      (3.7%)    2.4% (  -5% -   10%) 0.046
                          IntNRQ      150.45      (4.4%)      154.86      (3.4%)    2.9% (  -4% -   11%) 0.018
           BrowseMonthTaxoFacets       85.36      (3.8%)       90.76      (4.9%)    6.3% (  -2% -   15%) 0.000
            HighIntervalsOrdered       13.33      (5.4%)       15.07      (4.4%)   13.1% (   3% -   24%) 0.000
                HighSloppyPhrase       28.66      (4.8%)       38.67      (5.6%)   34.9% (  23% -   47%) 0.000
             MedIntervalsOrdered       22.66      (5.0%)       31.38      (5.4%)   38.5% (  26% -   51%) 0.000
           HighTermDayOfYearSort       66.67      (4.0%)       94.27      (6.3%)   41.4% (  29% -   53%) 0.000
                     MedSpanNear       44.36      (4.9%)       64.94      (5.4%)   46.4% (  34% -   59%) 0.000
                 MedSloppyPhrase       35.30      (5.0%)       52.90      (6.4%)   49.8% (  36% -   64%) 0.000
                      OrHighHigh       37.42      (4.6%)       57.81      (5.1%)   54.5% (  42% -   67%) 0.000
                       LowPhrase       55.41      (5.6%)       95.52      (6.3%)   72.4% (  57% -   89%) 0.000
                      AndHighMed       70.03      (4.0%)      122.34      (7.5%)   74.7% (  60% -   89%) 0.000
                       MedPhrase       43.35      (5.3%)       76.52      (6.8%)   76.5% (  61% -   93%) 0.000
                      HighPhrase       46.63      (4.7%)       86.27      (6.4%)   85.0% (  70% -  100%) 0.000
                       OrHighMed       49.73      (4.4%)       92.06      (6.8%)   85.1% (  70% -  100%) 0.000
                    HighSpanNear       42.46      (4.5%)       79.91      (6.6%)   88.2% (  73% -  103%) 0.000
                 LowSloppyPhrase       51.32      (4.8%)       97.60      (7.8%)   90.2% (  73% -  107%) 0.000
                     AndHighHigh       38.56      (4.3%)       75.29      (6.4%)   95.2% (  81% -  110%) 0.000
                       OrHighLow       45.05      (5.2%)       88.33      (7.1%)   96.1% (  79% -  114%) 0.000
                         MedTerm      137.02      (5.3%)      269.88      (8.1%)   97.0% (  79% -  116%) 0.000
                        HighTerm      120.45      (5.0%)      246.27      (9.2%)  104.5% (  85% -  125%) 0.000
                        Wildcard       39.54      (4.5%)       84.47      (7.9%)  113.6% (  96% -  132%) 0.000
               HighTermMonthSort      331.29      (5.6%)      751.47      (8.7%)  126.8% ( 106% -  149%) 0.000
                         LowTerm      113.12      (4.6%)      301.60     (11.0%)  166.6% ( 144% -  190%) 0.000
                     LowSpanNear       61.77      (4.6%)      175.88     (11.0%)  184.7% ( 161% -  209%) 0.000
                         Prefix3       74.16      (5.1%)      252.59     (14.2%)  240.6% ( 210% -  273%) 0.000
             LowIntervalsOrdered       70.67      (4.8%)      246.61     (11.6%)  249.0% ( 221% -  278%) 0.000
                         Respell        6.50      (4.4%)       25.56     (16.5%)  293.2% ( 260% -  328%) 0.000
                          Fuzzy1        3.64      (4.5%)       15.91     (17.7%)  337.5% ( 301% -  376%) 0.000
                          Fuzzy2        1.75      (4.4%)        8.24     (17.1%)  371.7% ( 335% -  411%) 0.000
                        PKLookup        1.81      (4.0%)       10.82     (21.1%)  497.9% ( 454% -  544%) 0.000
                      AndHighLow       82.63      (4.7%)      516.40     (24.9%)  524.9% ( 472% -  582%) 0.000
```

2023-06-08 15:27 UTC, uschindler commented
Wouldn't aligning the refill against the buffer size be better in general?

My idea would be to always round down to multiples of buffer size. This would also cause the undelying hardware to read aligned blocks (unless it is a CFS file) and not do multiple reads per buffer size.

I know this might affect other cases positively or negatively, but to me this looks like more what MMapDirectory is doing behind the OS layer.

2023-06-08 15:34 UTC, romseygeek commented
> Wouldn't aligning the refill against the buffer size be better in general?

This is tricky because there are cases when you want to read multiple bytes over a buffer size boundary - eg you can call `readLong(1023)` and that would require a non-aligned buffer.

2023-06-08 16:40 UTC, uschindler commented
I am aware of that. The psgong algorithms of the OS do the same in mmap. If you read 1023 bytes it might need to read 2 pages from disk.

Maybe do something like: if the size to be read is larger than half of buffer size, read jnsligned. Otherwise align.

2023-06-09 09:24 UTC, romseygeek commented on lucene/core/src/java/org/apache/lucene/store/BufferedIndexInput.java
> +      if (bufferStart + bufferSize - pos <= 1) {
I've rewritten this to extract a `maybeRefillBuffer()` method that should be easier to read.

2023-06-09 09:25 UTC, romseygeek commented
`wikimedium1m` with the latest changes seems happy:

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
            BrowseDateTaxoFacets       59.83      (5.1%)       59.89      (5.8%)    0.1% ( -10% -   11%) 0.953
                          IntNRQ      225.60      (5.7%)      226.74      (6.0%)    0.5% ( -10% -   12%) 0.784
     BrowseRandomLabelTaxoFacets       53.85      (4.7%)       54.17      (5.7%)    0.6% (  -9% -   11%) 0.719
       BrowseDayOfYearTaxoFacets       60.13      (5.6%)       60.77      (5.2%)    1.1% (  -9% -   12%) 0.533
            BrowseDateSSDVFacets       18.69      (6.9%)       18.93      (8.2%)    1.3% ( -12% -   17%) 0.592
       BrowseDayOfYearSSDVFacets       75.67      (6.3%)       76.99      (7.5%)    1.7% ( -11% -   16%) 0.426
     BrowseRandomLabelSSDVFacets       52.05      (4.2%)       53.00      (5.1%)    1.8% (  -7% -   11%) 0.222
           BrowseMonthSSDVFacets      106.47      (6.7%)      114.22      (7.2%)    7.3% (  -6% -   22%) 0.001
           BrowseMonthTaxoFacets       89.34      (4.4%)       97.02      (7.0%)    8.6% (  -2% -   20%) 0.000
                      HighPhrase       16.58      (4.3%)       19.43      (5.9%)   17.2% (   6% -   28%) 0.000
                     LowSpanNear       19.02      (5.1%)       23.24      (7.3%)   22.2% (   9% -   36%) 0.000
                HighSloppyPhrase       30.08      (4.8%)       40.20      (5.9%)   33.6% (  21% -   46%) 0.000
                 MedSloppyPhrase       29.49      (4.9%)       41.40      (7.3%)   40.4% (  26% -   55%) 0.000
                     MedSpanNear       33.38      (5.3%)       46.97      (8.4%)   40.7% (  25% -   57%) 0.000
                    HighSpanNear       24.43      (5.2%)       34.88      (6.8%)   42.7% (  29% -   57%) 0.000
           HighTermDayOfYearSort       69.66      (5.8%)      106.43     (10.9%)   52.8% (  34% -   73%) 0.000
                      OrHighHigh       39.29      (5.7%)       60.21      (9.7%)   53.2% (  35% -   72%) 0.000
                     AndHighHigh       40.47      (5.5%)       62.89     (10.3%)   55.4% (  37% -   75%) 0.000
            HighIntervalsOrdered       39.09      (4.8%)       61.29      (8.2%)   56.8% (  41% -   73%) 0.000
                       LowPhrase       50.33      (5.5%)       81.72      (9.0%)   62.4% (  45% -   81%) 0.000
                       OrHighLow       47.83      (6.7%)       88.33     (11.7%)   84.7% (  62% -  110%) 0.000
                       MedPhrase       55.53      (5.0%)      107.45     (11.2%)   93.5% (  73% -  115%) 0.000
                         MedTerm      109.26      (5.8%)      213.10     (15.5%)   95.0% (  69% -  123%) 0.000
             MedIntervalsOrdered       40.05      (5.5%)       79.18     (11.5%)   97.7% (  76% -  121%) 0.000
                        HighTerm      124.45      (6.2%)      247.29     (14.5%)   98.7% (  73% -  127%) 0.000
                       OrHighMed       60.81      (5.7%)      122.54     (12.5%)  101.5% (  78% -  126%) 0.000
               HighTermMonthSort      352.94      (4.8%)      789.35     (20.2%)  123.7% (  94% -  156%) 0.000
                         LowTerm      110.88      (5.6%)      256.65     (14.4%)  131.5% ( 105% -  160%) 0.000
                      AndHighMed       59.13      (6.4%)      149.40     (15.8%)  152.7% ( 122% -  186%) 0.000
                        Wildcard       81.60      (6.3%)      210.43     (15.8%)  157.9% ( 127% -  191%) 0.000
                         Prefix3      161.67      (5.6%)      538.22     (23.7%)  232.9% ( 192% -  277%) 0.000
                 LowSloppyPhrase       76.67      (6.1%)      262.56     (20.5%)  242.5% ( 203% -  286%) 0.000
             LowIntervalsOrdered       85.02      (5.4%)      296.94     (22.1%)  249.3% ( 210% -  292%) 0.000
                         Respell        4.45      (5.4%)       17.49     (22.2%)  293.1% ( 251% -  338%) 0.000
                          Fuzzy2        2.58      (5.4%)       11.05     (23.4%)  328.1% ( 283% -  377%) 0.000
                          Fuzzy1        3.71      (5.2%)       18.13     (24.6%)  388.6% ( 341% -  441%) 0.000
                        PKLookup        1.90      (5.6%)       11.05     (32.4%)  481.8% ( 420% -  550%) 0.000
                      AndHighLow      101.98      (6.1%)      644.03     (58.7%)  531.5% ( 439% -  635%) 0.000
```

2023-06-09 09:27 UTC, uschindler approved these changes

2023-06-09 09:33 UTC, uschindler commented
Looks fine to me, maybe rename the method `maybeRefillBuffer(long,...)` to make clear it is used only for positional reads. There's already the `refill()` method.

How about `refill4PositionalRead(long,...)`?

2023-06-09 09:44 UTC, romseygeek commented
I've renamed it to `resolvePositionInBuffer` as that's what it actually does, with the refilling as a side-effect.

2023-06-09 10:01 UTC, jpountz approved these changes
I left some minor comments but it looks good to me in general.

2023-06-09 10:57 UTC, merged

2023-06-12 15:32 UTC, mikemccand commented
`wikimedium10k` is a tiny corpus, really just for quick testing that your benchy is setup correctly.  If you look at the QPS of each task they are ridiculously high :)

In the future it's better to run on at least `wikimedium10M` or `wikimediumall`.