Enhancement 11236 lazy compute similarity score
apache/lucene pull request #12480
Opened 2023-08-01 07:07 UTC by Jackyrie2

### Description
This is an update to the previous PR. While benchmarking potential improvements to `HNSWGraphBuilder.initializeFromGraph`, a few issues were found. 
* ordinal of newNode was used as index to the `scoringContext` map instead of using size as index
* the entire `scoringContext` was evaluated during call to `sortInternal` instead of just checking if the new index being sorted has a pre-computed score

Two new unit tests were added to demonstrate the bugs, this PR fixes the issues above.

### Benchmarking Result
To measure any meaningful latency improvements, we have to first create a big index and other small indexes, then once we force an index merge, the index writer will invoke`HNSWGraphBuilder.initializeFromGraph`. [KnnGraphTester](https://github.com/mikemccand/luceneutil/blob/master/src/main/KnnGraphTester.java#L690) was modified as the following:
1. first add 90% of documents
2. iw.commit()
3. forceMerge into 1 segment
4. set merge policy to NoMergePolicy and add the rest of the documents
5. set merge policy to LogDocMergePolicy
6. forceMerge into 1 segment again <- This step is specifically captured in the benchmark and I have verified in logs that initializeFromGraph is called exactly once in this step

From the benchmark results, we are calculating significantly fewer scores using the lazy eval enhancement. However, the indexMergeTime did not decrease as expected. 
<img width="1162" alt="benchmark" src="https://github.com/apache/lucene/assets/45954779/c8201249-85d0-4192-90b3-543ae72623b5">

2023-08-01 07:11 UTC, Jackyrie2 commented
@benwtrent @zhaih please take a look when you get a chance! I couldn't figure out how to update the existing PR, so I created a new one.

2023-08-01 13:52 UTC, benwtrent requested changes
Thank you so much for running the benchmark.

I have two optimizations you should apply. I suggest the following to re-measure:

 - Use realistic vector sizes. You should be testing with at least 768 Float32 dimensions. If you are not, please make sure that you are. This way the distance calculation has the typical expense.
 - If the performance still isn't improved (with my optimizations & on 768 dim vectors), I suggest utilizing JFR to see where the time is spent. It could be that creating and deleting objects/adding removing from the hashmap washes out any real improvement :/

2023-08-01 13:52 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +    scoringContext = new HashMap<>();
Pre-allocate to `maxSize`. We should avoid making the hashmap grow as we add things.

2023-08-01 13:52 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +    }
You should simplify and only call the map once.
```suggestion
    // Check if we need to compute score
    ScoringFunction maybeScoringFunction = scoringContext.remove(sortedNodeSize);
    if (maybeScoringFunction != null) {
      score[sortedNodeSize] = maybeScoringFunction.calculateScore();
    }
```

2023-08-01 18:28 UTC, zhaih requested changes
Hi Jack, thanks for doing the benchmark and I think the count of scoring computation does indicate the optimization is worth trying.

To further squeeze the performance and show the benefit, I think we need to optimize the data structure so that it doesn't create too much overhead during the graph build.
I have several suggestions below, and let me know what you think!

Also +1 to @benwtrent 's suggestion about using 768 vectors to further testing.
Thanks again for the hardwork!

2023-08-01 18:28 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +    scoringContext = new HashMap<>();
we don't need hashmap actually, I believe an array with length of `maxSize` is more than enough, as we're at most mapping `idx` to `ScoringFunction` right?

2023-08-01 18:28 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
To further optimize the memory usage and eliminate potential GC overhead, I would suggest not storing `ScoringFunction` at all.
In theory, to compute a score, we need 3 things: SimilarityFunction, node_emb_1, node_emb_2. Where node embeddings can be get by calling `vectors.vectorValue(nodeId)` from `HnswGraphBuilder`, and also `SimilarityFunction` is held by `HnswGraphBuilder`.
That means, we don't need to even store the similarityFunction, and two bytes array beforehand, we can let the `HnswGraphBuilder` pass in a `BiFunction<Integer, Integer, Float>` to perform scoring execution when we need it and inside `NeighborArray` we just need to give two nodes' id to that function. That way, we don't need to store extra context inside `NeighborArray` and also avoid holding a lot of `byte[]` for too long. (If you think about it, we're holding all byte/float arrays necessary for score computation until we computed it or the graph is constructed, that's a huge GC load if your computer doesn't have enough memory)

2023-08-01 18:36 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +    scoringContext = new HashMap<>();
@zhaih yes! you are correct. Just have an array of `maxSize` works and `null` means there is no scoring function.

2023-08-01 18:51 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
I like this idea.

@zhaih instead of adding a function reference to the `NeighborArray#ctor`, why not pass the function to the `NeighborArray#sort()` method?

2023-08-01 21:00 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
> why not pass the function to the NeighborArray#sort() method?

Yeah +1

> This obviates the need for any additional structures, if score==-1 calculate via the method provided to sort().

I have one concern for this, that `-1` might be a valid score itself, but we can always have an additional integer, like `noScoreIndex` or so, to indicate upto which index we haven't calculated the score. (Because those nodes will always be sit in the front of the score array)

2023-08-01 21:22 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
Score "NaN" is probably best to cover our bases :)

2023-08-01 21:53 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
Oh right, I forgot Java has `NaN`, yeah then I guess `NaN` will be the best.

2023-08-02 04:55 UTC, Jackyrie2 commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
>    private int insertSortedInternal() {
This is a wonderful thread, I am learning a lot! Let me take yall's suggestions and see how much more performance we can gain. Again, really appreciate your help!

2023-08-03 20:20 UTC, Jackyrie2 commented
Here is a quick re-run of benchmark(100 dim vectors)  on the optimized code with a 90% - 10% split on documents addition:

Baseline -> old candidate -> optimized candidate:
253,234,833 -> 265,153,500 -> 246,373,375
3,845,039,583 -> 4,338,130,875 -> 3,674,674,583
10,131,094,959 -> 9,869,441,083 -> 9,569,986,875

I will run the benchmark on 768 dim vectors later.

2023-08-07 18:15 UTC, Jackyrie2 commented
### Benchmark with 768-dimension vectors
<img width="1081" alt="Screenshot 2023-08-07 at 10 15 01 AM" src="https://github.com/apache/lucene/assets/45954779/924a1e3f-7649-46b2-9fe2-c0b24d78c976">

2023-08-07 21:29 UTC, zhaih commented
Thank you @Jackyrie2 for a lot of benchmarking! Since we have already made it lightweight enough (requires no extra memory usage on NeighborArray) and the benchmark has shown mostly positive results(Benchmark does have quite a lot of noises, especially if you're running it with your local machine, if you want , maybe write some simple bash loop and run the evaluation 3 - 5 times and use the average), I would say this PR is a good optimization.

But it does need some more documentation I think as the NeighborArray is already complex enough, so I will try to carefully review it again recently.

Thank you!

2023-08-22 23:14 UTC, zhaih reviewed
I left some small comments, overall it looks good to me!

2023-08-22 23:14 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java
> +        case FLOAT32 -> vectorValue = (float[]) vectors.vectorValue(nodeOrd);
Let's take this part outside of lambda to reduce number of times we call `vectorValue`, this operation involves some seek and parse operation on off-heap memory.

2023-08-22 23:14 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +  interface ScoringFunction {
Javadoc for both interface and the method?

2023-08-22 23:14 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java
> +//          float score =
Let's remove those commented code?

2023-08-22 23:16 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java
> +      System.out.println("Node: " + tmpNode + "   Score: " + tmpScore);
remove this?

2023-08-22 23:24 UTC, zhaih commented
Ah sorry I almost forget:
don't forget to create a CHANGES.txt entry :)

2023-08-31 23:16 UTC, zhaih approved these changes
LGTM, I don't think there's a need to make it Lucene 10 only? (we're not breaking any APIs)

2023-08-31 23:16 UTC, zhaih commented on lucene/CHANGES.txt
> +* GITHUB##12371: enable lazy computation of similarity score during initializeFromGraph (Jack Wang)
Put it under Lucene 9.8?

2023-08-31 23:16 UTC, zhaih commented on lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java
>            // we are not sure whether the previous graph contains
Update this comment like
`We will compute those scores lazily when we need to pop out the non-diverse nodes`?

2023-09-01 06:02 UTC, zhaih approved these changes

2023-09-01 06:05 UTC, zhaih commented
@Jackyrie2 Seems the precommit fails?

2023-09-01 18:05 UTC, merged

2023-09-01 18:39 UTC, zhaih commented
Merged and backported