TaskExecutor waits for all tasks to complete before returning
apache/lucene pull request #12523
Opened 2023-08-28 20:56 UTC by quux00

The TaskExecutor used by IndexSearcher and AbstractKnnVectorQuery
waits until all tasks have finished before returning, even when
one or more of the tasks throw an Exception.

2023-09-05 08:12 UTC, javanna requested changes
Thanks for working on this @quux00 ! The fix looks good to me, I think we can improve on the testing side, I left a comment around that.

2023-09-05 08:12 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
Can we find another way to test this and remove the need for the sleep in this test? Perhaps we could use a count down latch and count down on each scorer, to make sure that they are all called, and instead of the assertion on the number of leaves, simply wait on the latch to be counted down?

2023-09-28 20:37 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
I removed the sleep and added a CountDownLatch that acts to wait until all exceptions have been thrown before the `scorer` methods that are NOT throwing Exceptions have to wait before they increment the `callsToScorer` counter.

With the original implementation of `TaskExecutor#invokeAll` this test fails about 80% of the time on my machine (I ran it about 100 times), whereas it always passes with the new impl of `invokeAll`. I don't see how to make it fully deterministically fail with the old `invokeAll` since we need the Exception to always get thrown by the "Exception case" scorers _before_ the non-Exception-case scorers finish.  You could put in a latch that the test waits upon that gates the non-Exception-case scorers (don't finish until the test has caught the Exception from invokeAll) - that would deterministically fail with the old version of `invokeAll`, but would never pass with the new code (it would hang indefinitely).

Let me know if you see a clean way to make it deterministic with both impls of `invokeAll`.

2023-09-28 20:37 UTC, quux00 commented on lucene/core/src/java/org/apache/lucene/search/TaskExecutor.java
> +        exc = new RuntimeException(e.getCause());
I added this change and the tests are passing.

2023-10-02 18:47 UTC, javanna reviewed
I left some nits on the testing part but it looks good already. Thanks!

2023-10-02 18:47 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    }
I think that this is incorrect, maybe due to a bad merge? That's because we now unconditionally offload to the executor.

2023-10-02 18:47 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            return slices.toArray(new LeafSlice[0]);
it would also be fine to call the existing slices method providing 1,1 as the threshold arguments. That should achieve the same end-goal.

2023-10-02 18:47 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    int fixedThreads = leaves.size() == 1 ? 1 : leaves.size() / 2;
how many leaves max may we have ? I am wondering if we may end up creating too many threads. Would it hurt the test to lower the number of threads?

2023-10-02 18:47 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +          exc.getMessage(), Matchers.containsString("MatchAllOrThrowExceptionQuery Exception"));
would it make sense to also check the suppressed exception? That could also be a separate test if it's easier, without randomized behaviour. Or you could pre-define the order in which exceptions may be thrown, which is easy to preserve as you already have an atomic counter. That should make checking the suppressed exception relatively easy.

2023-10-02 18:47 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +              latch.await(5000, TimeUnit.MILLISECONDS);
maybe add a comment here to explain that the slices that don't throw will wait for all the exceptions to be thrown before proceeding, in order to make the test more deterministic.

2023-10-02 18:50 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
> You could put in a latch that the test waits upon that gates the non-Exception-case scorers (don't finish until the test has caught the Exception from invokeAll) - that would deterministically fail with the old version of invokeAll, but would never pass with the new code (it would hang indefinitely).

I am not even sure that that would work, because in order to get the exception, the new code needs to wait for all slices, and if the slices are waiting for us to get the exception, that sounds like a deadlock?

I am thinking that the current test is good enough. It would fail quick enough for us to notice if we stopped waiting for all slices to be completed.

2023-10-02 18:53 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
Thinking more of this, perhaps using a single threaded executor, or even one that executes on the caller thread would make the test more repeatable? Do we need to leverage parallel execution to test the behaviour we are introducing? It seems like with a single thread we could even simplify the test and remove the latch?

2023-10-02 18:59 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    }
oh well, I guess I am wrong because tests succeed :)

2023-10-02 20:41 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
Using a single threaded executor would make the test more repeatable, but it also passes with the original implementation of `TaskExecutor#invokeAll`, so it doesn't really test the core change of the ticket.

It passes with the existing `invokeAll` functionality because that method calls the `task.run()` on all tasks (Callables now) _before_ moving to the second part of the method where it cycles through the Futures and calls `get`. The key aspect of the test is that it needs to ensure that all threads have finished before `invokeAll` returns in a truly concurrent multi-threaded scenario.

What we really want is a way to check that all `future.get` methods have been called in invokeAll before it returns, but I couldn't find a way to do that.

So you either need a probabilistic test like I currently have or we would need some trick to sort of test what we want with a single threaded executor, such as:

always throw at least two exceptions (except for tests where only one task is created by random chance) - and make sure that one of those exceptions is thrown by the last task to be processed. Then you would prove that the invokeAll method is waiting for all tasks to finish even when exceptions are thrown by "intermediate" tasks. I can try implementing that model, but it would require some documentation for maintainers to see what needs to be done to ensure the test is actually testing the key feature of the ticket.

2023-10-02 21:27 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            return slices.toArray(new LeafSlice[0]);
Got it. Fixed.

2023-10-02 21:27 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    int fixedThreads = leaves.size() == 1 ? 1 : leaves.size() / 2;
Fixed. I'll put a max of 8 threads.

2023-10-02 21:27 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +          exc.getMessage(), Matchers.containsString("MatchAllOrThrowExceptionQuery Exception"));
Good idea.

2023-10-02 21:31 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +              latch.await(5000, TimeUnit.MILLISECONDS);
Added.

2023-10-02 23:56 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +            RandomizedTest.sleep(25);
I pushed two new commits - one that address all feedback except this one. The final one then changes the test to use a single threaded executor and throwing two exceptions - at the beginning and end of the sequential flow of tasks. We can decide which test we like better and revert the last commit if necessary.

2023-10-03 08:54 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    }
I am still not getting what has changed that makes the additional if required in this test. I thought that we offload to the executor even with a single segment, hence `assertEquals(leaves.size(), numExecutions.get());` should be comprehensive, even for when there are no segments. Have you run multiple iterations with this change? Was the test failing for you that made you change it?

2023-10-03 09:11 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    }
I confirmed locally that the test fails in some cases with your change, but does not fail with the previous assertion. Can you revert this bit please?

2023-10-03 10:22 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +              task.run();
I think that I mislead you with this suggestion, sorry. I would rather use a single threaded executor instead. That is rather slow as it executes one task at a time, but it's executing on a separate thread hence the `execute` call does not block which is more realistic, otherwise you indeed implicitly wait for all tasks to be completed because invokeAll first submits them and then waits for them all to complete.

We have control over the future (because we create a FutureTask in TaskExecutor), but it sounds artificial to e.g. override `get` to ensure it is called. I would like to rather have a higher level test that verifies that no running tasks are left behind once the overall top-level operation returns.

I have been thinking that it probably makes sense to move this test to TestTaskExecutor and make it less generic. `invokeAll` takes now a collection of callables and perhaps you can test that independently of docs and segments created. Possibly increasing the number of tasks is going to make the test more repeatable. I think we can live with the probabilistic nature of this test though.

The following:

```
  public void testInvokeAllDoesNotLeaveTasksBehind() {
      TaskExecutor taskExecutor = new TaskExecutor(executorService);
      AtomicInteger tasks = new AtomicInteger(0);
      List<Callable<Void>> callables = new ArrayList<>();
      callables.add(() -> {
          throw new RuntimeException();
      });
      for (int i = 0; i < 99; i++) {
          callables.add(() -> {
              tasks.incrementAndGet();
              return null;
          });
      }
      expectThrows(RuntimeException.class, () -> taskExecutor.invokeAll(callables));
      assertEquals(99, tasks.get());
  }
```

fails without the wait 903 times out of 1000 on my machine. It is also much simpler and does not require a custom query either.

I would still consider testing suppressed exceptions and wait in two different methods.

2023-10-03 15:00 UTC, quux00 commented on lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
> +    }
Fixed.

2023-10-03 18:13 UTC, javanna commented
This looks great thanks @quux00 ! Could you add an entry to the lucene/CHANGES.txt file under Lucene 9.9 please?

2023-10-05 08:22 UTC, javanna approved these changes
LGTM

2023-10-05 08:25 UTC, merged

2023-10-05 08:25 UTC, javanna commented
Thanks @quux00 !