Add a merge policy wrapper that performs recursive graph bisection on merge.
apache/lucene pull request #12622
Opened 2023-10-04 13:11 UTC by jpountz

This adds `BPReorderingMergePolicy`, a merge policy wrapper that reorders doc IDs on merge using a `BPIndexReorderer`.
 - Reordering always run on forced merges.
 - A `minNaturalMergeNumDocs` parameter helps only enable reordering on the larger merged segments. This way, small merges retain all merging optimizations like bulk copying of stored fields, and only the larger segments - which are the most important for search performance - get reordered.
 - If not enough RAM is available to perform reordering, reordering is skipped.

To make this work, I had to add the ability for any merge to reorder doc IDs of the merged segment via `OneMerge#reorder`. `MockRandomMergePolicy` from the test framework randomly reverts the order of documents in a merged segment to make sure this logic is properly exercised.

2023-10-04 14:46 UTC, jpountz commented
The diff is large because I had to introduce a new `SlowCompositeCodecReaderWrapper`, which effectively does the merge (lazily) and can be fed to the reordering logic prior to actually running the merge. The rest of the change is reasonable (at least for now).

2023-10-12 18:09 UTC, s1monw requested changes
I did a first pass on that and left some comments and questions, nothing major. I left some nits on the way but have questions to be clarified before I can continue. thanks man for adding this change.

2023-10-12 18:09 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +        MergeState.DocMap compactionDocMap = mergeState.docMaps[0];
this really confuses me. Why do we only look at the first element of the docMaps array and never advance to the next segment?

2023-10-12 18:11 UTC, s1monw commented
just for the record. I think we should record if a segment was written and it contains blocks and make it viral. that might be a good idea anyway.

2023-10-17 09:10 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                  int reorderedDocId = reorderDocMap.get(docID);
We could try to combine the two doc maps.

I did it this way to try to keep the reordering logic and the merging logic as independent as possible. On the one hand, we have the reordering logic that works on a merged view of the input segments and doesn't care about deletes. On the other hand, we have the merge logic that computes the mapping between doc IDs in input segments and doc IDs in the merged segment (often just compacting deletes, ie. if index sorting is not enabled).

If we wanted to better combine these two things, we'd need to either ignore the `MergeState`'s doc maps or somehow make `MergeState` aware of the reordering. Today `MergeState` is completely unaware of the reordering, from its perspective it just needs to run a singleton merge (single input codec reader) and its only job is to reclaim deletes.

2023-10-17 09:21 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/index/SlowCompositeCodecReaderWrapper.java
> +  public synchronized int numDocs() {
This tries to cover for leaves that have a lazy `numDocs` impl. I added a comment.

2023-10-17 09:24 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +        MergeState.DocMap compactionDocMap = mergeState.docMaps[0];
The above line already has an assertion, I'll add a comment too.

2023-10-18 08:05 UTC, gf2121 commented on lucene/join/src/test/org/apache/lucene/search/join/TestBlockJoin.java
> +    config.setMergePolicy(newMergePolicy(random(), false));
MergePolicy is set twice :)

2023-10-18 09:15 UTC, jpountz commented on lucene/join/src/test/org/apache/lucene/search/join/TestBlockJoin.java
> +    config.setMergePolicy(newMergePolicy(random(), false));
Woops, thanks for catching!

2023-11-21 09:51 UTC, jpountz commented
@s1monw Could you take another look?

2023-11-21 10:11 UTC, s1monw requested changes
Left some minor suggstions LGTM otherwise

2023-11-21 10:11 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +    merge.setMergeInfo(merge.info);
did we have a test that realized that merge.info is missing?

2023-11-21 10:11 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/MergePolicy.java
> +      return totalMaxDoc;
<3

2023-11-21 10:11 UTC, s1monw commented on lucene/misc/src/java/org/apache/lucene/misc/index/BPReorderingMergePolicy.java
> +            private boolean reordered = false;
maybe make that a setOnce?

2023-11-21 10:11 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                new MergeState.DocMap() {
maybe we can make DocMap an interface and then just use a lambda here and in other places. would look much nicer. I can also do that in  a different PR after this is in.

2023-11-21 10:11 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +        assert mergeState.docMaps.length == 1;
can you put the length in the message. It will be helpful if we run in to an error here

2023-11-21 10:11 UTC, s1monw commented on lucene/misc/src/java/org/apache/lucene/misc/index/BPReorderingMergePolicy.java
> +              if (reader.numDocs() < minNumDocs) {
I guess it's style, but can we maybe only have a single return statement here?

2023-11-21 10:11 UTC, s1monw commented on lucene/misc/src/java/org/apache/lucene/misc/index/BPReorderingMergePolicy.java
> +                  Collections.singletonMap("bp.reordered", Boolean.toString(reordered)));
use the constant here `REORDERED`?

2023-11-22 15:52 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +    merge.setMergeInfo(merge.info);
Yes, some of the new tests failed because the new merge policy records that a segment has been reordered in the segment's diagnostics. Let me add dedicated tests for setMergeInfo.

2023-11-22 16:44 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                new MergeState.DocMap() {
I'll leave it to you for a follow-up. :)

2023-11-22 16:46 UTC, jpountz commented
@s1monw I pushed a commit that should address your feedback

2023-11-23 10:25 UTC, s1monw approved these changes
LGTM

2023-11-23 12:25 UTC, merged