TestIndexWriterOnVMError.testUnknownError times out (fixes potential IW deadlock on tragic exceptions).
apache/lucene pull request #12751
Opened 2023-11-03 10:45 UTC by dweiss

Fixes #12654.

2023-11-03 11:34 UTC, s1monw requested changes
I left two comments, thanks for opening that

2023-11-03 11:34 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +          } catch (Throwable t) {
I don't think we need that, it will be handled in block below?

2023-11-03 11:34 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
IMO we should also notify all threads waiting on the monitor in the case of an exception.

2023-11-03 12:30 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +          } catch (Throwable t) {
this was deliberate so that notifyAll would still be called, even if something happened. In fact, the finally block is not necessary - it's a drop-through with catch (Throwable), I just wanted to make it explicit that we need to set those fields.

2023-11-03 12:31 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
As commented above, it'll be called even if something happens. I didn't want to move that notify out of the synchronized block because this would mean the need to re-acquire the lock?

2023-11-03 14:43 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
not sure we are talking about the same thing. maybe do it like this:

```diff
--- a/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
+++ b/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
@@ -2560,13 +2560,15 @@ public class IndexWriter
 
           // close all the closeables we can (but important is readerPool and writeLock to prevent
           // leaks)
-          IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
-          writeLock = null;
-          closed = true;
-          closing = false;
-
-          // So any "concurrently closing" threads wake up and see that the close has now completed:
-          notifyAll();
+          try {
+            IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
+          } finally {
+            writeLock = null;
+            closed = true;
+            closing = false;
+            // So any "concurrently closing" threads wake up and see that the close has now completed:
+            notifyAll();
+          }
         }
       } catch (Throwable t) {
         throwable.addSuppressed(t);
```

2023-11-03 15:56 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
Ah, I see it now. Sure, I'll move it.  Out of curiosity - what's going to happen if an exception is thrown from here (it's before the synchronization block)?
```
        // Must not hold IW's lock while closing
        // mergeScheduler: this can lead to deadlock,
        // e.g. TestIW.testThreadInterruptDeadlock
        IOUtils.closeWhileHandlingException(mergeScheduler);
```

2023-11-04 13:16 UTC, s1monw commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
yeah you are right, this is also a recipe for deadlocks here... maybe we should do something like this:

```diff
--- a/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
+++ b/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
@@ -2463,7 +2463,15 @@ public class IndexWriter
     if (infoStream.isEnabled("IW")) {
       infoStream.message("IW", "rollback");
     }
-
+    Closeable cleanupAndNotify =
+        () -> {
+          assert Thread.holdsLock(this);
+          writeLock = null;
+          closed = true;
+          closing = false;
+          // So any "concurrently closing" threads wake up and see that the close has now completed:
+          notifyAll();
+        };
     try {
       synchronized (this) {
         // must be synced otherwise register merge might throw and exception if merges
@@ -2531,43 +2539,35 @@ public class IndexWriter
         // after we leave this sync block and before we enter the sync block in the finally clause
         // below that sets closed:
         closed = true;
-
-        IOUtils.close(writeLock); // release write lock
-        writeLock = null;
-        closed = true;
-        closing = false;
-        // So any "concurrently closing" threads wake up and see that the close has now completed:
-        notifyAll();
+        IOUtils.close(writeLock, cleanupAndNotify); // release write lock
       }
     } catch (Throwable throwable) {
       try {
         // Must not hold IW's lock while closing
         // mergeScheduler: this can lead to deadlock,
         // e.g. TestIW.testThreadInterruptDeadlock
-        IOUtils.closeWhileHandlingException(mergeScheduler);
-        synchronized (this) {
-          // we tried to be nice about it: do the minimum
-          // don't leak a segments_N file if there is a pending commit
-          if (pendingCommit != null) {
-            try {
-              pendingCommit.rollbackCommit(directory);
-              deleter.decRef(pendingCommit);
-            } catch (Throwable t) {
-              throwable.addSuppressed(t);
-            }
-            pendingCommit = null;
-          }
-
-          // close all the closeables we can (but important is readerPool and writeLock to prevent
-          // leaks)
-          IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
-          writeLock = null;
-          closed = true;
-          closing = false;
-
-          // So any "concurrently closing" threads wake up and see that the close has now completed:
-          notifyAll();
-        }
+        IOUtils.closeWhileHandlingException(
+            mergeScheduler,
+            () -> {
+              synchronized (this) {
+                // we tried to be nice about it: do the minimum
+                // don't leak a segments_N file if there is a pending commit
+                if (pendingCommit != null) {
+                  try {
+                    pendingCommit.rollbackCommit(directory);
+                    deleter.decRef(pendingCommit);
+                  } catch (Throwable t) {
+                    throwable.addSuppressed(t);
+                  }
+                  pendingCommit = null;
+                }
+                // close all the closeables we can (but important is readerPool and writeLock to
+                // prevent
+                // leaks)
+                IOUtils.closeWhileHandlingException(
+                    readerPool, deleter, writeLock, cleanupAndNotify);
+              }
+            });
       } catch (Throwable t) {
         throwable.addSuppressed(t);
       } finally {
```

2023-11-05 18:03 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
>            notifyAll();
Yep, looks good. I'm sorry for replying late - I was away and couldn't do it properly before. I'll post a patch in a minute.

2023-11-06 19:01 UTC, dweiss commented
I pushed the requested changes, @s1monw . No rush, just wanted to let you know.

2023-11-08 07:43 UTC, s1monw approved these changes
LGTM thanks Dawid

2023-11-08 08:47 UTC, merged