Normalize written scalar quantized vectors when using cosine similarity
apache/lucene pull request #12780
Opened 2023-11-07 21:24 UTC by kevindrosendahl

### Description

When using cosine similarity, the `ScalarQuantizer` normalizes vectors when calculating quantiles and `ScalarQuantizedRandomVectorScorer` normalizes query vectors before scoring them, but `Lucene99ScalarQuantizedVectorsWriter` does not normalize the vectors prior to quantizing them when producing the quantized vectors to write to disk. This PR normalizes vectors prior to quantizing them when writing them to disk.

Recall results on my M1 with the `glove-100-angular` data set (all using `maxConn`: 16, `beamWidth` 100, `numCandidates`: 100, `k`: 10, single segment):
| Configuration | Recall | Average Query Duration |
|---------------|-------|-----------------| 
| Pre-patch no quantization | 0.78762 | 0.68 ms |
| Pre-patch with quantization | 8.999999999999717E-5 | 0.45 ms |
| Post-patch no quantization | 0.78762 | 0.70 ms |
| Post-patch with quantization | 0.66742 | 0.66 ms |

2023-11-07 21:26 UTC, kevindrosendahl commented on lucene/core/src/test/org/apache/lucene/codecs/lucene99/TestLucene99HnswQuantizedVectorsFormat.java
>  public class TestLucene99HnswQuantizedVectorsFormat extends BaseKnnVectorsFormatTestCase {
This test was always using normalized vectors as input. I changed it to use vectors that aren't guaranteed to be normalized, but kept all existing tests using normalized vectors so as not to change other tests incidentally.

2023-11-08 12:58 UTC, benwtrent requested changes
Some questions and requested changes. Thank you for finding this bug!

2023-11-08 12:58 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99ScalarQuantizedVectorsWriter.java
> +        float[] copy = new float[v.length];
we should only have one `copy` array created. Outside the loop check if we need it, if so, initialize and then you can use it here in the loop. Seems better to do that than create a new `float[dim]` for every vector.

2023-11-08 12:58 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99ScalarQuantizedVectorsWriter.java
> +        float[] copy = new float[v.length];
Similar to above ^

2023-11-08 12:58 UTC, benwtrent commented on lucene/test-framework/src/java/org/apache/lucene/tests/index/BaseKnnVectorsFormatTestCase.java
> +          new KnnFloatVectorField("v2", randomNormalizedVector(30), similarityFunction));
Were you getting many failures with your change when you put non-normalized vectors? The fix to normalize on cosine should be transparent. The caller should never be aware that it happens as it only occurs for things that are then quantized.

2023-11-08 17:33 UTC, kevindrosendahl commented on lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99ScalarQuantizedVectorsWriter.java
> +        float[] copy = new float[v.length];
Good catch, changed in https://github.com/apache/lucene/pull/12780/commits/1d9f68be208ad2b111640d370bee8f410203099f

2023-11-08 17:33 UTC, kevindrosendahl commented on lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99ScalarQuantizedVectorsWriter.java
> +        float[] copy = new float[v.length];
Also changed in https://github.com/apache/lucene/pull/12780/commits/1d9f68be208ad2b111640d370bee8f410203099f

2023-11-08 17:42 UTC, kevindrosendahl commented on lucene/test-framework/src/java/org/apache/lucene/tests/index/BaseKnnVectorsFormatTestCase.java
> +          new KnnFloatVectorField("v2", randomNormalizedVector(30), similarityFunction));
The issue I was having was that I couldn't reproduce the issue in `testQuantizedVectorsWriteAndRead()` because `BaseKnnVectorsFormatTestCase::randomVector()` [always normalizes the vectors it creates](https://github.com/apache/lucene/blob/20d5de448a739beb85e380d153fb13bf1817a8d6/lucene/test-framework/src/java/org/apache/lucene/tests/index/BaseKnnVectorsFormatTestCase.java#L1236). That means that the persisted vectors matched the expected vectors (even after normalizing the expected vectors when using cosine).

To isolate the effects of the test changes from normalized to potentially non-normalized vectors to just this test, I kept the existing behavior (i.e. existing tests use normalized vectors) by renaming the existing method from `randomVector()` to `randomNormalizedVector()`, then adding a new method `randomVector()` which does not normalize the vectors. This commit https://github.com/apache/lucene/pull/12780/commits/7cb2375e850f963630788028af34e3275fc5af09 has those changes.

Not sure if that really answers your question, I didn't try changing any other tests to use non-normalized vectors. I'm happy to structure all of these tests however makes sense to you.

2023-11-08 17:46 UTC, benwtrent commented on lucene/test-framework/src/java/org/apache/lucene/tests/index/BaseKnnVectorsFormatTestCase.java
> +          new KnnFloatVectorField("v2", randomNormalizedVector(30), similarityFunction));
@kevindrosendahl I see now! thank you!

2023-11-08 17:46 UTC, benwtrent commented on lucene/test-framework/src/java/org/apache/lucene/tests/index/BaseKnnVectorsFormatTestCase.java
> +          new KnnFloatVectorField("v2", randomNormalizedVector(30), similarityFunction));
I will merge and backport once this is green.

2023-11-08 17:47 UTC, benwtrent approved these changes
great find!

2023-11-08 19:26 UTC, merged