Move group-varint encoding/decoding logic to DataOutput/DataInput
apache/lucene pull request #12841
Opened 2023-11-24 11:49 UTC by easyice

From issue: https://github.com/apache/lucene/issues/12826

The JMH benchmark with this PR on my Mac (Intel chip) :

java 17
```
Benchmark                                   (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.byteArrayReadGroupVInt       64  thrpt    5  5.519 ± 0.270  ops/us
GroupVIntBenchmark.byteArrayReadVInt            64  thrpt    5  4.075 ± 2.868  ops/us
GroupVIntBenchmark.byteBufferReadGroupVInt      64  thrpt    5  7.464 ± 1.618  ops/us
GroupVIntBenchmark.byteBufferReadVInt           64  thrpt    5  5.179 ± 0.470  ops/us
```

java 21
```
Benchmark                                   (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.byteArrayReadGroupVInt       64  thrpt    5   5.768 ± 0.305  ops/us
GroupVIntBenchmark.byteArrayReadVInt            64  thrpt    5   5.255 ± 0.110  ops/us
GroupVIntBenchmark.byteBufferReadGroupVInt      64  thrpt    5  11.551 ± 0.252  ops/us
GroupVIntBenchmark.byteBufferReadVInt           64  thrpt    5   5.611 ± 0.266  ops/us
```

2023-11-24 13:32 UTC, jpountz reviewed
I still don't feel great about the API taking longs, but otherwise I like this change. @uschindler might have opinions on the `MemorySegmentIndexInput` implementation.

Should we optimize `ByteBuffersDataInput` similarly (and then delegate in `ByteBuffersIndexInput`) to yield speedups with older Java releases as well?

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +  }
Can you add the same `catch (NullPointerException | IllegalStateException e)` that `readInt()` and other read methods have, for the case when the index input is closed?

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +  private static final int[] MASKS = new int[] {0xFF, 0xFFFF, 0xFFFFFF, 0xFFFFFFFF};
maybe rename to `GROUP_VINT_MASKS` or something along these lines now that this logic moved to a class which is not only about group vint?

Also in general I prefer having constants before instance members in the class definition.

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/DataOutput.java
> +  BytesRef groupVIntBytes;
BytesRefBuilder feels like a better fit for how you're using it (using `length` rather than `offset` to track the number of written bytes). Also let's make it `private`?

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/test/org/apache/lucene/codecs/lucene99/TestGroupVInt.java
> +    Directory dir = FSDirectory.open(createTempDir());
Let's use `newFSDirectory` to add coverage for all Directory implementations?

```suggestion
    Directory dir = newFSDirectory(createTempDir());
```

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +    }
I don't think we have a test that covers this case well at the moment.

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/DataInput.java
> +  public void readGroupVInt(long[] docs, int offset) throws IOException {
Let's make this method private? This would force `MemorySegmentIndexInput` to copy the logic of `readGroupVInts` but this would also be better encapsulated?

2023-11-24 13:32 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/DataOutput.java
> +      writeVInt((int) values[off]);
Now that we're moving this to `DataOutput`, we probably need to check these casts, e.g. with `Math.toIntExact`.

2023-11-24 13:33 UTC, jpountz commented
And maybe `BufferedIndexInput` too for folks using `NIOFSDirectory`?

2023-11-24 14:14 UTC, easyice reviewed
Thank you for the fast review! I will try to do the similarly optimize  use `BitUtil.VH_LE_INT#get() ` in `ByteBuffersDataInput` and `BufferedIndexInput`

2023-11-24 14:14 UTC, easyice commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +    }
In `TestGroupVInt#testEncodeDecode` we use a range of [1-31] `bpv` and a ragne of [1-128] `numValues`,  For instance if the `bpv==2` and  `numValues==4` it will cover this case?

2023-11-24 14:14 UTC, easyice commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +  }
+1, Thanks!

2023-11-24 14:14 UTC, easyice commented on lucene/core/src/test/org/apache/lucene/codecs/lucene99/TestGroupVInt.java
> +    Directory dir = FSDirectory.open(createTempDir());
+1

2023-11-26 13:29 UTC, easyice commented
I did the similarly optimize in `BufferedIndexInput` and `BufferedIndexInput`, The benchmark with java 17 looks fine. In order to observe the diff after overriding `readGroupVInts`,I add `DataInput#readGroupVIntsBaseline` which is copy from `readGroupVInts`, it will be removed after code review.


Here is the JMH output for newly optimized, `byteBuffersReadGroupVIntBaseline` and `nioReadGroupVIntBaseline` means use the default implementation (`DataInput#readGroupVIntsBaseline`), the other is their own optimized implementations
```
Benchmark                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.byteBuffersReadGroupVInt              64  thrpt    5  5.384 ± 1.074  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline      64  thrpt    5  2.056 ± 0.365  ops/us
GroupVIntBenchmark.nioReadGroupVInt                      64  thrpt    5  8.787 ± 1.405  ops/us
GroupVIntBenchmark.nioReadGroupVIntBaseline              64  thrpt    5  5.281 ± 0.741  ops/us
```

2023-12-02 13:36 UTC, uschindler commented
Hi,
I have no time to review at moment, will come back next week.

Some thoughts:
- there's copy-paste code missing to MemorySegmentIndexInput for 20 and 19. But wen can do this later.
- ByteBufferIndexInput needs code to support MMapDirectory in older Java versions.

For both cases above make sure to exactly follow all try catch blocks and calling to super as fone in other bulk read methods.

It may also be needed to add a separate test to TestMultiMMap.

Also make sure to run tests with Java 17 and Java 19, 20, 21.

2023-12-02 13:45 UTC, uschindler commented
In general I am not sure if we really need specialization in Mmapdir. Without a benchmark showing improvement, I'd cancel this. Counting number of virtual calls is bullshit. This is all optimized away by Hotspot's inlining, so don't repeat code just because of a few method calls. CC @rmuir

2023-12-03 16:38 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/store/ByteBuffersDataInput.java
> +    docs[offset] = (int) BitUtil.VH_LE_INT.get(bytes, curPosition) & GROUP_VINT_MASKS[n1Minus1];
@jpountz Thanks for this suggestion, the performance is similar

2023-12-03 16:38 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/store/DataInput.java
> +  static final int[] GROUP_VINT_MASKS = new int[] {0xFF, 0xFFFF, 0xFFFFFF, 0xFFFFFFFF};
+1

2023-12-03 16:38 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/store/DataOutput.java
> +   * Encode integers using group-varint. It uses VInt to encode tail values that are not enough for
+1, Thanks, i like that

2023-12-03 16:38 UTC, easyice commented on lucene/core/src/test/org/apache/lucene/codecs/lucene99/TestGroupVInt.java
>  public class TestGroupVInt extends LuceneTestCase {
+1, cool!

2023-12-03 16:44 UTC, easyice commented
Thank you very much for your suggestions, i had fixed the comments from @jpountz, but the related to Mmapdir will be later(such as java19, java20 support), because we need to confirm whether to change it. i agree that we should be cautious here. in my understanding the optimized code is faster than the main branch probably because the optimized code doesn't need a `switch` statement in `GroupVIntUtil#readLongInGroup`, although it was inlined.


The JMH output for currently, it's similar to before we replaced `varHander` with `ByteBuffer#getInt()`
java17
```
Benchmark                                                 (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.byteBuffersReadGroupVInt                   64  thrpt    5   4.698 ± 2.039  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline           64  thrpt    5   2.167 ± 0.064  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt               64  thrpt    5   7.386 ± 0.524  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline       64  thrpt    5   7.358 ± 1.316  ops/us
GroupVIntBenchmark.nioReadGroupVInt                           64  thrpt    5   8.236 ± 1.052  ops/us
GroupVIntBenchmark.nioReadGroupVIntBaseline                   64  thrpt    5   5.381 ± 1.134  ops/us
```

java21
```
Benchmark                                                 (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.byteBuffersReadGroupVInt                   64  thrpt    5   4.622 ± 0.880  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline           64  thrpt    5   1.674 ± 0.245  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt               64  thrpt    5  10.165 ± 1.083  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline       64  thrpt    5   5.104 ± 0.388  ops/us
GroupVIntBenchmark.nioReadGroupVInt                           64  thrpt    5   9.527 ± 1.556  ops/us
GroupVIntBenchmark.nioReadGroupVIntBaseline                   64  thrpt    5   5.351 ± 0.621  ops/us
```

 @uschindler Thank you for take a look at this, here is the assembly output for `MemorySegmentIndexInput#readGroupVInt`, using command:  `java -XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly  --module-path lucene/benchmark-jmh/build/benchmarks --module org.apache.lucene.benchmark.jmh GroupVIntBenchmark.mmap`

<details>
<summary >assembly code</summary>

```

0801============================= C1-compiled nmethod ==============================
 ----------------------------------- Assembly -----------------------------------
|
00Compiled method (c1)    4890  610   !   2       org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt (243 bytes)
00 total in heap  [0x0000000110a6d290,0x0000000110a710d0] = 15936
  relocation     [0x0000000110a6d3e8,0x0000000110a6d650] = 616
01 main code      [0x0000000110a6d660,0x0000000110a6e7d8] = 4472
e9 stub code      [0x0000000110a6e7d8,0x0000000110a6e898] = 192
 |  oops           [0x0000000110a6e898,0x0000000110a6e8a8] = 16
60 metadata       [0x0000000110a6e8a8,0x0000000110a6e980] = 216
 scopes data    [0x0000000110a6e980,0x0000000110a6f788] = 3592
00 scopes pcs     [0x0000000110a6f788,0x0000000110a706c8] = 3904
 0000 dependencies   [0x0000000110a706c8,0x0000000110a706f8] = 48
 | 483b handler table  [0x0000000110a706f8,0x0000000110a70fe0] = 2280
 nul chk table  [0x0000000110a70fe0,0x0000000110a710d0] = 240

[Constant Pool (empty)]

[MachCode]
 [Entry Point]
b710  # {method} {0x000000016d4d56b0} 'readGroupVInt' '([JI)V' in 'org/apache/lucene/store/MemorySegmentIndexInput'
 | 0100 0075 | 0d48 83  # this:     rsi:rsi   = 'org/apache/lucene/store/MemorySegmentIndexInput'
87   # parm0:    rdx:rdx   = '[J'
| 1801   # parm1:    rcx       = int
00  #           [sp+0x230]  (sp of caller)
00
  0x000000010cd98108  0x0000000110a6d660: 448b 5608 | 49bb 0000 | 002c 0100 | 0000 4d03 | d34c 3bd0
: 01
e9  0x0000000110a6d674: ;   {runtime_call ic_miss_stub}
 4a  0x0000000110a6d674: 0f85 06aa | 5107 660f | 1f44 0000
00 [Verified Entry Point]
| 0000 4883   0x0000000110a6d680: 8984 2400 | c0fe ff55 | 4881 ec20 | 0200 0090 | 4181 7f20 | 0000 0000
|
bf00  0x0000000110a6d698: ;   {runtime_call StubRoutines (final stubs)}
 0100 | 0000 7517 | 4889 b700 |   0x0000000110a6d698: 7405 e801 | 0e50 0748 | 89b4 2480 | 0100 0048 | 8994 2488 | 0100 0089 | 8c24 9001 | 0000 48bf
0100 0048   0x0000000110a6d6b8: 60d1 526d | 0100 0000 | 8b5f 0883 | c302 895f | 0881 e3fe | 0f00 0083 | fb00 0f84
|
c787  0x0000000110a6d6d4: ;*aload_0 {reexecute=0 rethrow=0 return_oop=0}
                       ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@0 (line 319)
0801 | 0000 01  0x0000000110a6d6d4: 4c0e 0000 | 8b7e 3848
00
   0x0000000110a6d6dc: ;*getfield curSegment {reexecute=0 rethrow=0 return_oop=0}

                      ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@1 (line 319)
  0x000000010cd98128: 0000 e929 | 0000 0048 | 83bf 1001 | 0000 00  0x0000000110a6d6dc: c1e7 0348 | 83ff 000f | 842a 0000
75
   0x0000000110a6d6e8: ;   {metadata('jdk/internal/foreign/AbstractMemorySegmentImpl')}
| 17  0x0000000110a6d6e8: 0049 b8a0 | a40c 2d01 | 0000 0044 | 8b4f 0849 | ba00 0000 | 2c01 0000 | 004d 03ca | 4d3b 4138
48 89b7 | 10  0x0000000110a6d708: 0f85 370e | 0000 e900 | 0000 0048
01
 00  0x0000000110a6d714: ;*invokeinterface byteSize {reexecute=0 rethrow=0 return_oop=0}
00 |                       ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@4 (line 319)
48  0x0000000110a6d714: 8bdf 488b
c7
 87  0x0000000110a6d718: ;*getfield length {reexecute=0 rethrow=0 return_oop=0}
18 | 0100                      ; - jdk.internal.foreign.AbstractMemorySegmentImpl::byteSize@1 (line 244)
 00                      ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@4 (line 319)
01  0x0000000110a6d718: 5f10 488b


  0x0000000110a6d71c: ;*getfield curPosition {reexecute=0 rethrow=0 return_oop=0}
                       ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@10 (line 319)
 0x000000010cd98148: 0000 00e9 | 0800  0x0000000110a6d71c: 7e20 482b | df48 bf11 | 0000 0000 | 0000 0048 | 3bdf 0f8c

00  0x0000000110a6d730: ;*lcmp {reexecute=0 rethrow=0 return_oop=0}
00                       ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@17 (line 319)
|   0x0000000110a6d730: 2907 0000 | 488b fe48
48
83 87f0 |   0x0000000110a6d738: ;*invokevirtual readByte {reexecute=0 rethrow=0 return_oop=0}
0000                      ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@29 (line 325)
 00  0x0000000110a6d738: 8bf7 0f1f
01


 0x000000010cd98158:   0x0000000110a6d73c: ;   {optimized virtual_call}
  0x0000000110a6d73c: 4400 00e8
;   {metadata(method data for {method} {0x000000012817e820} 'unlock' '()V' in 'java/util/concurrent/locks/ReentrantLock')}

   0x0000000110a6d740: ; ImmutableOopMap {[384]=Oop [392]=Oop }
 0x000000010cd98158: 48be 9898 | 21                      ;*invokevirtual readByte {reexecute=0 rethrow=0 return_oop=0}
69                       ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@29 (line 325)
  0x0000000110a6d740: 3cac 5107
01
00  0x0000000110a6d744: ;   {other}
   0x0000000110a6d744: 0f1f 8400
|
0000  0x0000000110a6d748: ;*invokevirtual readByte {reexecute=0 rethrow=0 return_oop=0}
 8b                      ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@29 (line 325)
be  0x0000000110a6d748: b404 0000 | 25ff 0000 | 0048 8bf8 | c1ff 0689 | bc24 9401 | 0000 488b | d0c1 fa04 | 83e2 0389
 | ac  0x0000000110a6d768: 9424 9801 | 0000 488b | c8c1 f902 | 83e1 0389 | 8c24 9c01 | 0000 83e0 | 0389 8424 | a001 0000
00 0000 | 83c7 0289 | beac 0000 | 00  0x0000000110a6d788: 488b b424 | 8001 0000 | 448b 4638
81
   0x0000000110a6d794: ;*getfield curSegment {reexecute=0 rethrow=0 return_oop=0}
e7fe                      ; - org.apache.lucene.store.MemorySegmentIndexInput::readGroupVInt@65 (line 332)
   0x0000000110a6d794: 49c1 e003

| ff  0x0000000110a6d798: ;*getfiel [...]

2023-12-04 15:20 UTC, easyice commented
I ran the benchmark using `wikimediumall`, we can got a minor speed up on java21 with `MMapDirectory`,  but no significant improvement with `NIOFSDirectory`(java17),  because the `NIOFSDirectory` has some additional cost.

For task `prefix3`, the baseline of  `Lucene99PostingsReader.readVIntBlock` calls percentage in the flame graph: 

*  `NIOFSDirectory`  2.8%
*  `MMapDirectory`   9.9%

Here is the benchmark output with java 21, baseline(main), candidate(PR):

<details>
<summary>round 1</summary>

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
                         LowTerm      164.44     (11.4%)      161.36     (10.5%)   -1.9% ( -21% -   22%) 0.589
                     AndHighHigh       30.63      (4.5%)       30.13      (4.7%)   -1.6% ( -10% -    7%) 0.260
                          IntNRQ       15.46      (6.5%)       15.25      (4.1%)   -1.3% ( -11% -    9%) 0.437
                      AndHighMed       53.37      (7.9%)       52.67      (7.9%)   -1.3% ( -15% -   15%) 0.598
                       OrHighMed       41.16      (7.6%)       40.62      (6.5%)   -1.3% ( -14% -   13%) 0.556
                      TermDTSort       63.95      (9.3%)       63.25      (8.5%)   -1.1% ( -17% -   18%) 0.702
                       LowPhrase       34.09      (4.0%)       33.79      (4.6%)   -0.9% (  -9% -    8%) 0.514
                          Fuzzy2       33.43      (2.8%)       33.14      (3.7%)   -0.9% (  -7% -    5%) 0.399
                       MedPhrase       63.94      (4.0%)       63.47      (4.2%)   -0.7% (  -8% -    7%) 0.565
                      AndHighLow      347.49      (2.3%)      344.95      (3.5%)   -0.7% (  -6% -    5%) 0.435
                         MedTerm      300.87      (7.2%)      298.76      (5.7%)   -0.7% ( -12% -   13%) 0.731
                    OrNotHighLow      209.67      (3.5%)      208.27      (3.3%)   -0.7% (  -7% -    6%) 0.536
             MedIntervalsOrdered       15.79      (2.4%)       15.69      (2.6%)   -0.6% (  -5% -    4%) 0.450
                        HighTerm      228.97      (5.8%)      227.71      (4.5%)   -0.6% ( -10% -   10%) 0.737
                    HighSpanNear        4.51      (1.6%)        4.48      (1.8%)   -0.5% (  -3% -    2%) 0.314
                 MedSloppyPhrase       15.24      (3.1%)       15.17      (3.4%)   -0.5% (  -6% -    6%) 0.625
                     MedSpanNear        6.97      (2.1%)        6.95      (2.1%)   -0.3% (  -4% -    4%) 0.668
                      HighPhrase       19.21      (3.1%)       19.17      (3.4%)   -0.2% (  -6% -    6%) 0.841
               HighTermTitleSort       46.25      (3.2%)       46.16      (4.7%)   -0.2% (  -7% -    7%) 0.886
             LowIntervalsOrdered        9.01      (2.0%)        8.99      (1.9%)   -0.2% (  -4% -    3%) 0.794
                 LowSloppyPhrase       40.24      (3.4%)       40.18      (3.9%)   -0.2% (  -7% -    7%) 0.890
           HighTermDayOfYearSort      160.70      (2.9%)      160.45      (2.8%)   -0.2% (  -5% -    5%) 0.861
            HighTermTitleBDVSort        3.52      (4.0%)        3.51      (4.9%)   -0.1% (  -8% -    9%) 0.920
                HighSloppyPhrase       10.64      (3.8%)       10.63      (4.0%)   -0.1% (  -7% -    8%) 0.950
                       OrHighLow      286.00      (3.6%)      285.99      (3.4%)   -0.0% (  -6% -    7%) 0.997
            HighIntervalsOrdered        1.92      (3.2%)        1.92      (3.4%)   -0.0% (  -6% -    6%) 0.997
                         Respell       21.95      (2.1%)       21.95      (2.4%)   -0.0% (  -4% -    4%) 0.998
                     LowSpanNear        3.20      (1.6%)        3.20      (1.1%)    0.0% (  -2% -    2%) 0.977
                          Fuzzy1       45.64      (3.5%)       45.69      (3.7%)    0.1% (  -6% -    7%) 0.932
                   OrNotHighHigh      138.92      (3.8%)      139.06      (3.8%)    0.1% (  -7% -    7%) 0.935
                    OrNotHighMed      106.41      (6.1%)      106.55      (5.9%)    0.1% ( -11% -   12%) 0.946
                        PKLookup       94.25      (3.5%)       94.44      (3.2%)    0.2% (  -6% -    7%) 0.850
                    OrHighNotLow      190.58      (4.1%)      191.10      (3.3%)    0.3% (  -6% -    7%) 0.816
               HighTermMonthSort     1081.10      (4.7%)     1089.58      (7.1%)    0.8% ( -10% -   13%) 0.680
                      OrHighHigh       14.63      (5.1%)       14.76      (5.2%)    0.8% (  -9% -   11%) 0.603
                    OrHighNotMed      125.32      (3.6%)      126.40      (3.9%)    0.9% (  -6% -    8%) 0.463
                   OrHighNotHigh      187.08      (2.9%)      189.14      (3.4%)    1.1% (  -5% -    7%) 0.273
                        Wildcard       52.68      (3.2%)       53.31      (3.5%)    1.2% (  -5% -    8%) 0.265
                         Prefix3       15.10      (2.9%)       16.62      (3.1%)   10.0% (   3% -   16%) 0.000
```
</details>


<details>
<summary>round 2</summary>

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
                    OrNotHighMed      131.92      (6.5%)      127.91      (6.2%)   -3.0% ( -14% -   10%) 0.131
               HighTermMonthSort     1150.34      (4.7%)     1117.43      (5.3%)   -2.9% ( -12% -    7%) 0.071
                      TermDTSort       71.29      (6.2%)       69.81      (6.8%)   -2.1% ( -14% -   11%) 0.310
                      AndHighMed       55.29      (5.5%)       54.16      (5.8%)   -2.0% ( -12% -    9%) 0.252
                       OrHighMed       30.76      (5.7%)       30.18      (5.7%)   -1.9% ( -12% -   10%) 0.295
                   OrNotHighHigh      143.93      (4.5%)      141.50      (5.2%)   -1.7% ( -10% -    8%) 0.274
                   OrHighNotHigh      172.51      (4.4%)      169.68      (5.0%)   -1.6% ( -10% -    8%) 0.272
                         LowTerm      227.14     (10.1%)      223.62     (10.2%)   -1.6% ( -19% -   20%) 0.629
                    OrNotHighLow      317.49      (4.1%)      313.04      (5.0%)   -1.4% ( -10% -    8%) 0.331
                       MedPhrase       76.90      (5.5%)       75.84      (5.6%)   -1.4% ( -11% -   10%) 0.429
                    OrHighNotMed      201.60      (4.7%)      199.02      (4.7%)   -1.3% ( -10% -    8%) 0.391
                 LowSloppyPhrase       22.26      (4.6%)       22.00      (4.2%)   -1.2% (  -9% -    7%) 0.400
                    OrHighNotLow      151.23      (5.5%)      149.47      (4.9%)   -1.2% ( -10% -    9%) 0.481
                     AndHighHigh       19.39      (2.7%)       19.18      (2.6%)   -1.1% (  -6% -    4%) 0.196
                          Fuzzy1       35.55      (4.1%)       35.20      (5.0%)   -1.0% (  -9% -    8%) 0.495
                       OrHighLow      204.03      (4.3%)      202.34      (3.3%)   -0.8% (  -8% -    7%) 0.493
               HighTermTitleSort       71.31      (3.8%)       70.77      (4.4%)   -0.7% (  -8% -    7%) 0.566
                HighSloppyPhrase        3.55      (4.1%)        3.53      (4.1%)   -0.6% (  -8% -    7%) 0.632
                 MedSloppyPhrase        6.40      (3.6%)        6.37      (3.2%)   -0.6% (  -7% -    6%) 0.582
                     LowSpanNear        9.38      (1.6%)        9.33      (1.7%)   -0.6% (  -3% -    2%) 0.287
                      OrHighHigh       14.17      (2.1%)       14.10      (2.6%)   -0.5% (  -5% -    4%) 0.479
                          Fuzzy2       33.09      (2.7%)       32.94      (4.1%)   -0.5% (  -7% -    6%) 0.677
                      HighPhrase       19.05      (2.9%)       18.97      (2.8%)   -0.4% (  -5% -    5%) 0.616
                       LowPhrase       63.67      (3.9%)       63.39      (4.2%)   -0.4% (  -8% -    7%) 0.732
                         MedTerm      314.53      (5.9%)      313.31      (6.9%)   -0.4% ( -12% -   13%) 0.849
            HighTermTitleBDVSort        3.43      (3.9%)        3.42      (4.4%)  [...]

2023-12-05 09:29 UTC, jpountz reviewed
Thanks @easyice, I left some minor comments, it looks close!

2023-12-05 09:29 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/ByteBuffersDataInput.java
> +    blockOffset = blockOffset(pos);
We already computed `blockOffset()` above, can we avoid computing it twice, e.g. by replacing the `readByte()` call with `block.get(blockOffset++)`?

2023-12-05 09:29 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/DataOutput.java
> +  private BytesRefBuilder groupVIntBytes = new BytesRefBuilder();
Can it be made final?

2023-12-05 09:29 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +  public static void fallbackReadGroupVInt(DataInput in, long[] dst, int offset)
It doesn't need `fallback` as a prefix anymore now that it's in its own class. Let's document that this is a default implementation and that it is recommended to use `DataInput#readGroupVInts` directly rather than this method?

2023-12-05 09:29 UTC, jpountz commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +
Maybe copy `curSegment` to a local variable here, e.g. `MemorySegment curSegment = this.curSegment` so that the JVM doesn't have to worry about `curSegment` getting updated?

2023-12-05 09:29 UTC, jpountz commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      final int flag = readByte() & 0xFF;
Since we already did the job of checking that we have enough bytes left, we don't need `readByte()` to do it for us?

```suggestion
      final int flag = curSegment.get(LAYOUT_BYTE, curPosition++) & 0xFF;
```

2023-12-05 09:29 UTC, jpountz commented on lucene/test-framework/src/java/org/apache/lucene/tests/store/BaseDirectoryTestCase.java
> +      // test large data to covers multiple blocks in ByteBuffersDataInput
adding it explicitly since this is probably the most important case to cover

```suggestion
      // test large data to covers multiple blocks in ByteBuffersDataInput and MMapDirectory via TestMultiMMap
```

2023-12-05 09:31 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/store/DataOutput.java
> +  public void writeGroupVInts(long[] values, int limit) throws IOException {
I'm tempted to mark it `@lucene.experimental` to allow us to change the signature to use ints in the future. And likewise for its counterpart on `DataInput`?

2023-12-05 14:19 UTC, rmuir commented
> Thank you very much for your suggestions, i had fixed the comments from @jpountz, but the related to Mmapdir will be later(such as java19, java20 support), because we need to confirm whether to change it. i agree that we should be cautious here. in my understanding the optimized code is faster than the main branch probably because the optimized code doesn't need a `switch` statement in `GroupVIntUtil#readLongInGroup`, although it was inlined.
> 
> The JMH output for currently, it's similar to before we replaced `varHander` with `ByteBuffer#getInt()` java17
> 
> ```
> Benchmark                                                 (size)   Mode  Cnt   Score   Error   Units
> GroupVIntBenchmark.byteBuffersReadGroupVInt                   64  thrpt    5   4.698 ± 2.039  ops/us
> GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline           64  thrpt    5   2.167 ± 0.064  ops/us
> GroupVIntBenchmark.mmap_byteBufferReadGroupVInt               64  thrpt    5   7.386 ± 0.524  ops/us
> GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline       64  thrpt    5   7.358 ± 1.316  ops/us
> GroupVIntBenchmark.nioReadGroupVInt                           64  thrpt    5   8.236 ± 1.052  ops/us
> GroupVIntBenchmark.nioReadGroupVIntBaseline                   64  thrpt    5   5.381 ± 1.134  ops/us
> ```
> 
> java21
> 
> ```
> Benchmark                                                 (size)   Mode  Cnt   Score   Error   Units
> GroupVIntBenchmark.byteBuffersReadGroupVInt                   64  thrpt    5   4.622 ± 0.880  ops/us
> GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline           64  thrpt    5   1.674 ± 0.245  ops/us
> GroupVIntBenchmark.mmap_byteBufferReadGroupVInt               64  thrpt    5  10.165 ± 1.083  ops/us
> GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline       64  thrpt    5   5.104 ± 0.388  ops/us
> GroupVIntBenchmark.nioReadGroupVInt                           64  thrpt    5   9.527 ± 1.556  ops/us
> GroupVIntBenchmark.nioReadGroupVIntBaseline                   64  thrpt    5   5.351 ± 0.621  ops/us
> ```
> 
> @uschindler Thank you for take a look at this, here is the assembly output for `MemorySegmentIndexInput#readGroupVInt`, using command: `java -XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly --module-path lucene/benchmark-jmh/build/benchmarks --module org.apache.lucene.benchmark.jmh GroupVIntBenchmark.mmap`
> 
> assembly code

you need to install hsdis to be able to see instructions and not just binary data from printassembly. see https://github.com/apache/lucene/blob/main/help/jmh.txt

2023-12-05 16:06 UTC, easyice commented
Thank you @rmuir, the new assembly output is here:)   CC @uschindler 

https://github.com/easyice/lucene_files/blob/main/MemorySegmentIndexInput.readGroupVInt.asm.txt

2023-12-05 18:12 UTC, uschindler commented
Hi,
Did you create this one with the jmh option `-perfasm`? This looks like unoptimized code generated only by C1, not by the C2 compiler.

It would be good to have 2 asm dumps: one with your patch and one where the benchmark just calls the inherited default impl on Mmapdir.

2023-12-05 22:18 UTC, jpountz commented
@uschindler FYI this is what I'm getting: https://gist.github.com/jpountz/be81b1eb93c6118aac65c3679911f1d8. There are two files: baseline.txt for the default impl, and contender.txt for the optimized impl.

> In general I am not sure if we really need specialization in Mmapdir.
> We do not even implement readVInt for memory segments. Why should we implement it for this complex case?

To be clear, this specialization is not about doing the same kind of optimization that the JVM would do by inlining, it's about taking advantage of the fact that many of our Directory implementations can do unaligned random reads under the hood to decode group-varints more efficiently, fewer conditionals specifically.

2023-12-06 23:34 UTC, uschindler commented
The best idea that I have instead of VarHandles: Create an implementation for ByteBuffer (using the methods available there). This implementation would work with:
- byte arrays: Use ByteBuffer.wrap(), do stuff. Don't care about the instances, with Java 11+ the escape anaylsis will nuke the bytebuffers
- ByteBuffers - use as is
- MemorySegment: You can wrap a MemorySegent slice as ByteBuffer (like byte arrays). The MemorySegment code wraps just the portion as a single use byteBuffer, calls the generic method and throws it away. Also here: the temporary object is nuked by escape analysis

I would give that a try: It is easy and reuseable as we just use a ByteBuffer as a view on top of the small area.

P.S.: That escape analysis works you can see in our Panama Vector Util. Every vector multiplication creates around 20 objects....

2023-12-07 04:20 UTC, easyice commented
@uschindler Thanks for review!

> With unaligned random reads you mean that you read with positional reads from the area where the buffer is saved? With default DataInput you can only go forward, so you need to read everything and also in order.

The optimized decode for an integer value using `getInt(pos) & mask`,  it interprets the following bytes as intger, then use `mask` to remove unnecessary, since the length of each value is not fixed, the `getInt(pos)` will like `getInt(1); getInt(2); getInt(4); getInt(7)`, so it is unaligned random reads. This random access is not supported in `DataInput`, and possibility a bit heavy if use `RandomAccessInput` directly.

> The best idea that I have instead of VarHandles: Create an implementation for ByteBuffer

do you mean create an implementation to get the current block as `ByteBuffer` for `BufferedIndexInput` `ByteBuffersDataInput` and `MemorySegmentIndexInput` like "wrapSliceAsByteBuffer()" ? then put the decode function `readGroupVInt` to `DataInput`?

2023-12-07 08:00 UTC, uschindler commented
> > The best idea that I have instead of VarHandles: Create an implementation for ByteBuffer
> 
> do you mean create an implementation to get the current block as `ByteBuffer` for `BufferedIndexInput` `ByteBuffersDataInput` and `MemorySegmentIndexInput` like "wrapSliceAsByteBuffer()" ? then put the decode function `readGroupVInt` to `DataInput`?

My idea was to create a utility class with a static method that does the decoding on top of a ByteBuffer. This method takes a ByteBuffer and the same remaining parameters. To allow reuse of bytebuffers also add a startoffset where encoding starts.

In the several indexinputs just wrap a slice and call the static method. In ByteBufferIndexInput directly call the method. 

The only downside of this is that the caller code must know beforehand how large the slice must be.

2023-12-07 13:08 UTC, jpountz commented
> The only downside of this is that the caller code must know beforehand how large the slice must be.

I think that there is another downside, which is that this might not allow you to read 4 bytes for each integer. E.g. let's assume the simple case of 4 integers that are less than 256. The header byte is `0` in that case. So we know we need 4 bytes and can get a ByteBuffer of size 4. But then we'd like to `ByteBuffer#getInt()` at offsets 0, 1, 2 and 3 on that `ByteBuffer`, which can't be done for the last 3 integers since it has a size of 4?

Alternatively, could we read 17 bytes all the time and do something like below?

```java
try {
  ByteBuffer nextBytes = in.readByteBuffer(17);
  <decoding logic>
  in.seek(in.getPosition() - nextBytes().remaining()); // rewind unread bytes
} catch (EOFException e) {
  // naive impl
}
```

2023-12-07 18:35 UTC, uschindler commented
Lol. That's strange!

I would not have added a readNBytes method and just do the ByteBuffer wrapping in the readVInt method that calls the static method to decode.

If that's still slow we have to do a special case for mmap....

I will check tomorrow or at weekend.

2023-12-08 03:54 UTC, easyice commented
> Thank you for sharing the code, it seems very clear, another way, could we pass the current block(ByteBuffer) to the decode function like below? this will keep the remaining bytes checking in each indexinputs.
> 
> ```java
>   private void readGroupVInt(long[] dst, int offset) throws IOException {
>     if (buffer.remaining() < GroupVIntUtil.MAX_LENGTH_PER_GROUP) {
>       GroupVIntUtil.readGroupVInt(this, dst, offset);
>       return;
>     }
>     int pos = buffer.position();
>     int len = GroupVIntUtil.readGroupVIntFromByteBuffer(buffer, pos, dst, offset);
>     buffer.position(pos + len);
>   }
> ```

Thank you for quick  impl  Adrien, for reference, i tried this approach  [code link](https://github.com/easyice/lucene/commit/13851013e98ff8e27f05fa6dc4bc2e450ea6c03d#diff-c81a04bd13d225f3a2dc2c47bde9590686fe5bb0a197c99eeec1a35bf2cc04cc) ,it's no performance regression on `NIOFSDirectory` and  `ByteBuffersDataInput`, but  terrible performance on `MemorySegment`:

```
Benchmark                                                     (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline           64  thrpt    5  5.395 ± 0.228  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntUseByteBuffer      64  thrpt    5  1.394 ± 1.848  ops/us
```

2023-12-08 08:39 UTC, jpountz commented
I'll check if there is GC activity during the benchmark. In the meantime, I looked into using lambdas instead, and it seems like it would work well: https://github.com/apache/lucene/commit/8109e639508b6875d657e84634dd27c58942f610

```
Benchmark                                                (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt              64  thrpt    5  13.174 ± 0.870  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline      64  thrpt    5   6.834 ± 0.021  ops/us
```

2023-12-08 09:55 UTC, uschindler commented
I will nag Maurizio again about the problem with slice(). The reason for this was some strange problem with Hotspot. I thought they fixed it.

2023-12-08 10:12 UTC, easyice commented
> Can we do the same for all other inputs?

I think so, i will do this if @jpountz doesn't mind.

> I will nag Maurizio again about the problem with slice().

Thank you so much for pinpointing the cause of the problem!

2023-12-08 12:03 UTC, easyice commented
I'm running the performance differences between previous commit, it will take a moment.

2023-12-08 12:22 UTC, uschindler commented on lucene/test-framework/src/java/org/apache/lucene/tests/store/BaseDirectoryTestCase.java
> +    for (int i = 0; i < iterations; i++) {
I am a bit afraid that those tests kill my SSD at some point (also Jenkin's SSD). This creates files over and over. With test directories its not a problem, but with real FDDirectory ones we should reduce the iteration counts.

The chunked test should clearly setup a directory with a random chunk size once and run all tests on it. Ideally write only one file with multiple variants of groupVints behind each other (so it definitely crosses borders) and then read all of them.

2023-12-08 12:31 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +  public static interface IntReader {
add `@FunctionalInterface`

2023-12-08 12:32 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +   * @param dst the array to read ints into.
parameter "pos" is missing in javadocs

2023-12-08 12:34 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +              flag, p -> curSegment.get(LAYOUT_LE_INT, p), curPosition, dst, offset);
isn't the +1 missing here like above?

This is why I'd like to have a test that reads a vint group and other data from the same input placed behind each other!

2023-12-08 12:36 UTC, uschindler requested changes

2023-12-08 12:36 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +    final MemorySegment curSegment = this.curSegment;
This part MUST also be inside they try-catch, as it would throw NPE or IllegalStateException when the input was closed!

2023-12-08 12:40 UTC, easyice commented
It looks good on `byteBuffers` and `MMapDirectory`, the benchmark result is pretty close to previous commit,
but a bit slowdon on `NIOFSDirectory`, i will dig it.

* `*ReadGroupVInt` the current commit
* `*_viaDupCode` the previous commit, using duplicated code.
* `*Baseline` no change.

java17
```
Benchmark                                                   (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.byteBuffersReadGroupVInt                     64  thrpt    5  5.156 ± 0.378  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline             64  thrpt    5  2.130 ± 0.039  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVInt_viaDupCode          64  thrpt    5  5.455 ± 0.164  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt                 64  thrpt    5  7.632 ± 0.377  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline         64  thrpt    5  7.376 ± 0.485  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt_viaDupCode      64  thrpt    5  7.408 ± 0.532  ops/us
GroupVIntBenchmark.nioReadGroupVInt                             64  thrpt    5  6.905 ± 0.589  ops/us
GroupVIntBenchmark.nioReadGroupVIntBaseline                     64  thrpt    5  5.574 ± 0.216  ops/us
GroupVIntBenchmark.nioReadGroupVInt_viaDupCode                  64  thrpt    5  9.014 ± 0.162  ops/us
```

java21
```
Benchmark                                                   (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.byteBuffersReadGroupVInt                     64  thrpt    5   5.539 ± 0.220  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVIntBaseline             64  thrpt    5   1.825 ± 0.055  ops/us
GroupVIntBenchmark.byteBuffersReadGroupVInt_viaDupCode          64  thrpt    5   5.543 ± 0.097  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt                 64  thrpt    5   9.428 ± 0.189  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVIntBaseline         64  thrpt    5   5.565 ± 0.080  ops/us
GroupVIntBenchmark.mmap_byteBufferReadGroupVInt_viaDupCode      64  thrpt    5  10.476 ± 1.343  ops/us
GroupVIntBenchmark.nioReadGroupVInt                             64  thrpt    5   8.434 ± 1.887  ops/us
GroupVIntBenchmark.nioReadGroupVIntBaseline                     64  thrpt    5   5.431 ± 0.072  ops/us
GroupVIntBenchmark.nioReadGroupVInt_viaDupCode                  64  thrpt    5  10.723 ± 0.399  ops/us
```

2023-12-08 13:07 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +      throws IOException {
@uschindler should we also throws `NullPointerException`, `IllegalStateException` exception that maybe happen in `MemorySegmentIndexInput`?

2023-12-08 13:31 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +      throws IOException {
No. Why? It is an unchecked exception.

The NPE and ISE are mmap special case (also for the legacy mmap impl). Please only cover the whole method in memorysegment's input by the try-catch. If anywhere while the method is executed we get an NPE the input is closed. No need to do anything outside.

2023-12-08 13:33 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +      throws IOException {
See my other comment. Just extend the NPE/ISE try on the whole read method. Like everywhere else. Just look at the other methods, they are all identically structured. There is a reason why it is done like that. Don't change the pattern.

2023-12-08 13:34 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/GroupVIntUtil.java
> +      throws IOException {
All public methods in MemorySegmentIndexInput need the try catch. Everything private not.

2023-12-08 16:51 UTC, uschindler requested changes

2023-12-08 16:51 UTC, uschindler commented on lucene/core/src/test/org/apache/lucene/store/TestMMapDirectory.java
> +  private void doTestReadingClosedInput(Directory dir, long[] values, int numValues)
You don't need to test all variants and different sizes here. Just create an empty file with indexoutput. open it and close it, then call `readGroupVInts`. As this should only trigger the AlreadyClosedException theres no need to repeat this multiple times.
These are IO-heavy tests, so only do the required stuff and don't scrub my SSD. It also slows down those tests.

Just add it here and try to call that method on "two": 
- https://github.com/apache/lucene/blob/08d24dd9cb10b0808264b7c44e5b620d7d1a398e/lucene/test-framework/src/java/org/apache/lucene/tests/store/BaseChunkedDirectoryTestCase.java#L70-L74
- https://github.com/apache/lucene/blob/08d24dd9cb10b0808264b7c44e5b620d7d1a398e/lucene/test-framework/src/java/org/apache/lucene/tests/store/BaseChunkedDirectoryTestCase.java#L91-L95

Anyways, I don't think we need this test in reality. Otherwise we would need a call of all public methods.

2023-12-08 17:06 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +              flag, p -> curSegment.get(LAYOUT_LE_INT, p), curPosition, dst, offset);
Are you sure. It just reads the flag but does not increment.

2023-12-08 17:51 UTC, easyice commented on lucene/core/src/test/org/apache/lucene/store/TestMMapDirectory.java
> +  private void doTestReadingClosedInput(Directory dir, long[] values, int numValues)
Thank you @uschindler , It's more simpler, i like this!

2023-12-09 12:52 UTC, uschindler requested changes

2023-12-09 12:52 UTC, uschindler commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
I would rename all those benchmark methods to have better names including the exact implementation's class name. Remove internal details like ByteBuffer vs. something else, it should just like: `benchMMapDirectoryInputs`, `benchBufferedIndexInput`, `benchByteBuffersIndexInput`,...

2023-12-09 13:34 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/store/BufferedIndexInput.java
> +  @Override
>  if you like I can create a patch (and possbly also push it to your repository). 

Thanks @uschindler , Feel free to push patch if you like :)  or if you're busy i can try it too. i'm investigating why lambda has a bit regression on `NIOFSDirectory` today, but it seems no more can be optimize.

2023-12-09 14:42 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/store/BufferedIndexInput.java
> +  @Override
Maybe that goes away then. There shouldn't be a difference between byte buffers.

It could be caused my the long to int cast?

2023-12-09 14:50 UTC, uschindler commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
If we implement ByteBufferInput (without s) for java 17's mmap, we can detect this problem. I know the class is badly named and should me MappedByteBufferIndexInput.

I have some ideas, let me check this evening or tomorrow.

2023-12-09 14:51 UTC, uschindler commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
The reason why niofs may have problems more quickly is the case because the buffer size is quite small so it may more often fall back to the slow impl causing deoptimization on hotspot.

2023-12-09 16:14 UTC, easyice commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
Thank for you suggestions! the buffer size for both niofs and ByteBuffersDataInput(with s) should be 1024 in the case, and both did long to int cast, but ByteBuffersDataInput(with s) not become slow so much as niofs

* **niofs** ~18% slow than using duplicate code
* **ByteBuffersDataInput(with s)** ~7% slow than using duplicate code

I tried remove the long to int cast, and increase block size, nothing changed on jmh benchmark result. all cases have no GC activity. it's an interesting issue.

2023-12-09 16:34 UTC, easyice commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
> I would rename all those benchmark methods to have better names including the exact implementation's class name. 

How about benchmark methods names like the following?
```
benchMMapDirectoryInputs_readVInt 
benchMMapDirectoryInputs_readGroupVInt

benchNIOFSDirectoryInputs_readVInt 
benchNIOFSDirectoryInputs_readGroupVInt

benchByteBuffersIndexInput_readVInt 
...
```

2023-12-10 19:13 UTC, uschindler commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/GroupVIntBenchmark.java
> +  public void mmap_byteBufferReadVInt(Blackhole bh) throws IOException {
Looks fine.

2023-12-10 19:22 UTC, uschindler commented
Hi, I was busy this Sunday, sorry for delay. Will check tomorrow.

In general: My idea is to have a single static utility method (like the default one) in the util class that does the *whole* readGroupVInt, but that also (additionally) takes a lambda to random-access read the integer and also takes a parameter with the maximum size available in the context of the caller for random access reads with the lambda. MemorySegmentIndexInput would pass the segment.byteSize()-position, while ByteBuffers would pass remaining(). It would also take the reference offset of the *actual* position so it knows what to add for random-access reads). As return value it would return the new position. Both (reference position before the first block and return value) would be relative for usage by the lambda. The caller then just calls the method with the lambda (possibly wrapping the whole call with the usual NPE/ISE try-catch block).

This would allow an easy implementation by 3rd party directory implementations without knowing how readGroupVInt works internally. 3rd party implementations and our own MMap/NIO/... would just call this static method if they support random access or call super(), if they can't.

2023-12-11 03:41 UTC, easyice commented
> 3rd party implementations and our own MMap/NIO/... would just call this static method if they support random access or call super(), if they can't.

Thanks @uschindler , it's ok!, i'm going to do this today, and then you can take a look when you get a chance.

2023-12-11 11:10 UTC, uschindler reviewed
Hi, looks much better. I'd like to move the whole loop to the utility class.

2023-12-11 11:53 UTC, easyice commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
I am indeed worried about borders, now i understand your idea,  just consider current block, i will push a commit later.

2023-12-11 12:22 UTC, easyice commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
I think the loop of `readVInt()` needs to stay? because we needs update position of block before  `readVInt()` in different directory implementations.

2023-12-11 12:27 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
Hrrrm.... Thinking about that.

2023-12-11 12:28 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
Same for the byte header... Sorry forgot about this.

2023-12-11 12:43 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
For IndexInput subclasses, you can call setPosition(). So basically we won't even need the return value as the utility method can set the file pointer on its own. The static method would only need maximum available bytes to seek to and the IndexInput.

For native DataInputs that do not extend IndexInput, we can use the low level code, nobody outside would implement that on their own.

2023-12-11 12:46 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
You could also call `skipBytes()`.

2023-12-11 13:00 UTC, easyice commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
It seems can be work well, i will do it then re run benchmark. so we use `skipBytes` directly, regardless of whether the current instance is subclasses of `IndexInput`?

2023-12-11 13:04 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
oooooh, no better not on default. DataInput by default reads the bytes in a loop (e.g., when it is an InputStreamDataInput). But in that case the specialized method should never be used. Maybe add this to the documentation. We should add some hint in the Utility's class that the specialized method can only be used if and only if:
- input supports random access
- calling skipBytes only changes file pointer and does *NOT* read bytes (e.g., does not use the default impl).

Of course tests would fail.

2023-12-11 13:26 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
In fact it would still work with default `skipBytes()` that has a loop of `readByte()`, it would be just ineffective. But nobody would do this in a custom directory implementation!
So +1 to use skipBytes!

2023-12-11 14:00 UTC, uschindler commented on lucene/core/src/java21/org/apache/lucene/store/MemorySegmentIndexInput.java
> +      for (i = 0; i <= limit - 4; i += 4) {
> +1, we can make sure the static method caller have an efficient implementation of `skipBytes()`(base on `seek()`), Just i guess the `seek()` has an impact on performance, let me try..

Yes, if `skipBytes()` is not efficient (InputStream based DataInput), you can't use that specialized method anyways. IndecInput has an efficient default implementation, so no need to change anything. So we do not need to optimize anything.

Just call skipBytes() and test performance.

2023-12-11 16:26 UTC, easyice commented
The performance of the new approach seems regressed  a bit more on java21_benchMMapDirectoryInputs_readGroupVInt, here is the  difference of speed up relative to the baseline.


|        | task                                     | previous  commit | current      | diff   |
|--------|------------------------------------------|------------------|--------------|--------|
| java17 | benchByteBuffersIndexInput_readGroupVInt | 2.3x faster      | 2.1x faster  | -0.2x  |
| java17 | benchNIOFSDirectoryInputs_readGroupVInt  | 1.15x faster     | 1.09x faster | -0.06x |
| java21 | benchByteBuffersIndexInput_readGroupVInt | 2.7x faster      | 3.0x faster  | +0.3x  |
| java21 | benchNIOFSDirectoryInputs_readGroupVInt  | 1.75x faster     | 1.24x faster | -0.51x |
| java21 | benchMMapDirectoryInputs_readGroupVInt   | 1.74x faster     | 1.3x faster  | -0.44x |


Benchmark delta:

**Previous commit:**
java21

```
Benchmark                                                            (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  11.463 ± 0.371  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5   4.631 ± 0.970  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5   4.346 ± 1.094  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5   1.611 ± 0.408  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5   9.099 ± 1.438  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5   5.207 ± 0.646  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5   3.998 ± 0.667  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5   8.702 ± 0.513  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5   4.967 ± 0.319  ops/us
```

java17

```
Benchmark                                                            (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  10.309 ± 1.592  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5   4.236 ± 0.464  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5   4.755 ± 0.426  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5   2.012 ± 0.142  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5   7.233 ± 0.759  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5   7.471 ± 0.274  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5   3.854 ± 0.541  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5   6.399 ± 1.494  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5   5.557 ± 0.147  ops/us
```

**New approach:**
java17

```
Benchmark                                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  4.715 ± 3.024  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5  4.085 ± 0.352  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5  4.194 ± 2.129  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5  1.985 ± 0.594  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  6.946 ± 2.249  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  7.198 ± 1.596  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5  3.859 ± 0.345  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5  5.845 ± 1.214  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5  5.324 ± 0.470  ops/us
```

java21

```
Benchmark                                                            (size)   Mode  Cnt   Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  10.705 ± 1.000  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5   4.785 ± 0.986  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5   4.704 ± 1.458  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5   1.518 ± 0.428  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5   6.948 ± 3.155  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5   5.312 ± 0.223  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5   3.374 ± 2.154  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5   6.367 ± 1.217  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5   5.095 ± 0.544  ops/us
```

2023-12-11 17:07 UTC, uschindler commented
Hi, the problem of MMapDir is that the seek method has to update also the current block number.

Maybe we pass a second lambda to update the position? Let's just try this out!

2023-12-11 17:14 UTC, easyice commented
Thank you @uschindler , thinking about that too, i will try to a second lambda tomorrow.

2023-12-11 17:55 UTC, uschindler commented
Otherwise I like the new code very much.

In fact, this is a micro-benchmark. So the differences in speed won't be visible in query benchmarks.

2023-12-12 00:11 UTC, uschindler commented
Hi @easyice,
I have a better idea. Lets keep the 2 different method, but do another trick:
- The base class DataInput implements the public outer loop as a final implementation, subclasses won't override it: `public final void readGroupVInts(long[] dst, int limit) throws IOException`; this method does the outer loop and the tail readVInt(). There's nothing to optimize there anymore, so make that method final. The trick is now that this method calls inside the loop a `protected readGroupVInt()` method, where the default implementation of it is the one from the static helper class
- Subclasses like MemorySegment/ByteBuffer would just override the protected `readGroupVInt()` and possible provide their own implementation.

In short:
- make the outer loop a final public method thats called from client code
- make the previous private method to read a block protected and implement it in subclasses

This allows subclasses to just optimize by overriding the protected method and from there call the static helper method with the lambda. MemorySegment would also wrap with try...catch.

```java 
class DataInput.java:

  public final void readGroupVInts(long[] dst, int limit) throws IOException {
    int i;
    for (i = 0; i <= limit - 4; i += 4) {
      this.readGroupVInt(this, dst, i);
    }
    for (; i < limit; ++i) {
      dst[i] = readVInt();
    }
  }


  protected void readGroupVInt(long[] dst, int offset) throws IOException {
    GroupVIntUtil.readGroupVInt(this, dst, i);
  }


class MemorySegmentindexInput:

  @Override
  protected void readGroupVInt(long[] dst, int offset) throws IOException {
    try {
        curPosition +=
            GroupVIntUtil.readGroupVInt(
                this,
                this.curSegment.byteSize() - curPosition,
                p -> this.curSegment.get(LAYOUT_LE_INT, p),
                curPosition,
                dst,
                i);
    } catch (NullPointerException | IllegalStateException e) {
      throw alreadyClosed(e);
    }
  }
```

Do you get the idea?

2023-12-12 00:32 UTC, easyice commented
Thanks for the detailed description, got it! looks better :)

2023-12-12 05:19 UTC, easyice commented
> I have a better idea. Lets keep the 2 different method, but do another trick:

With this great idea, the performance comes back!

java21

```
Benchmark                                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  5.458 ± 0.405  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5  4.837 ± 0.502  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5  4.587 ± 0.304  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5  1.799 ± 0.084  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  9.815 ± 0.255  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  5.517 ± 0.230  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5  4.294 ± 0.060  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5  8.928 ± 0.313  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5  5.121 ± 0.328  ops/us
```

java17
```
Benchmark                                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchByteArrayDataInput_readGroupVInt                 64  thrpt    5  4.093 ± 2.429  ops/us
GroupVIntBenchmark.benchByteArrayDataInput_readVInt                      64  thrpt    5  3.530 ± 1.120  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5  3.648 ± 3.295  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5  1.644 ± 0.844  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  6.992 ± 1.110  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  7.188 ± 1.340  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5  3.690 ± 0.617  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5  5.587 ± 4.289  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5  5.283 ± 0.330  ops/us
```

2023-12-12 09:00 UTC, uschindler commented
> Could we consider not changing `MemorySegmentIndexInput` for java 19 and java20? As a preview feature , it seems reasonable that we only do optimizations in higher versions, and they are not Long-Term-Support (LTS) releases. but if you still feel we should to support them, i will do it.

Hi,
it is up to you, but at some point I will copy paster the code over, because I try to keep the 3 impls aligned to each other (I have some semi-automatic process) for updates. Java 22 is ongoing and will be merged soon. There is also the problem: It would be slower in Java 19 than in Java 18 or Java 17, if we also improve the `ByteBufferIndexInput` (without 's', see below).

So I would like you to just copypaste the one method to the other impl. It is tested by Jenkins automatically once we have it merged into main branch.

What is much more important: Please add the implementation for `ByteBufferIndexInput` (which is responsible for `MMapDirectory` before Java 18. Then you should see speedup with Java 17, too.

I am in generally not sure if this should be backported into the 9.x branch of Lucene unless we have performance tests for Java 11. In Java 11 the lambdas may be a problem and slowdown. So I would say: Let's do this only in main branch (Lucene 10.x).

2023-12-12 09:40 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/store/ByteBuffersIndexInput.java
> +  public void readGroupVInt(long[] docs, int limit) throws IOException {
this should be protected.

Why do we not have an improved implemenattion here? Last parameter should be "offset".

2023-12-12 09:52 UTC, easyice commented on lucene/core/src/java/org/apache/lucene/store/ByteBuffersIndexInput.java
> +  public void readGroupVInt(long[] docs, int limit) throws IOException {
Sorry for the missing change the parameter name and access modifiers!

2023-12-12 13:14 UTC, easyice commented
Hi, I added the implementation for `ByteBufferIndexInput`, Unfortunately, the benchmark shows a bit regression:


java17
```
Benchmark                                                          (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt              64  thrpt    5  6.591 ± 1.333  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline      64  thrpt    5  7.253 ± 0.443  ops/us
```


Probably that the `ix()` has a bit overhead, or capturing lambda problem like `NIOFSDirectory`?


DirectByteBuffer#getInt():

```java
    public short getShort(int i) {
        try {
            return getShort(ix(checkIndex(i, (1 << 1))));
        } finally {
            Reference.reachabilityFence(this);
        }
    }
```

I ran with `-XX:+PrintInlining` parameter, it shows the methods are fully inlined:

```
                     @ 139   org.apache.lucene.store.ByteBufferIndexInput$$Lambda$75/0x0000000800c84ca8::read (9 bytes)   inline (hot)
                                  @ 5   org.apache.lucene.store.ByteBufferIndexInput::lambda$readGroupVInt$0 (10 bytes)   inline (hot)
               !                    @ 6   java.nio.DirectByteBuffer::getInt (28 bytes)   inline (hot)
                                     \-> TypeProfile (30309/30309 counts) = java/nio/DirectByteBufferR
                                      @ 5   java.nio.Buffer::checkIndex (24 bytes)   inline (hot)
                                      @ 8   java.nio.DirectByteBuffer::ix (10 bytes)   inline (hot)
               !                      @ 11   java.nio.DirectByteBuffer::getInt (36 bytes)   inline (hot)
                                        @ 4   java.nio.Buffer::scope (17 bytes)   force inline by annotation
               !                        @ 13   jdk.internal.misc.ScopedMemoryAccess::getIntUnaligned (22 bytes)   force inline by annotation
               !                          @ 6   jdk.internal.misc.ScopedMemoryAccess::getIntUnalignedInternal (38 bytes)   force inline by annotation
                                            @ 17   jdk.internal.misc.Unsafe::getIntUnaligned (12 bytes)   inline (hot)
                                              @ 5   jdk.internal.misc.Unsafe::getIntUnaligned (83 bytes)   (intrinsic)
                                              @ 8   jdk.internal.misc.Unsafe::convEndian (16 bytes)   inline (hot)
                                            @ 23   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
                                        @ 21   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
                                      @ 16   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
```

2023-12-12 14:39 UTC, uschindler commented
There is no lambda capturing problem. I have no idea why it complains. It really looks like fully inlined. It seems that it is not happy about those ByteBuffers at all.

`ix()` is called all the time, that's hot.

2023-12-12 15:21 UTC, easyice commented
Even if i used the copy code approach(avoid to using lambda, for test purpose), it was only 15%-20% faster. 

like this:

```
  @Override
  public void readGroupVInts(long[] dst, int limit) throws IOException {
    int i;
    for (i = 0; i <= limit - 4; i += 4) {
      readGroupVInt(dst, i);
    }
    for (; i < limit; ++i) {
      dst[i] = readVInt();
    }
  }

  private void readGroupVInt(long[] dst, int offset) throws IOException {
    final ByteBuffer buffer = curBuf;
    if (buffer.remaining() < GroupVIntUtil.MAX_LENGTH_PER_GROUP) {
      GroupVIntUtil.readGroupVInt(this, dst, offset);
      return;
    }

    final int flag = readByte() & 0xFF;
    ...
    dst[offset] = guard.getInt(buffer, curPosition) & GroupVIntUtil.MASKS[n1Minus1];
    ...
    buffer.position(curPosition);
  }
```

copy code approach output:

```
Benchmark                                                          (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt              64  thrpt    5  8.991 ± 1.569  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline      64  thrpt    5  7.387 ± 0.268  ops/us
```

2023-12-12 15:23 UTC, uschindler commented
I have the feeling that for direct buffers (this is what MMap and NIO use, the getInt() seems more expensive than the sequential reads.

2023-12-12 15:25 UTC, uschindler commented
If you have an on-heap ByteBuffer (like for ByteBuffersIndexInput), it executes completely different code when reading from the underlying data structure..

2023-12-13 04:03 UTC, easyice commented
I agree with you, the getInt() seems more expensive than `MemorySegment`,  i prefer to revert the change on `ByteBufferIndexInput`, then the similar improve on java20, java19 (to keep the 3 impls aligned to each other)

2023-12-13 23:47 UTC, uschindler commented
> I agree with you, the getInt() seems more expensive than `MemorySegment`, i prefer to revert the change on `ByteBufferIndexInput`, then do the similar improve on java20, java19 (to keep the 3 impls aligned to each other), what do you think?
> 
> > for direct buffers (this is what MMap and NIO use
> 
> `NIOFSDirectory` seems using `HeapByteBuffer`? the `BufferedIndexInput.refill()->ByteBuffer.allocate()` will return a `HeapByteBuffer`.

I thought NIO works on the native bytebuffers used internally by NIOFSDir. As there is file access involved for optimal performance they should be direct. I can check this tomorrow, but I think there was some override in NioFsDir.

Sorry it is too late, but I am quite sure this is the main difference.

2023-12-13 23:57 UTC, uschindler commented
I checked: niofs indexinput still uses an on heap buffer. So I have no idea why it is slower for that case.

2023-12-14 00:02 UTC, uschindler commented
Let's keep ByteBufferIndexInput (without s) as is. Maybe work on that later. We would need to figure out what is causing slowness here.

So revert the change and copy paste code to MemorysegmentIndexInput.

My question: the coded 9.9 was already released, but as there is no index format change, we can just move the code away from the codec. But as this is now part of indexinput, we must be sure that the format and API is final.

I tend to think we should for now only merge this to main. Before backporting we should ensure that java 11 is not causing speed regression.

2023-12-14 04:19 UTC, easyice commented
> Let's keep ByteBufferIndexInput (without s) as is. Maybe work on that later. We would need to figure out what is causing slowness here.

Yes, it is very strange. I have spent some time investigating this but nothing found yet. I will continue to pay attention to this.


> I tend to think we should for now only merge this to main.

+1, I think backporting this PR to version 9.9 might not be necessary. any suggestions on this? @jpountz

2023-12-14 07:59 UTC, easyice commented
After copy paste code to `MemorysegmentIndexInput`, they work well:

java19:

```
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  9.050 ± 0.288  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  4.686 ± 0.099  ops/us
```

java20:

```
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  8.773 ± 4.910  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  4.408 ± 1.843  ops/us
```

2023-12-22 03:31 UTC, easyice commented
Hi @uschindler , can we merge this PR now?(without optimizing ByteBufferIndexInput) or anything else that needs to be changed?

2023-12-22 08:28 UTC, uschindler commented
Hi,
Yes we can. I was waiting for some comment from Adrien. Let me invite him for a review.
As this is main branch only, we can find-rube and change APIs later.
Uwe

2023-12-22 08:32 UTC, uschindler approved these changes

2023-12-22 15:45 UTC, jpountz approved these changes
Change looks good to me, thanks for running the micro benchmarks again.

I was thinking we'd backport this to 9.x, since this doesn't look like it would break anything. This would also help nightly benchmarks stay more in line with the stable branch. No strong feelings though, if @uschindler likes it better as a 10.0 only change, that's fine with me.

2023-12-22 16:23 UTC, uschindler commented
> Change looks good to me, thanks for running the micro benchmarks again.
> 
> I was thinking we'd backport this to 9.x, since this doesn't look like it would break anything. This would also help nightly benchmarks stay more in line with the stable branch. No strong feelings though, if @uschindler likes it better as a 10.0 only change, that's fine with me.

I think you're right. My problem was that the MMapDirectory changes regarding the ByteBufferIndexInput impl and NIOFSDir may be slower on 11. As we backed out those changes, I see no reason not to backport it. If somebody uses memory segments he she is already on java 19+.

I'd still like to check perf of the other changes on java 11 (ByteBuffers)!

Anyways, we should stop working on 9.x.

Uwe

2023-12-22 16:24 UTC, uschindler commented
I think, @mikemccand should have nightly benchmarks for both branches, the stable one and the main one.

2023-12-23 12:18 UTC, merged

2023-12-23 12:20 UTC, uschindler commented
I appied this for Lucene 10 only (main branch). This also fits changes.txt.

Let's figure out if backporting breaks anything. If this is fine in Lucene 9.x, we can move the changes entry. But for now I'd like to more thoroughly test this and see if Mike's production benchmark shows any changes.

2023-12-23 12:22 UTC, uschindler commented
I also merged the main barnch into the Java 22+ MMapDirectory implementation to make sure the MMAP tester finds any issues during its runs: https://jenkins.thetaphi.de/job/Lucene-MMAPv2-Linux/ and https://jenkins.thetaphi.de/job/Lucene-MMAPv2-Windows/

2023-12-26 14:17 UTC, easyice commented
There seems to be a speedup on [prefix queries](http://people.apache.org/~mikemccand/lucenebench/Prefix3.html) in nightly benchmarks.

For reference, here is the benchmark in branch_9x with this PR, the performance of `ByteBuffersIndexInput` looks better than java17,   `NIOFSDirectoryInputs` is similar than java17, but `MMapDirectoryInputs` has performance regression( we don't change the MMapDirectory impl)

java11:

```
Benchmark                                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5  5.064 ± 0.069  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5  1.612 ± 0.078  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  6.334 ± 0.914  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  7.362 ± 0.505  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5  4.885 ± 0.545  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5  2.977 ± 0.346  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5  2.660 ± 1.700  ops/us
```

I ran with `-XX:+PrintInlining` parameter in `benchMMapDirectoryInputs_readGroupVInt` task, the output is similar to java17
```
    702  799       3       org.apache.lucene.store.DataInput::readGroupVInts (41 bytes)   made not entrant
                              @ 12   org.apache.lucene.store.DataInput::readGroupVInt (7 bytes)   inline (hot)
                               \-> TypeProfile (26795/26795 counts) = org/apache/lucene/store/ByteBufferIndexInput$SingleBufferImpl
                                @ 3   org.apache.lucene.util.GroupVIntUtil::readGroupVInt (77 bytes)   inline (hot)
               !                  @ 1   org.apache.lucene.store.ByteBufferIndexInput::readByte (100 bytes)   inline (hot)
                                    @ 8   org.apache.lucene.store.ByteBufferGuard::getByte (9 bytes)   inline (hot)
                                      @ 1   org.apache.lucene.store.ByteBufferGuard::ensureValid (16 bytes)   inline (hot)
               !                      @ 5   java.nio.DirectByteBuffer::get (28 bytes)   inline (hot)
                                       \-> TypeProfile (13760/13760 counts) = java/nio/DirectByteBufferR
                                        @ 5   java.nio.Buffer::nextGetIndex (31 bytes)   inline (hot)
                                        @ 8   java.nio.DirectByteBuffer::ix (10 bytes)   inline (hot)
                                        @ 11   jdk.internal.misc.Unsafe::getByte (7 bytes)   force inline by annotation
                                          @ 3   jdk.internal.misc.Unsafe::getByte (0 bytes)   (intrinsic)
                                        @ 16   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
                                  @ 39   org.apache.lucene.util.GroupVIntUtil::readLongInGroup (81 bytes)   inline (hot)
               !                    @ 49   org.apache.lucene.store.ByteBufferIndexInput::readShort (25 bytes)   inline (hot)
                                      @ 8   org.apache.lucene.store.ByteBufferGuard::getShort (9 bytes)   inline (hot)
                                        @ 1   org.apache.lucene.store.ByteBufferGuard::ensureValid (16 bytes)   inline (hot)
               !                        @ 5   java.nio.DirectByteBuffer::getShort (27 bytes)   inline (hot)
                                         \-> TypeProfile (59062/59062 counts) = java/nio/DirectByteBufferR
                                          @ 4   java.nio.Buffer::nextGetIndex (38 bytes)   inline (hot)
                                          @ 7   java.nio.DirectByteBuffer::ix (10 bytes)   inline (hot)
               !                          @ 10   java.nio.DirectByteBuffer::getShort (32 bytes)   inline (hot)
                                            @ 9   jdk.internal.misc.Unsafe::getShortUnaligned (12 bytes)   inline (hot)
                                              @ 5   jdk.internal.misc.Unsafe::getShortUnaligned (33 bytes)   (intrinsic)
                                              @ 8   jdk.internal.misc.Unsafe::convEndian (16 bytes)   inline (hot)
                                            @ 17   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
                                          @ 15   java.lang.ref.Reference::reachabilityFence (1 bytes)   force inline by annotation
```

2023-12-26 16:16 UTC, uschindler commented
Hi,

Thanks for the measurements, @easyice. So basically, we can backport the commit without any modifications. I can do this and move change entries afterwards.

No PR is needed for that. It's easy.

Uwe

2023-12-28 12:59 UTC, uschindler commented
Hi @easyice, is my understanding correct. We can backport this PR as is?

2023-12-28 13:34 UTC, easyice commented
Thank you Uwe,  in my understanding we shouldn't backport this PR, because it has performance regression on java11 for `MMapDirectoryInputs` , this is also the main way of reading data. what do you think? CC @jpountz

2023-12-28 13:47 UTC, uschindler commented
> Thank you Uwe, in my understanding we shouldn't backport this PR, because it has performance regression on java11 for `MMapDirectoryInputs` , this is also the main way of reading data. what do you think? CC @jpountz

No it hasn't. We excluded MMapDirectory based on ByteBufferIndexInput in this PR. There is no change in ByteBufferIndexInput.

2023-12-28 13:48 UTC, uschindler commented
This PR only changes the Java 19-21 MMapIndput as we had a regression of ByteBufferIndexInput in Java 17 with ByteBufferIndexInput, too. So it was reverted. Just look at the code. With Java 17 (and therefore Java 11) there is no change in code.

2023-12-28 13:51 UTC, uschindler commented
If you have backported this PR and see a difference, it is a relic. Just raise number of repetitions.

2023-12-28 13:53 UTC, uschindler commented
As the naming of classes is causing issues all the time, I will open a PR and rename the badly named `ByteBufferIndexInput` used by MMapDirectory for Java 11-18 to `MappedByteBufferIndexInput`.

2023-12-28 13:59 UTC, easyice commented
Yeah, i backport this PR to branch_9x on my local machine, and run the benchmark with java11, i got performance regression  for `MMapDirectoryInputs`, even if we not change the code for `ByteBufferIndexInput` :(

java11
```
Benchmark                                                            (size)   Mode  Cnt  Score   Error   Units
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVInt              64  thrpt    5  5.064 ± 0.069  ops/us
GroupVIntBenchmark.benchByteBuffersIndexInput_readGroupVIntBaseline      64  thrpt    5  1.612 ± 0.078  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVInt                64  thrpt    5  6.334 ± 0.914  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readGroupVIntBaseline        64  thrpt    5  7.362 ± 0.505  ops/us
GroupVIntBenchmark.benchMMapDirectoryInputs_readVInt                     64  thrpt    5  4.885 ± 0.545  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVInt               64  thrpt    5  2.977 ± 0.346  ops/us
GroupVIntBenchmark.benchNIOFSDirectoryInputs_readGroupVIntBaseline       64  thrpt    5  2.660 ± 1.700  ops/us
```

2023-12-28 14:00 UTC, easyice commented
> As the naming of classes is causing issues all the time, I will open a PR and rename the badly named `ByteBufferIndexInput` used by MMapDirectory for Java 11-18 to `MappedByteBufferIndexInput`.

That's cool!

2023-12-28 14:03 UTC, easyice commented
> If you have backported this PR and see a difference, it is a relic. Just raise number of repetitions.

Ohhh... let me try again..

2023-12-28 14:10 UTC, uschindler commented
You see a relic. There is no slowdown. The baseline code is exactly the same like the one

The difference may come from different decisions by hotspot regarding inlining possibly because the benchmark runtime was too short. You won't the a difference in production. You are hunting ghosts.

I see no reason to not backport this code. In general, I don't think the whole code here will make a big difference in production, as seen by Mike's benchmark. This is the reason why I am not happy in moving the code complexity to the indexinputs at all.

So either backport it or revert it in total.

These are only microbenchmarks that don't have a large impact at all. If it is twice as fast you will see a difference, but not for the code here. In production the inline decisions by hotspot will be totally different. The benchmark code only runs in isolation.

2023-12-28 14:25 UTC, easyice commented
Thanks for explaining!  i agree that the micro benchmarks results are for reference only, so let we backport it :)

2023-12-29 12:16 UTC, uschindler commented
Hi @easyice,
I backported the PR. There was only a change in the test because in Java 11 does not have random() with two parameters. We have TestUtil for that.
Uwe

2023-12-29 12:28 UTC, easyice commented
Thank you for the backport and all great suggestions!

2024-01-11 13:33 UTC, jpountz commented
FYI I pushed an annotation to nightly benchmarks, it should show up tomorrow.