Fix DV update files referenced by merge will be deleted by concurrent flush
apache/lucene pull request #13017
Opened 2024-01-16 09:14 UTC by guojialiang92

### Description

This PR aims to address issue #13015.
A more detailed explanation of the issue and the reasoning behind the fix can be found in the report link above.

### Solution

- Before the file merge starts, execute `IndexFileDeleter#incRef` on the files referenced by merge to ensure that the file will not be deleted.
- After the file merge is completed/abort, execute `IndexFileDeleter#decRef`.
- In `ReadersAndUpdates#writeFieldUpdates`, `ReadersAndUpdates#swapNewReaderWithLatestLiveDocs` should be executed after `SegmentCommitInfo#setDocValuesUpdatesFiles`, ensuring that `SegmentReader` contains a deep clone of the `SegmentCommitInfo#dvUpdatesFiles`.

### Tests

- I introduced `MockAssertFileExistIndexInput` which validate file exists before reading it.
- I introduced `testForceMergeDVUpdateFileWithConcurrentFlush` which fails on `main` branch since the DV update file not exist, but passes on this branch.
- I added corresponding `testMergeDVUpdateFileOnGetReaderWithConcurrentFlush` which passes on both `main` and this branch. Because before merge, `IndexFileDeleter#incRef` is executed in `StandardDirectoryReader#open`.
- I added corresponding `testMergeDVUpdateFileOnCommitWithConcurrentFlush` which passes on both `main` and this branch. Because before merge, `IndexFileDeleter#incRef` is executed in `IndexWriter#prepareCommitInternal`.

### Checklist

- [x]  I have reviewed the guidelines for [How to Contribute](https://github.com/apache/lucene/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x]  I have given Lucene maintainers [access](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x]  I have developed this patch against the `main` branch.
- [x]  I have run `./gradlew check`.
- [x]  I have added tests for my changes.

2024-01-18 08:29 UTC, soren-xzk commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                    deleter.incRef(mr.reader.getSegmentInfo().files());
There is an assert judgment in incRef/decRef, which must have the IndexWriter's lock. There is no lock in this place, may there be a problem?

2024-01-18 11:44 UTC, guojialiang92 commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                    deleter.incRef(mr.reader.getSegmentInfo().files());
Hello, This PR has noticed that `IndexFileDeleter#incRef/IndexFileDeleter#decRef` needs to have the `IndexWriter` lock. I will explain in detail:

1. `IndexFileDeleter#incRef` is called in `IndexWriter#mergeMiddle`. it has been locked by `synchronized (this)` before the `IndexFileDeleter#incRef` is called.
2. Another call of `IndexFileDeleter#incRef` in `IndexWriter#preparePointInTimeMerge`. `IndexWriter#preparePointInTimeMerge` is called by `IndexWriter#prepareCommitInternal` or `IndexWriter#getReader`. `synchronized (this)` is performed in both `IndexWriter#prepareCommitInternal` and `IndexWriter#getReader`, so the `IndexFileDeleter#incRef` in  `IndexWriter#preparePointInTimeMerge` does not need to be locked.
3. `IndexFileDeleter#decRef` is called in `IndexWriter#closeMergeReaders`. `IndexWriter#closeMergeReaders` is a `synchronized` function.

2024-02-10 13:10 UTC, stefanvodita requested changes
Thank you for identifying and addressing this issue and sorry for the long wait in review.
I appreciate the thorough tests, I ran them too with and without the change and saw the same success/failure pattern you described.

To commit this, we need to add an entry to `CHANGES.txt`. The release process for 9.10 is starting on Monday. I don’t know if we would delay for this bug fix, so maybe it’s safer to aim for 9.11 - I think you would have to add a new section in `CHANGES.txt`.

2024-02-10 13:11 UTC, stefanvodita commented on lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java
> +      if (!Files.exists(filePath)) {
Nit: We try not to use `!` in the Lucene codebase because it's easy to miss. We can say `Files.exists(filePath) == false` instead.

2024-02-27 16:11 UTC, stefanvodita commented
Thanks! Could you also look at the CHANGES entry I had mentioned? We want to record the fix and credit you for the work.

2024-02-28 06:59 UTC, guojialiang92 commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> +                    mr -> {
Nice catch! I've adapted the code as suggested.

2024-02-28 07:02 UTC, guojialiang92 commented on lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java
> +      if (!Files.exists(filePath)) {
Sounds good! I have fix it.

2024-02-28 07:05 UTC, guojialiang92 commented on lucene/core/src/java/org/apache/lucene/index/ReadersAndUpdates.java
> +        || reader.getSegmentInfo().getDelGen() != pendingDeletes.info.getDelGen()) {
I found that when both `IndexWriter#updateDocument` and `IndexWriter#softUpdateDocument` exist, the new refCount control logic may delete the `.liv` file that no longer exists.

I have fixed this problem and added test cases, please code review, thank you!
@stefanvodita 

### Test
In order to reproduce and solve the problem, I introduced `testForceMergeWithPendingHardAndSoftDeleteFile`.

1. `IndexWriter#addDocument` doc1 = {"id": "1", "version": "1"}
2. `IndexWriter#commit`, which will produce segment0 = {_0.cfe, _0.cfs, _0.si}
3. `IndexWriter#addDocument` doc2 = {"id": "2", "version": "1"}
4. `IndexWriter#addDocument` doc3 = {"id": "3", "version": "1"}
5. `IndexWriter#addDocument` doc4 = {"id": "4", "version": "1"}
6. `IndexWriter#addDocument` doc5 = {"id": "5", "version": "1"}
7. `IndexWriter#commit`, which will produce segment1 = {_1.cfe, _1.cfs, _1.si}
8. `IndexWriter#updateDocument` updates doc2 to {"id": "2", "version": "2"}
9. `IndexWriter#commit`, which will produce segment2 = {_2.cfe, _2.cfs, _2.si}, and update segment1 to {_1.cfe, _1.cfs, _1.si, _1_1.liv}
10. `IndexWriter#updateDocument` updates doc3 to {"id": "3", "version": "2"}
11. `IndexWriter#softUpdateDocument` updates doc4 to {"id": "4", "version": "2"}
12. `DirectoryReader reader = IndexWriter#getReader(true, false)`, which will produce segment3 = {_3.cfe, _3.cfs, _3.si}, and update segment1 to {_1.cfe, _1.cfs, _1.si, _1_1.liv, _1_1.fnm, _1_1_Lucene80_0.dvd, _1_1_Lucene80_0.dvm}
13. `reader.close()`
14. `IndexWriter#commit`, update segment1 to {_1.cfe, _1.cfs, _1.si, _1_2.liv, _1_1.fnm, _1_1_Lucene80_0.dvd, _1_1_Lucene80_0.dvm}
15. `IndexWriter#forceMerge(1)`

### Analyze
**In step 12**
Because parameter `writeAllDeletes` of method `IndexWriter#getReader` has a value of `false`, `IndexWriter#writeReaderPool`, `ReaderPool#writeAllDocValuesUpdates`, and `ReadersAndUpdates#writeFieldUpdates` will be executed in sequence.

In method `ReadersAndUpdates#writeFieldUpdates`, since `ReadersAndUpdates#pendingDVUpdates` is not empty, `ReadersAndUpdates#swapNewReaderWithLatestLiveDocs` and `ReadersAndUpdates#createNewReaderWithLatestLiveDocs` will be executed in sequence.

`ReadersAndUpdates#createNewReaderWithLatestLiveDocs` will generate a new `SegmentReader` based on `pendingDeletes`. The new `SegmentReader` will hold the latest `liveDocs` and `numDocs`, but the value of `SegmentReader.si.delGen `will still be 1.

**In step 14**
_1_2.liv will be created, _1_1.liv will be deleted, and `pendingDeletes.info.delGen` will be updated to 2. 

**In step 15**
`ReadersAndUpdates#getReaderForMerge` will determine whether `SegmentReader` needs to be refreshed based on `pendingDeletes`. If `delGen` is not compared, `SegmentReader` will not be refreshed, and the refCount of _1_1.liv will still be +/- during the merge. When the refCount reaches 0, _1_1.liv will be deleted and `NoSuchFileException` will be thrown.

### Solution
In order to solve this problem, `ReadersAndUpdates#getReaderForMerge` is necessary to add comparison logic to `delGen`.
`SegmentReader` needs to be refreshed when `pendingDeletes.needsRefresh(reader) || reader.getSegmentInfo().getDelGen() != pendingDeletes.info.getDelGen()` returns `true`.

2024-02-28 07:33 UTC, guojialiang92 commented
> Thanks! Could you also look at the CHANGES entry I had mentioned? We want to record the fix and credit you for the work.

Thanks, I have add entry to CHANGES.txt.

2024-02-29 09:31 UTC, stefanvodita approved these changes
I think the change is good, but there's people who understand this code much better than I. I'll approve tentatively, but leave the PR up over the weekend to see if anyone else wants to have a look. Amazing work @guojialiang92!

2024-03-04 11:18 UTC, merged