Modernize BWC testing with parameterized tests
apache/lucene pull request #13046
Opened 2024-01-29 12:22 UTC by s1monw

After working on #12829 I was quite surprised about the complexity our BWC have and how ancient the appear compared to the rest of our test suite. I took a step back and tired to modernize the tests to leverage RandomizedRunner Parameterized Tests that allow us to have more structured and hopefully more extendible BWC tests in the future. This change doesn't add any new tests but tries to make the ones we have more structured and support growth down the road. 
Basically, every index type got it's own Test class that doesn't require to loop over all the indices in each test. Each test case is run with all versions specified. Several sanity checks are applied in the base class to make individual tests smaller and much easier to read.

2024-01-29 12:27 UTC, s1monw commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestDVUpdateBackwardsCompatibility.java
> +    // NOCOMMIT: why are we only testing one version here?
maybe somebody has an answer to that

2024-01-29 12:56 UTC, jpountz reviewed
I like the approach. I'm curious of @dweiss' opinion since he's more familiar with the testing framework.

2024-01-29 12:56 UTC, jpountz commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBinaryBackwardsCompatibility.java
> +    // don't this will fail since the indices are not supportd
```suggestion
    // don't this will fail since the indices are not supported
```

2024-01-29 12:56 UTC, jpountz commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestEmptyIndexBackwardsCompatibility.java
> +    // NOCOMMIT: why are we only testing one version here?
I would guess it's because it's more about testing the upgrade logic on empty indexes than about testing the format of old empty indexes.

2024-01-29 15:59 UTC, dweiss commented
I like it. Whenever there is test repetition that can be driven by data, it should be driven by data. 

The only downside to using ParametersFactory is that it's something that is implemented by the randomizedtesting framework (not JUnit itself) and people may be unfamiliar with it - perhaps a comment on the class (or the parameterized constructor) pointing at where the arguments come from would make it easier to grasp how this thing works?

Plain JUnit alternatives do exist but they rely on a different test runner (Parameterized) - you wouldn't be able to extend from LuceneTestCase anymore (and you'd be outside of the randomization context). I don't see any other, more elegant, solutions.

2024-01-29 16:02 UTC, dweiss commented
Oh, one more problem is that you can't "see" the structure of tests before you actually run them (in an IDE). Don't know how much of an issue this is in practice but it's impossible to solve with JUnit4. Some IDEs may also have problems repeating a particular test if its name contains parameters and their names. But I don't think we should think in terms of IDE support - the final outcome and benefit for maintainability matters more.

2024-01-29 16:51 UTC, mikemccand approved these changes
This looks great!  Thank you for modernizing our ancient BWC tests @s1monw.  I left minor comments.  For the `// nocommit` questions let's make followon issues to address?  We should PnP this!

2024-01-29 16:51 UTC, mikemccand commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestIndexUpgradeBackwardsCompatibility.java
> +  /** Randomizes the use of some of hte constructor variations */
`hte` -> `the`

2024-01-29 16:51 UTC, mikemccand commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestIndexUpgradeBackwardsCompatibility.java
> +    // NOCOMMIT we use to have single segment indices but we stopped creating them at some point
I don't know why we stopped!  We should start again?  But maybe as followon?

2024-01-30 09:44 UTC, s1monw commented
> We should PnP this!

What on earth means PnP? Mike, check out this search: https://www.google.com/search?q=pnp+acronym   wikipedia FTW

2024-01-30 11:05 UTC, uschindler requested changes
Looks fine to me. Theres only a forbiddenapis problem due to `String#formatted`.

Replace by `String.format(Locale.ROOT, indexPattern, version)`

2024-01-30 11:05 UTC, uschindler commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/BackwardsCompatibilityTestBase.java
> +    return indexPattern.formatted(version);
default locale...

2024-01-30 16:11 UTC, mikemccand commented
> > We should PnP this!
> 
> What on earth means PnP? Mike, check out this search: https://www.google.com/search?q=pnp+acronym wikipedia FTW

PnP = progress not perfection!  Not plug and play, not transistors, heh.

2024-01-30 17:08 UTC, s1monw commented
@uschindler I need to hear you speaking german to tell, you know that ;)

2024-01-30 17:45 UTC, uschindler commented
There is no formatted() with locale.

2024-01-30 17:48 UTC, uschindler requested changes

2024-01-30 17:48 UTC, uschindler commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/BackwardsCompatibilityTestBase.java
> +    return indexPattern.formatted(Locale.ROOT, version);
This method does not exist with locale. You just format the locale and the version number :-)

`String#formatted()` is looking nice but locale dependent bullshit. You may need to change the comment above, too.

2024-01-30 18:03 UTC, uschindler commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/BackwardsCompatibilityTestBase.java
> +    return indexPattern.formatted(Locale.ROOT, version);
This is the only correct variant: `String.format(Locale.ROOT, indexPattern, version)`

2024-01-30 18:08 UTC, uschindler commented on lucene/backward-codecs/src/test/org/apache/lucene/backward_index/BackwardsCompatibilityTestBase.java
> +    return indexPattern.formatted(Locale.ROOT, version);
See also: https://github.com/elastic/elasticsearch/pull/81603

2024-01-30 20:19 UTC, uschindler approved these changes
Looks fine. All nocommits are todos now.

I think it's ready for a first round. P💊P

P.S.: About the code style I would prefer the list of versions as a `Stream.of(...)` and converting them to those sets of versions using a stream mapping. Those array declarations look always strange.

2024-01-30 20:25 UTC, dweiss approved these changes

2024-01-31 14:27 UTC, merged

2024-01-31 14:28 UTC, s1monw commented
thanks everybody... I will go and backport this to 9.x as well

2024-02-09 16:30 UTC, HoustonPutman commented
So I just finished the 8.11.3 release, and had some problems with the back-compat testing code. Obviously the ant/gradle switch and jdk versions meant that I had to do a lot of it manually, but I'm pretty sure the regex matching in the `update_backcompat_tests()` function in `addBackcompatIndexes.py` was broken by this commit.

I updated the files myself manually for 8.11.3 (on main and 9x), and I think they are correct (and the tests pass), but I would recommend checking them and re-checking that the python script works with these changes...