BaseVectorSimilarityQueryTestCase assumes connected hnsw graph to
apache/lucene pull request #13260
Opened 2024-04-03 16:48 UTC by msokolov

…rityQueryTestCase

### Description

2024-04-03 16:56 UTC, uschindler requested changes

2024-04-03 17:07 UTC, msokolov commented on lucene/core/src/test/org/apache/lucene/search/BaseVectorSimilarityQueryTestCase.java
> +  private boolean graphIsDisconnected(IndexReader reader) throws IOException {
yeah, maybe we want to use in some other test class too. Ill refactor and pull out the field name

2024-04-03 17:53 UTC, benwtrent commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
Do we need to unwrap `FilterLeafReader`? I wonder if tests would randomly wrap the readers and this would fail the casting here. Since its a test, not that big of a deal as we would see the failure as a class cast exception.

I think assuming that all KnnVectorReaders implement `HnswGraphProvider` is OK for this utility as its specifically an HNSW utility.

2024-04-03 18:00 UTC, uschindler commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
We have Unwrappable#unwrap for that (under the assumption that FilterLeafReader implements that interface).

I added this to some classes, e.g
 It works with directories.

2024-04-03 18:51 UTC, shubhamvishu reviewed
Thanks @msokolov for fixing this!.....I left some comments

2024-04-03 18:51 UTC, shubhamvishu commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +  }
This function seems to be motivated from `FixedBitSet#nextSetBit` and would be more suitable for `FixedBitSet` class?....I wonder why it does not have it already.

2024-04-03 18:51 UTC, shubhamvishu commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +  public static List<Integer> componentSizes(HnswGraph hnsw) throws IOException {
It seems like the purpose of this function is to be a utility for future use cases(if any) because if we only need to know the graph is fully connected we could just pick a node and traverse only once to check if its size is equal to graph size i.e. early terminate instead of going through all components. Alternatively, I think we should keep `componentSizes` as-is but implement `isFullyConnected` like below?

```java
public static boolean isFullyConnected(HnswGraph hnsw) throws IOException {
    FixedBitSet connectedNodes = new FixedBitSet(hnsw.size());
    assert hnsw.size() == hnsw.getNodesOnLevel(0).size();
    System.out.println("size=" + hnsw.size());
    return connectedNodes.length() == traverseConnectedNodes(hnsw, connectedNodes);
  }
  ```

2024-04-03 19:31 UTC, msokolov commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +  }
Yes it could go there - it's a near clone of `FixedBitSet.nextSetBit` but I guess the motivation is to limit the surface area of supported functions. Perhaps if this gets wider use we could move it?

2024-04-03 19:39 UTC, msokolov commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
LeafReader doesn't seem to implement that unwrapping interface right now. Are you saying `ctx.reader()` might not be a `CodecReader`?

2024-04-03 19:48 UTC, benwtrent commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
The `ctx.reader()` might be a `FilterLeafReader` which isn't a `CodecReader`. I don't know if any of the tests actually wrap it or not.

So, I would do `FilterLeafReader.unwrap(ctx.reader())`.

`FilterLeafReader` doesn't implement `Unwrappable`.

2024-04-03 19:53 UTC, msokolov commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +  }
I guess one would also want to discourage its use in performance-sensitive code because it requires extra work beyond what `nextSetBit` does

2024-04-03 20:00 UTC, uschindler commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
Ok. So that's a job for future to implement this interface for all filter or wrappers. Originally this was added for MMapDirectory and some other class.

2024-04-03 20:01 UTC, msokolov commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
Oh, I see. You can call `Unwrappable.unwrapAll()` on anything it's just a no-op, duh. I suppose I can add that `implements Unwrappable`.

2024-04-03 20:02 UTC, uschindler commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
Actually it's not implemented yet for any subclass: https://github.com/search?q=repo%3Aapache%2Flucene%20unwrappable&type=code

2024-04-03 20:09 UTC, uschindler commented on lucene/test-framework/src/java/org/apache/lucene/tests/util/hnsw/HnswTestUtil.java
> +      }
Can you just add the interface to the FilterLeafReader? After that it confirms to the standard and You can use the static unwrapper.

2024-04-04 08:31 UTC, uschindler approved these changes

2024-04-04 08:32 UTC, uschindler commented
I think the Unwrappable for FilterReader should be added in a separate PR. For now this is fine.

I remember vaguely that I left our FilterReader because of the static method conflicting with the interface. This may be a good job for cleanup 10.x (remove static and just implement interface).

2024-04-04 12:31 UTC, merged

2024-04-04 12:31 UTC, msokolov commented
thanks for the reviews!

2024-04-04 13:07 UTC, msokolov commented
hm a failure popped up when I pushed:

```
org.apache.lucene.search.TestKnnByteVectorQuery > testTimeout FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at __randomizedtesting.SeedInfo.seed([AE2970724EFAD848:FE11FBC92B12FA54]:0)
 ```

I don't *think* it's related but I'll check

2024-04-04 13:22 UTC, benwtrent commented
@msokolov I have had something similar fail in other code, so it isn't related to your change here. I think its a flaky test. It doesn't reliably reproduce for me.