New JMH benchmark method - vdot8s that implement int8 dotProduct in C…
apache/lucene pull request #13572
Opened 2024-07-16 01:51 UTC by goankur

#### Credit: https://www.elastic.co/search-labs/blog/vector-similarity-computations-ludicrous-speed

Implement vectorized dot product in native C code using Neon intrinsics

### Description

`DO NOT MERGE`
Rough implementation created for discussion with Lucene community. 

`TODO:` Add more notes

2024-07-16 05:18 UTC, rmuir commented
Do we even need to use intrinsics? function is so simple that the compiler seems to do the right thing, e.g. use `SDOT` dot production instruction, given the correct flags:

https://godbolt.org/z/KG1dPnrqn

https://developer.arm.com/documentation/102651/a/What-are-dot-product-intructions-

2024-07-16 05:34 UTC, rmuir commented
I haven't benchmarked, just seems `SDOT` is the one to optimize for, and GCC can both recognize the code shape and autovectorize to it without hassle. 

my cheap 2021 phone has `asimddp` feature in /proc/cpuinfo, dot product support seems widespread.

You can use it directly via intrinsic, too, no need to use add/multiply intrinsic: https://arm-software.github.io/acle/neon_intrinsics/advsimd.html#dot-product

But unless it is really faster than what GCC does with simple C, no need.

2024-07-16 05:45 UTC, rmuir commented on lucene/core/build.gradle
> +          args << "-O3 --shared"
I think here is the problem, pass `-march` so it can use NEON/SVE dot product instructions for a more interesting comparison

2024-07-16 05:57 UTC, rmuir commented on lucene/core/build.gradle
> +          args << "-O3 --shared"
try something like `-O3 -march=armv8.4-a -funroll-loops` to test NEON. The documentation says that cortex/neoverse can do 4 of these in parallel, and GCC appears at a glance to unroll the SDOTs: https://godbolt.org/z/drbvW3TE1

2024-07-17 03:20 UTC, goankur commented on lucene/core/build.gradle
> +          args << "-O3 --shared"
Thanks for reviewing this @rmuir.

I tried `-O3 -march=armv8.2-a+dotprod` ([recommended flag per AWS graviton documentation](https://github.com/aws/aws-graviton-getting-started/blob/main/c-c++.md#enabling-arm-architecture-specific-features)) on my AWS `m6g.4xlarge` (Graviton2) instance type with ` GCC 10.5.0`  to compile the code snippet below but it always seems to give incorrect (0) result. I am trying to understand why `vdotq_s32` has no effect but currently hitting a wall.

```

int vdot8s(char vec1[], char vec2[], int limit) {
    int result = 0;
    int32x4_t accum = vdupq_n_s32(0);
    int i = 0;

    for (; i+16 <= limit; i+=16 ) {
        // Read into 8 (bit) x 16 (values) vector
        int8x16_t v1 = vld1q_s8((const int8_t*) (vec1 + i));
        int8x16_t v2 = vld1q_s8((const int8_t*) (vec2 + i));
        vdotq_s32(accum, v1, v2);
    }
    // REDUCE:  Add every vector element in target and write result to scalar
    result += vaddvq_s32(accum);
    // Scalar tail. TODO: Use FMA
    for (; i < limit; i++) {
        result += vec1[i] * vec2[i];
    }
    printf("Results: %d\n", result);
    return result;
}

```

2024-07-17 10:49 UTC, rmuir commented on lucene/core/build.gradle
> +          args << "-O3 --shared"
@goankur at a glance it seems you are ignoring return value from it. i think it should be `accum = vdotq_s32(accum, v1, v2)`

2024-07-18 02:24 UTC, goankur commented on lucene/core/build.gradle
> +          args << "-O3 --shared"
That was it, just needed a fresh pair of eyes.

2024-07-18 02:28 UTC, goankur commented
> Do we even need to use intrinsics? function is so simple that the compiler seems to do the right thing, e.g. use `SDOT` dot production instruction, given the correct flags:
> 
> https://godbolt.org/z/KG1dPnrqn
> 
> https://developer.arm.com/documentation/102651/a/What-are-dot-product-intructions-



> I haven't benchmarked, just seems `SDOT` is the one to optimize for, and GCC can both recognize the code shape and autovectorize to it without hassle.
> 
> my cheap 2021 phone has `asimddp` feature in /proc/cpuinfo, dot product support seems widespread.
> 
> You can use it directly via intrinsic, too, no need to use add/multiply intrinsic: https://arm-software.github.io/acle/neon_intrinsics/advsimd.html#dot-product
> 
> But unless it is really faster than what GCC does with simple C, no need.

With the updated compile flags, the performance of auto-vectorized code is slightly better than explicitly vectorized code (see results). Interesting thing to note is that both C-based implementations have `10X` better throughout compared to the Panama API based java implementation (unless I am not doing apples-to-apples comparison).

2024-07-18 02:58 UTC, rmuir commented
> With the updated compile flags, the performance of auto-vectorized code is slightly better than explicitly vectorized code (see results). Interesting thing to note is that both C-based implementations have `10X` better throughout compared to the Panama API based java implementation (unless I am not doing apples-to-apples comparison).

This seems correct to me. The java Vector API is not performant for the integer case. Hotspot doesn't much understand ARM at all and definitely doesn't even have instructions such as `SDOT` in its vocabulary at all.

2024-07-18 03:10 UTC, rmuir commented on lucene/core/build.gradle
> +               << "-march=armv8.2-a+dotprod"
for simple case of benchmarking i would just try `-march=native` to compile the best it can for the specific cpu/microarch. Then you could test your `dot8s` on ARM 256-bit SVE (graviton3, graviton4) which might be interesting...

2024-07-18 13:30 UTC, ChrisHegarty commented
> > With the updated compile flags, the performance of auto-vectorized code is slightly better than explicitly vectorized code (see results). Interesting thing to note is that both C-based implementations have `10X` better throughout compared to the Panama API based java implementation (unless I am not doing apples-to-apples comparison).
> 
> This seems correct to me.

Same. The performance benefit is large here. We do similar in Elasticsearch, and have impls for both AArch64 and x64. I remember @rmuir making a similar comment before about the auto-vectorization - which is correct. I avoided it at the time given the toolchain that we were using, but it's a good option which I'll reevaluate.

https://github.com/elastic/elasticsearch/blob/main/libs/simdvec/native/src/vec/c/aarch64/vec.c

> The java Vector API is not performant for the integer case. Hotspot doesn't much understand ARM at all and definitely doesn't even have instructions such as `SDOT` in its vocabulary at all.

++ Yes. This is not a good state of affairs. I'll make sure to get an issue filed with OpenJDK for it.

2024-07-18 13:35 UTC, ChrisHegarty commented
Could Lucene ever have this directly in one of its modules?  We currently use the `FlatVectorsScorer` to plugin the "native code optimized" alternative, when scoring Scalar Quantized vectors. But Lucene misses out on this by default, which is a pity.

2024-07-18 14:13 UTC, rmuir commented
> I avoided it at the time given the toolchain that we were using, but it's a good option which I'll reevaluate.

It should work well with any modern gcc (@goankur uses gcc 10 here). If using clang, I think you need to add some pragmas for it, that's all, see https://llvm.org/docs/Vectorizers.html and also there are some hints in the ARM docs.

One issue would be which to compile for/detect: 

IMO for arm there would be two good ones:
* armv8.2-a+dotprod (NEON)
* armv9-a (SVE)

For x86 probably at most three?:
* x86-64-v2 (AVX2)
* x86-64-v3 (AVX512)
* VNNI (should be tested but seems fit for the task? but not widespread? cascade-lake+?)

2024-07-18 14:34 UTC, rmuir commented
Here is my proposal visually: https://godbolt.org/z/a9T8YrroY

As you can see, by passing  `-march=cascadelake` it generates VNNI instructions.
IMO, no need for any intrinsics anywhere, for x86 nor ARM. Just a dead-simple C function and being smart about which targets we compile for.

(these variants should all be benchmarked of course first)

2024-07-18 15:04 UTC, rmuir commented
And i see from playing around with compiler versions, the advantage of intrinsics approach: although I worry how many variants we'd maintain. it would give stability across releasing lucene without worrying about change to underlying C compiler etc, no crazy aggressive compiler flags needed, etc.

But we should at least START with autovectorizer and look/benchmark various approaches it uses, such as VNNI one in the example above.

2024-07-18 15:13 UTC, rmuir commented
I definitely want to play around more with @goankur 's PR here and see what performance looks like across machines, but will be out of town for a bit.

There is a script to run the benchmarks across every aws instance type in parallel and gather the results: https://github.com/apache/lucene/tree/main/dev-tools/aws-jmh

I want to tweak https://github.com/apache/lucene/blob/main/dev-tools/aws-jmh/group_vars/all.yml to add the graviton4 (or any other new instance types since it was last touched) and also add c-compiler for testing this out, but we should be able to quickly iterate with it and make progress.

2024-07-19 09:29 UTC, ChrisHegarty commented
Just to expand a little on a previous comment I made above.

> Could Lucene ever have this directly in one of its modules? 

An alternative option to putting this in `core`, is to put it in say `misc`, allowing users creating `KnnVectorsFormat` to hook into it through the `Lucene99FlatVectorsFormat` and `FlatVectorsScorer`.  That way it would be somewhat optional in the build and distribution.

2024-07-19 12:22 UTC, msokolov commented
> An alternative option to putting this in core, is to put it in say misc, allowing users creating KnnVectorsFormat to hook into it through the Lucene99FlatVectorsFormat and FlatVectorsScorer. That way it would be somewhat optional in the build and distribution.

There are a few issues with distributing native-built methods that I can see. First, building becomes more complicated - you need a compiler, the build becomes more different on different platforms (can we support windows?), and when building you might have complex needs like targeting a different platform (or more platforms) than you are building on. Aside from building, there is the question of distributing the binaries and linking them into the runtime. I guess some command-line option is required in order to locate the .so (on linux) or .dll or whatever? And there can be environment-variable versions of this. So we would have to decide how much hand-holding to do. Finally we'd want to build the java code so it can fall back in a reasonable way when the native impl is not present. But none of this seems insurmountable. I believe Lucene previously had some native code libraries in its distribution and we could do so again.  I'm not sure about the core vs misc distinction, I'd be OK either way, although I expect we want to keep core "clean"?

2024-07-20 01:46 UTC, goankur commented on lucene/core/build.gradle
> +               << "-march=armv8.2-a+dotprod"
I tried `-march=native` on an `m7g.4xlarge` (Graviton3) instance type, OS, JDK, GCC were unchanged. `dot8s` and `vdot8s` are now `~3.5x` faster than java implementation, compared to being `10x` better on `m6g.4xlarge` (Graviton2)

Benchmark   |    (size)   | Mode | Cnt |  Score |  Error |  Units
---|---|---|---|---|---|---
VectorUtilBenchmark.binaryDotProductVector   |  768 | thrpt  |  15 | 10.570 | ± 0.003 | ops/us
VectorUtilBenchmark.dot8s          |            768  | thrpt  | 15 | 37.659  | ± 0.422 | ops/us
VectorUtilBenchmark.vdot8s         |            768  | thrpt  |  15 | 37.123 | ± 0.237  | ops/us

2024-07-20 02:10 UTC, rmuir commented on lucene/core/build.gradle
> +               << "-march=armv8.2-a+dotprod"
I think this happens because with the gcc10+sve, the implementation is not really unrolled. it should be possible to be 10x faster, too.

2024-07-20 02:14 UTC, goankur commented
> > > With the updated compile flags, the performance of auto-vectorized code is slightly better than explicitly vectorized code (see results). Interesting thing to note is that both C-based implementations have `10X` better throughout compared to the Panama API based java implementation (unless I am not doing apples-to-apples comparison).
> > 
> > 
> > This seems correct to me.
> 
> Same. The performance benefit is large here. We do similar in Elasticsearch, and have impls for both AArch64 and x64. I remember @rmuir making a similar comment before about the auto-vectorization - which is correct. I avoided it at the time given the toolchain that we were using, but it's a good option which I'll reevaluate.
> 
> https://github.com/elastic/elasticsearch/blob/main/libs/simdvec/native/src/vec/c/aarch64/vec.c
> 
> > The java Vector API is not performant for the integer case. Hotspot doesn't much understand ARM at all and definitely doesn't even have instructions such as `SDOT` in its vocabulary at all.
> 
> ++ Yes. This is not a good state of affairs. I'll make sure to get an issue filed with OpenJDK for it.

Thanks Chris. Please share the link to OpenJDK issue when you get a chance.

2024-07-20 02:22 UTC, rmuir commented on lucene/core/build.gradle
> +               << "-march=armv8.2-a+dotprod"
oh, the other likely explanation on the performance is that the integer dot product in java is not AS HORRIBLE on the 256-bit SVE as it is on the 128-bit neon. it more closely resembles the logic of how it behaves on AVX-256: two 8x8 bit integers ("64-bit vectors") are multiplied into intermediate 8x16-bit result (128-bit vector) and added to 8x32-bit (256-bit vector). Of course, it does not use SDOT instruction which is sad as it is CPU instruction intended precisely for this purpose.

On the 128-bit neon there is not a possibility with java's vector api to process 4x8 bit integers ("32-bit vectors") like the SDOT instruction does: https://developer.arm.com/documentation/102651/a/What-are-dot-product-intructions-
Nor is it even performant to take 64-bit vector and process "part 0" then "part 1". The situation is really sad, and the performance reflects that.

2024-07-20 02:52 UTC, goankur commented
> I definitely want to play around more with @goankur 's PR here and see what performance looks like across machines, but will be out of town for a bit.
> 
> There is a script to run the benchmarks across every aws instance type in parallel and gather the results: https://github.com/apache/lucene/tree/main/dev-tools/aws-jmh
> 
> I want to tweak https://github.com/apache/lucene/blob/main/dev-tools/aws-jmh/group_vars/all.yml to add the graviton4 (or any other new instance types since it was last touched) and also add c-compiler for testing this out, but we should be able to quickly iterate with it and make progress.

Let me try to squeeze some cycles out next week and see if I can make progress on this front.

2024-07-30 19:11 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> + */
I think we should remove the ifdef, this does not happen with `-march=native`, correct? The problem is only you try to "force" SVE? afaik, M3 doesnt support it and so `-march=native` should automatically take the neon path.

2024-07-30 19:13 UTC, rmuir commented on lucene/core/src/c/dotProduct.h
> +int32_t dot8s(int8_t* a, int8_t* b, int32_t limit);
can we fix these prototypes to all be the same? Can we include from the .c file? Maybe also dding `-Wall -Werror` will help keep the code tidy?

2024-07-30 19:20 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +int32_t vdot8s_sve(int8_t *vec1, int8_t *vec2, int32_t limit) {
purely cosmetic, but maybe change these all to array syntax, which will be easier for java developers, and transform pointer arithmetic such as `vec1 + i + 2 * vec_length` into `vec1[i + 2 * vec_length]`

2024-07-30 19:26 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +    // Scalar tail. TODO: Use FMA
I think you can remove TODO, since aarch64 "mul" is really "madd", i expect it already emits single instruction. look at assembler if you are curious.

2024-07-30 19:31 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +    }
maybe consider "vector tail", since 4 * vector length can be significant: and vector dimensions may not be exact multiple of that. It limits the worst case processing that "scalar tail" must do. Example from the java vector code: https://github.com/apache/lucene/blob/main/lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java#L153-L158

2024-08-01 01:04 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +    }
for any "tails" like this where we manually unroll and vectorize the main loop, we can add pragmas to prevent GCC/LLVM from trying to unroll and vectorize the tail. It is not strictly necessary but will lead to tighter code.

2024-08-01 01:07 UTC, rmuir commented
go @goankur, awesome progress here. It is clear we gotta do something :) I left comments just to try to help. Do you mind avoiding rebase for updates? I am going to take a stab at the x86 side of the house.

2024-08-01 01:12 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +    }
and maybe its just enough to disable autovectorization, as unrolling might still be a win for scalar tail: can't remember what hotspot is doing on the java vector code for this.

2024-08-01 01:26 UTC, rmuir commented on lucene/core/src/c/dotProduct.c
> +	// svptrue_b8() returns a predictae in which every element is true
With gcc autovectorization, i see use of SVE `whilelo` (predicate as counter) instead.  I think it basically works on loop counter, maybe look at autogenerated assembly with godbolt for inspiration? Sorry, I'm not well-versed in SVE but trying to help improve the performance as it would be important for Graviton3/Graviton4/etc. 

See also https://developer.arm.com/documentation/ddi0602/2024-06/SVE-Instructions/WHILELO--predicate-as-counter---While-incrementing-unsigned-scalar-lower-than-scalar--predicate-as-counter--

2024-08-01 03:00 UTC, rmuir commented
Attached is a patch to get x86 support working.

It makes some changes to the build: specifically the java code statically picks the best MethodHandle (SVE, Neon, Generic), and its able to compile Generic on any architecture/compiler (e.g. x86). I added necessary guards to the arm SVE/Neon code for this to work.

Changes were necessary to dodge performance traps with MethodHandle or use wrong compiler flags. But I think it makes the build more straightforward: it builds native as you expect,  if you want to use different compiler set `CC` env vars etc differently. 

Just with generic C code I see a good lift on avx-256 skylake:
```
Benchmark                                   (size)   Mode  Cnt   Score   Error   Units
VectorUtilBenchmark.binaryDotProductVector     768  thrpt   15  10.019 ± 0.080  ops/us
VectorUtilBenchmark.dot8s                      768  thrpt   15  17.492 ± 0.359  ops/us
```

Next step is to add x86 intrinsics  (e.g. VNNI) and try to max out the hardware.

[x86.patch.txt](https://github.com/user-attachments/files/16449392/x86.patch.txt)

2024-08-01 03:30 UTC, rmuir commented
TODO: need to examine avx256 difference of auto-vectorized C with vs java vector api for the integers here. This isn't nearly as bad as the ARM case (where we understand many of the underlying problems already), but I'm surprised to see such a lift, would be good to understand it.

2024-08-01 03:38 UTC, rmuir commented
also, would be good to compare apples-to-apples here. currently from what i see, benchmark compares `dot8s(MemorySegment..)` vs `BinaryDotProduct(byte[])`. To me this mixes up concerns about memorysegment vs java heap with C vs vector API, so it would be good to resolve for understanding purposes.

2024-08-01 05:26 UTC, goankur commented
Hey Robert — Apologies for the delay and thanks for iterating with me on this one. I will incorporate your feedback and update this PR by Aug 1st, 2024.

2024-08-02 01:28 UTC, goankur commented on lucene/core/src/c/dotProduct.h
> +int32_t dot8s(int8_t* a, int8_t* b, int32_t limit);
Prototypes fixed and `dotProduct.h` included in `dotProduct.c`. I did not add `-Wall -Werror` yet as after including changes from your patch the compilation of `dotProduct.c` file fails for me on Graviton boxes. Let's continue that discussion in the separate thread.

2024-08-02 01:29 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +int32_t vdot8s_sve(int8_t *vec1, int8_t *vec2, int32_t limit) {
Fixed.

2024-08-02 01:30 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +    // Scalar tail. TODO: Use FMA
This has been replaced with Vector tail as suggested in a later comment.

2024-08-02 01:55 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +    }
Converted scalar tail to vector and throughput score on Graviton3 dropped from `45.5` -> `44.2` which is a bit surprising. My guess is that auto-vectorized and unrolled code for scalar tail is more efficient than vector tail. Comparing scalar and vector tail in godbolt  - https://godbolt.org/z/sjo6KMnP7,  the `whilelo` instruction generated by auto-vectorization, stands out to me but I don't understand why that would cause a meaningful drop in performance. Let me try and dig a little deeper.

2024-08-02 02:07 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +    }
### Graviton 3 
```
Benchmark                                   (size)   Mode  Cnt   Score   Error   Units
VectorUtilBenchmark.binaryDotProductVector     768  thrpt   15  10.570 ± 0.002  ops/us
VectorUtilBenchmark.dot8s                      768  thrpt   15  44.562 ± 0.448  ops/us
```

2024-08-02 02:12 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +	// svptrue_b8() returns a predictae in which every element is true
Let me look into this tomorrow.

2024-08-02 02:47 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> + */
Simply having `-march=native` compiler flag and no `ifdef` directive makes clang (15.0) throw compilation error: 'SVE support not enabled', so guarding the SVE code with `ifdef` is necessary. That said there is no need for extra check on `__APPLE__` and I have removed that part from `ifdef`.

2024-08-02 03:01 UTC, goankur commented
> But I think it makes the build more straightforward: it builds native as you expect, if you want to use different compiler set `CC` env vars etc differently.

I still get compilation problems on Graviton 3 with these changes. I haven't tested on Graviton 2 but pretty sure that same issue will surface.

```
### Steps to reproduce on Graviton 3 box

$ wget https://github.com/user-attachments/files/16449392/x86.patch.txt .
$ git apply --include=lucene/core/build.gradle x86.patch.txt
$ git diff

 .... Shows the diff has been correctly applied to lucene/core/build.gradle
```

Compiling with `./gradlew :lucene:core:build` throws the error below

```
> Task :lucene:core:compileDotProductSharedLibraryDotProductC FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lucene:core:compileDotProductSharedLibraryDotProductC'.
> Error while evaluating property 'compilerVersion' of task ':lucene:core:compileDotProductSharedLibraryDotProductC'.
   > No tool chain is available to build for platform 'linux_aarch64':
       - Tool chain 'visualCpp' (Visual Studio):
           - Visual Studio is not available on this operating system.
       - Tool chain 'gcc' (GNU GCC):
           - Don't know how to build for platform 'linux_aarch64'.
       - Tool chain 'clang' (Clang):
           - Don't know how to build for platform 'linux_aarch64'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
```

2024-08-02 11:24 UTC, rmuir commented
That is the fault of your graviton setup though, you can see it right in your previous `platforms` logic where it is invoking `cCompiler.executable 'gcc10-cc'`.

Fix GCC to be in path correctly and things will work.

2024-08-03 02:41 UTC, goankur commented
> java --enable-native-access=ALL-UNNAMED \
>        --enable-preview \
>        -Djava.library.path="./lucene/core/build/libs/dotProduct/shared" \
>        -jar lucene/benchmark-jmh/build/benchmarks/lucene-benchmark-jmh-10.0.0-SNAPSHOT.jar \
>       regexp "(.*)?(binaryDotProductVector|dot8s)"



> That is the fault of your graviton setup though, you can see it right in your previous `platforms` logic where it is invoking `cCompiler.executable 'gcc10-cc'`.
> 
> Fix GCC to be in path correctly and things will work.

Ok, So I tried exporting the `CC` environment variable and cleared gradle's config cache by executing  `./gradlew clean` but the I still get the same compilation error:

```
...
Tool chain 'gcc' (GNU GCC):
           - Don't know how to build for platform 'linux_aarch64'.
 ...
```
Seems like `CC` environment variable is not being honored.

From [Gradle's documentation](https://docs.gradle.org/current/userguide/native_software.html#native_binaries:tool_chain) :

```
So for GCC running on linux, the supported target platforms are 'linux/x86' and 'linux/x86_64'. 
For GCC running on Windows via Cygwin, platforms 'windows/x86' and 'windows/x86_64' are supported. 
(The Cygwin POSIX runtime is not yet modelled as part of the platform, but will be in the future.)

If no target platforms are defined for a project, then all binaries are built to target a default platform
named 'current'. This default platform does not specify any architecture or operatingSystem value, 
hence using the default values of the first available tool chain.
```

I could be misinterpreting things but judging by the error, gradle's default toolchain pick - `gcc` does not know how to build for target platform - `linux_aarch64`. To fix this problem this the best I could do (also reflected in latest commit)

```
toolChains {
     gcc(Gcc) {
          target("linux_aarch64") {
              cCompiler.executable = System.getenv("CC")
          }
      }
     clang(Clang) {
         target("osx_aarch64"){
             cCompiler.executable = System.getenv("CC")
         }
     }
 }
```

2024-08-03 03:02 UTC, goankur commented
@rmuir  - I am going to be out for the next week so please feel free to play with it and further refine the code.  

- Once we get some performance numbers from adding `x86 intrinsics`, I think, the next step would be to test the impact on HNSW searching/indexing with `int8` quantized vectors. 
- Assuming things look promising, we will need community feedback on native code acceptance.
- If there is appetite to having it within Lucene (core/native/misc) then we will need tests + documentation + cleanup before this can be merged .

2024-08-14 19:48 UTC, rmuir commented
sorry @goankur i'm super-behind, vacations and end of summer. i definitely want to try out the VNNI path but just haven't found the cycles yet.

2024-08-17 00:43 UTC, goankur commented
> also, would be good to compare apples-to-apples here. currently from what i see, benchmark compares `dot8s(MemorySegment..)` vs `BinaryDotProduct(byte[])`. To me this mixes up concerns about memorysegment vs java heap with C vs vector API, so it would be good to resolve for understanding purposes.

As I understand, here is the call stack 

`PanamaVectorUtilSupport.dotProduct(MemorySegment, MemorySegment)`
`PanamaVectorUtilSupport.dotProduct(byte[], byte[])`
`VectorUtil.dotProduct(byte[], byte[])`
`VectorUtilBenchmark.binaryDotProductVector()` 

So heap allocated `byte[]` gets wrapped into MemorySegment before the dotProduct computation that uses Panama APIs.

For strict apples-to-apples comparison, one would wrap the heap-allocated `byte[]` into a MemorySegment and pass it to the native code -- `dot8s(MemorySegment..)` -- but this does not work and throws the following exception

```
Caused by: java.lang.IllegalArgumentException: Heap segment not allowed: MemorySegment{ heapBase: Optional[[B@53a133c5] address:0 limit: 768 }
        at java.base/jdk.internal.foreign.abi.SharedUtils.unboxSegment(SharedUtils.java:331)
        at org.apache.lucene.util.VectorUtil.dot8s(VectorUtil.java:217)
        ... 13 more

```

So I can't think of a good way to make the comparison fairer. Do you have any recommendations ?

2024-08-17 00:54 UTC, goankur commented on lucene/core/src/c/dotProduct.c
> +	// svptrue_b8() returns a predictae in which every element is true
@rmuir  -- I tried using `svwhilelt_b8_u32(i, limit)` intrinsic for generating the predicate in both the unrolled-loop and vector tail but the performance was actually worse :-(.  

To give you an idea of what I did, here is link to the ARM documentation with code sample

https://developer.arm.com/documentation/102699/0100/Optimizing-with-intrinsics

2024-09-05 15:14 UTC, mikemccand commented
> Could Lucene ever have this directly in one of its modules? We currently use the `FlatVectorsScorer` to plugin the "native code optimized" alternative, when scoring Scalar Quantized vectors. But Lucene misses out on this by default, which is a pity.

+1, it's horrible that Lucene cannot offer such performance gains.  We are still bottlenecked by the java vector API limitations ...

I like the idea of adding native code options under `lucene/misc` module?  And if `FlatVectorScorer` is easily swapped to the native optimized version, via custom `Codec` with examples in `misc`, that seems like a viable path forward?  It would still not be Lucene's default `Codec`, but it would at least be an option for users?

2024-09-05 15:16 UTC, mikemccand commented
> It makes some changes to the build: specifically the java code statically picks the best MethodHandle (SVE, Neon, Generic), and its able to compile Generic on any architecture/compiler (e.g. x86). I added necessary guards to the arm SVE/Neon code for this to work.

Whoa, this is cool!  So with @rmuir's patch we have the necessary switching at run-time (one time static check) to pick the right native (compiled C code relying on good gcc auto-vectorization) implementation of `dotProduct`, falling back to a generic one if none of the specialized ones apply.

2024-09-05 15:18 UTC, mikemccand commented
> There is a script to run the benchmarks across every aws instance type in parallel and gather the results: https://github.com/apache/lucene/tree/main/dev-tools/aws-jmh

Holy smokes this is a cool benchy tool!  Imagine if Lucene's nightly benchy could use this to run on all hardware... we'd be able to catch hardware/environment specific odd Lucene regressions.

2024-09-05 15:31 UTC, mikemccand commented
> Once we get some performance numbers from adding x86 intrinsics, I think, the next step would be to test the impact on HNSW searching/indexing with int8 quantized vectors.

Can we test on `int7`?

`int8` is unfortunately [currently broken](https://github.com/apache/lucene/issues/13519), and likely we should remove it as an option for 10.0.0, and later add it back if/when we can get the complicated math (see discussion on that issue) ironed out.

2024-09-05 15:54 UTC, mikemccand commented
I'm trying to understand the status of this PR... so far it's a standalone JMH benchy that shows that using [FFM](https://openjdk.org/jeps/454) to invoke our own native C implementation of `dotProduct` on ints (e.g. needed for `int7`, `int4` HNSW scalar quantization in Lucene) that's carefully optimized to use the right SIMD instructions (switching depending on the capabilities of the CPU) shows sizable speedups (up to 10X) over our current "pure java" Panama vector API implementation?

This is a micro-benchmark of just `dotProduct`, so the overall gains to Lucene's HNSW indexing and searching will be less than 10X.  But, `dotProduct` is [very much the hotspot of Lucene's HNSW](https://github.com/mikemccand/luceneutil/issues/256#issuecomment-2159000055) indexing and searching, so the end gains will likely be significant, especially on CPUs that perform poorly today via Panama (e.g. ARM).

To make this actually accessible to users I think we would still need to:

  * Add this `nativeDotProduct` somewhere, likely `lucene/misc` module, and get gradle to compile it all
  * Make an alternative `NativeFlatVectorScorer` (in `misc`) that uses the `nativeDotProduct`
  * Make a `NativeLucene99HnswVectorsFormat` that is just like the default for `core` (`Lucene99HnswVectorsFormat` now), but it invokes `NativeFlatVectorScorer` instead.  Hopefully this can be done without too much code duplication.
  * Show examples of how one could use Lucene's default `Codec` but swap in this `NativeLucene99HnswVectorsFormat` for KNN fields

I think this all can be done after 10.0 -- there's no particular reason why we need a major release to add this?  It's entirely new (optimized) added feature.

2024-09-06 01:44 UTC, goankur commented
> I'm trying to understand the status of this PR... so far it's a standalone JMH benchy that shows that using [FFM](https://openjdk.org/jeps/454) to invoke our own native C implementation of `dotProduct` on ints (e.g. needed for `int7`, `int4` HNSW scalar quantization in Lucene) that's carefully optimized to use the right SIMD instructions (switching depending on the capabilities of the CPU) shows sizable speedups (up to 10X) over our current "pure java" Panama vector API implementation?

That is the correct assessment. `10X` throughput gains on AWS Graviton 2 and roughly `4.3x` throughput gain on AWS Graviton 3 with the native code as demonstrated by JMH benchmarks. 

One small wrinkle that makes this comparison less than apples-to-apples is the Panama API based `dotProduct` implementation wraps heap allocated `byte[]` with `MemorySegment` whereas the native C code allocates byte arrays **off-heap** and wraps them with `MemorySegment` before invoking `dotProduct` method. 

Invoking native C code with `MemorySegment` backing **on-heap** byte arrays throws the error below which I am not sure how to resolve.

```
Caused by: java.lang.IllegalArgumentException: Heap segment not allowed: MemorySegment{ heapBase: Optional[[B@53a133c5] address:0 limit: 768 }
        at java.base/jdk.internal.foreign.abi.SharedUtils.unboxSegment(SharedUtils.java:331)
        at org.apache.lucene.util.VectorUtil.dot8s(VectorUtil.java:217)
        ... 13 more

```

> This is a micro-benchmark of just `dotProduct`, so the overall gains to Lucene's HNSW indexing and searching will be less than 10X. But, `dotProduct` is [very much the hotspot of Lucene's HNSW](https://github.com/mikemccand/luceneutil/issues/256#issuecomment-2159000055) indexing and searching, so the end gains will likely be significant, especially on CPUs that perform poorly today via Panama (e.g. ARM).

Yes, I agree and next step, as I see, would be to integrate it with vector scoring component and measure performance using [knnPerfTest.py](https://github.com/mikemccand/luceneutil/blob/main/src/python/knnPerfTest.py)


> To make this actually accessible to users I think we would still need to:
> 
> * Add this `nativeDotProduct` somewhere, likely `lucene/misc` module, and get gradle to compile it all
> * Make an alternative `NativeFlatVectorScorer` (in `misc`) that uses the `nativeDotProduct`
> * Make a `NativeLucene99HnswVectorsFormat` that is just like the default for `core` (`Lucene99HnswVectorsFormat` now), but it invokes `NativeFlatVectorScorer` instead.  Hopefully this can be done without too much code duplication.
> * Show examples of how one could use Lucene's default `Codec` but swap in this `NativeLucene99HnswVectorsFormat` for KNN fields
> 
> I think this all can be done after 10.0 -- there's no particular reason why we need a major release to add this? It's entirely new (optimized) added feature.

Sounds good! Thanks for the suggestions on next step @mikemccand.

2024-09-06 10:58 UTC, uschindler commented
Hi the whole setup of the calls to native code are not correct. In Lucene we don't use or need "--enable-preview", because we have a special way to compile the code ("you added it marked as "hacky"). In fact, the Java code must be placed in the `src/java21` folder which gets a special compilation (using apijar) files that also ensure it works with Java 22 and later.

So basically the code would need to be added to the VectorizationProvider.

Anyways: At moment we do not want to have native code in Lucene Core.

2024-09-06 11:01 UTC, uschindler requested changes
See previous comment.

2024-09-11 13:12 UTC, mikemccand commented
> Anyways: At moment we do not want to have native code in Lucene Core.

+1, we don't put native code in Lucene's `core`.

But @uschindler is there maybe a way forward not using core?  I.e. add native code to `misc` or `sandbox` or so, to enable iterating on direct access to SIMD for early adopters (opt in)?

Or is the `src/javaXX` approach core-only for some reason?

Having the likes of OpenSearch, Elasticsearch, and Solr implement their own (high performance) direct native SIMD access seems not ideal to me.  It really should somehow be an option in Lucene, even if it's not the default.

This would be our "Plan C" (["Plan B" was the previous workaround of gaining early access to SIMD via Panama](https://github.com/apache/lucene/issues/12302), but even that is bottlenecking us too much now).

2024-09-13 16:59 UTC, ChrisHegarty commented
> > Anyways: At moment we do not want to have native code in Lucene Core.
> ..
> Having the likes of OpenSearch, Elasticsearch, and Solr implement their own (high performance) direct native SIMD access seems not ideal to me. It really should somehow be an option in Lucene, even if it's not the default.

As someone who wrote and maintains the native scorer in Elasticsearch, it gives great speed ups for Scalar Quantised vectors on ARM. Since Panama Vector is horrible for arithmetic operations on byte-sized values; both widen and accessing various parts of the vector. We have an AVX implementation too, but it gives less improvements. I don't see Panama Vector improving in this area any time soon :-(.  For floats we don't do any native.

In the latest Binary Quantization https://github.com/apache/lucene/pull/13651, Panama Vector performs very nicely.  It might be that some of the motivation for a native scorer may just go away.

2024-09-14 07:17 UTC, uschindler commented on gradle/java/javac.gradle
> +      options.compilerArgs += ["--release", rootProject.minJavaVersion.toString(), "--enable-preview"]
No need for this when everything is moved to java21 folder

2024-09-14 07:57 UTC, uschindler commented
> > Anyways: At moment we do not want to have native code in Lucene Core.
> 
> +1, we don't put native code in Lucene's `core`.
> 
> But @uschindler is there maybe a way forward not using core? I.e. add native code to `misc` or `sandbox` or so, to enable iterating on direct access to SIMD for early adopters (opt in)?
> 
> Or is the `src/javaXX` approach core-only for some reason?

In the current setup it is. One could generalize this, but this should be fine step by step in separate PRs. There are several problems to solve, also with regards to modularization and where the stub jars are:

- compilation stubs (apijars) need to move to a common folder across Gradle projects (we don't have dich common module yet as core itself has no dependencies).
- the bootstrapping of Panama and memory segment code is based on factories which are not yet pluggable. This may need SPI. So one could simply drop a separate JAR into class path/module path and then it enabled native code.
- I would like to prevent duplicate and hairy initialization code, so one single place that loads the service providers and fies appropriate checks before.

In general it's doable but I really doubt if this is healthy for this project's infrastructure.

So I am still -1 to Gabe native code before we have refactored major parts. One condition is to have java 22 as minimum version, so we can at least introduce MemorySegment as top level citizen into our own APIs. I was arguing in the java community to have the foreign API stabilized and released with 21, but unfortunately it was done in 22. If we can get rid of the shit and simply tell our downstream users to accept java 22 as minimum version, and only the Panama vector stuff needs to be me jarred it would simplify a lot.

Uwe

2024-10-23 19:07 UTC, msokolov reviewed
I took a look. I have to say I'm still kind of confused about why we sometimes get these vector scorers via scorersupplier and other times get them from static create() methods and I worry about the resource usage - it's difficult to reason about by staring at code, so I think we need to run some tests to be more confident

2024-10-23 19:07 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentScalarQuantizedVectorScorer.java
> +/*
can you say where this file came from? Was it mostly copied from some other file, or is it all brand new?

2024-10-24 11:28 UTC, mikemccand commented on lucene/native/src/c/dotProduct.c
> +int32_t vdot8s_sve(int8_t vec1[], int8_t vec2[], int32_t limit) {
Earlier @rmuir had suggested just relying on `gcc` to compile the "obvious" C code down to efficient vectorized implementation, but here it looks like we are still hand rolling the NEON asm intrinsics?  Was the `gcc` path less performant?

2024-10-24 11:29 UTC, mikemccand commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentScalarQuantizedVectorScorer.java
> +/*
Duplicate copyright header.

2024-10-24 12:05 UTC, mikemccand commented
@goankur -- thank you for pulling out the actual native code into a new `native` Lucene module.  I'm not sure we need a new module -- could we use `misc` or `sandbox` maybe?

I have not looked so closely at the PR, just left a few minor comments so far, but ... how come there are so many changes necessary in `core`?  It looks like a lot of hard forking of existing sources to specialize specific cases (memory segment, byte quentization, ???).  I had expected (from the view from 10000 feet) the PR to be nearly entirely outside of `core`.

2024-10-24 16:49 UTC, yugushihuang commented
We have measured performance using [knnPerfTest.py](https://github.com/mikemccand/luceneutil/blob/main/src/python/knnPerfTest.py) in lucene util with this PR [commit](https://github.com/goankur/lucene/commit/85d78116f87b679078a80cf606cd4bc7219ee793) as candidate branch. 
### cmd
```
'/usr/lib/jvm/java-21-amazon-corretto/bin/java', '-cp', [...], '--add-modules', 'jdk.incubator.vector', '-Djava.library.path=/home/[user_name]/lucene_candidate/lucene/native/build/libs/dotProduct/shared', 'knn.KnnGraphTester', '-quantize', '-ndoc', '1500000', '-maxConn', '32', '-beamWidthIndex', '50', '-fanout', '6', '-quantizeBits', '7', '-numMergeWorker', '12', '-numMergeThread', '4', '-encoding', 'float32', '-topK', '10', '-dim', '768', '-docs', 'enwiki-20120502-lines-1k-mpnet.vec', '-reindex', '-search-and-stats', 'enwiki-20120502-mpnet.vec', '-forceMerge', '-quiet'
```
### Lucene_Baseline
```
Graph level=3 size=46, connectedness=1.00
Graph level=2 size=1405, connectedness=1.00
Graph level=1 size=46174, connectedness=1.00
Graph level=0 size=1500000, connectedness=1.00

Results:
recall  latency (ms)     nDoc  topK  fanout  maxConn  beamWidth  quantized  index s  force merge s  num segments  index size (MB)
 0.332         0.333  1500000    10       6       32         50     7 bits   432.69         271.51             1          5558.90
```
### Lucene_Candidate
```
Graph level=3 size=46, connectedness=1.00
Graph level=2 size=1410, connectedness=1.00
Graph level=1 size=46205, connectedness=1.00
Graph level=0 size=1500000, connectedness=1.00

Results:
recall  latency (ms)     nDoc  topK  fanout  maxConn  beamWidth  quantized  index s  force merge s  num segments  index size (MB)
 0.337         0.260  1500000    10       6       32         50     7 bits   441.25         293.41             1          5558.91
```

The latency has dropped from 0.333ms to 0.26ms.

2024-10-24 17:59 UTC, msokolov commented
nice improvement! I do see the index time increased and  wonder if it is due to creating too many heavyweight RandomVectorScorers. Maybe we can make this easier by simplifying the whole RandomVectorScorer creation pathway. Although that is out of scope here, it might be good to try and work around it if possible as I suggested above

2024-10-25 19:31 UTC, goankur commented on lucene/core/src/java/org/apache/lucene/codecs/lucene99/OffHeapQuantizedByteVectorValues.java
> +    lastOrd = targetOrd;
Got it!. I will remove this in the next revision. I was just trying to optimize for the case when `getScoreCorrectionConstant(int targetOrd)` gets invoked with the same `targetOrd` multiple times in succession.

2024-10-25 21:22 UTC, goankur commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/VectorUtilBenchmark.java
> +          byte[] a = new byte[size];
Yes this is the setup code for the benchmark. We run setup once every `iteration` for a total of `15` iterations across `3` forks (5 iterations per fork)  for each `size` being tested. Each fork is preceded by 3 warm-up iterations.
So before **each** iteration we generate random numbers in range [0-127] in two on-heap `byte[]`, allocate off-heap memory segments and populate them with contents from `byte[]`. These off-heap memory segments are provided to `VectorUtil.NATIVE_DOT_PRODUCT` method handle. 

(Code snippet below for reference)

```
@Param({"1", "128", "207", "256", "300", "512", "702", "1024"})
  int size;

@Setup(Level.Iteration)
public void init() {
...
}
```

> I wonder if we would see something different if we generated a large number of vectors and randomized which ones we compare on each run. Also would performance vary if the vectors are sequential in their buffer (ie vector 0 starts at 0, vector 1 starts at size...)

I guess the question you are hinting at is how does the performance vary when the two candidate vectors are further apart in memory (L1 cache / L2 cache / L3 cache / Main-memory). Do the gains from native implementation become insignificant with increasing distance ?  Its an interesting question and I propose that we add benchmark method(s) to answer them in a follow up PR. Does that sound reasonable ?

2024-10-25 22:12 UTC, goankur commented on lucene/benchmark-jmh/src/java/org/apache/lucene/benchmark/jmh/VectorUtilBenchmark.java
> +          byte[] a = new byte[size];
Nonetheless I will simplify the setup code to make it a bit more readable in the next iteration.

2024-10-28 20:16 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentByteVectorScorer.java
> +  MemorySegment offHeapScratch;
> I'm concerned about the cost of creating these for every scorer() we create because that happens a lot.

The `offHeapScratch` is only allocated in the rare case of vector data being split across multiple MemorySegments each representing a mmap region.

> Hmm now I see we did do that! But then I wonder why we also need to do it here.

When creating a `RandomVectorScorer()` for the give `byte[]` of query, we will need to copy these bytes to an off-heap for consumption within native dot-product. Native code can only work with memory that is outside the management of Java GC.

In the next revision, I am going to refactor some of these and add documentation to hopefully make this more clear.

2024-10-28 20:18 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentScalarQuantizedVectorScorer.java
> +/*
Yep! Will do in the next revision.

2024-10-28 20:22 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentByteVectorScorer.java
> +      if (offHeapQuery == null) {
This whole `NativeDotProductScorer` is gone in the next iteration. For the byteVector case, I am planning to generate offHeap MemorySegments in case native dot product is enabled. Then in `PanamaVectorUtilSupport.dotProduct(MemorySegment a, MemorySegment b)` we will delegate the computation to native code if both segments are native.

2024-10-28 23:21 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentScalarQuantizedVectorScorer.java
> +/*
Oops! Removed in the next revision.

2024-10-29 01:47 UTC, goankur commented on lucene/native/src/c/dotProduct.c
> +int32_t vdot8s_sve(int8_t vec1[], int8_t vec2[], int32_t limit) {
> Was the gcc path less performant?

Yes. The compiler auto-vectorized dot-product implementation shows `~14% ` **LOWER** throughput compared to this manually unrolled and vectorized implementation which uses SVE intrinsics. Here is the JMH benchmark output from the next revision executed on `AWS Graviton 3` instance. C implementation compiled with `GCC 10` and compiler flags `-O3 -march=native -funroll-loops`

```
Benchmark                        (size)   Mode  Cnt   Score   Error   Units
VectorUtilBenchmark.dot8s           768  thrpt   15  42.698 ± 0.719  ops/us
VectorUtilBenchmark.simpleDot8s     768  thrpt   15  36.814 ± 1.144  ops/us
```

Command to reproduce these results with the next revision

```
    java --enable-native-access=ALL-UNNAMED \
            --enable-preview \
            -Djava.library.path="./lucene/native/build/libs/dotProduct/shared" \
            -jar lucene/benchmark-jmh/build/benchmarks/lucene-benchmark-jmh-11.0.0-SNAPSHOT.jar regexp \
             "(.*)?(ot8s)" \
             -p "size=768"
```

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Stack overflow thread:
Thanks this is helpful, but let's not permanently record the SO thread in the code comments

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Q1. Why did we enable the native code path here if its inefficient ? A1. So that it can be
I don't think the unit-testing use case is a good one -- unit tests should be testing the actual production code path. I see that the required test setup would be complex, but IMO it's better to have simpler production code and complex unit tests than complex unused production code and simple unit tests!

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Q3. Should JMH benchmarks measure the performance of this method? A3. No, because they would
These comments are helpful for the PR, but I think in the actual code we would want to simplify and maybe say something like: do not call in production. Indeed we could possibly even add an `assert false: "inefficient implementation, do not use"` ? And in production fall back to the non-native impl

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +  public static MemorySegment offHeapByteVector(int numBytes) {
maybe put "random" in the name so we can easily tell this is creating a random value

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +      } catch (Throwable ex$) {
what are we trying to catch here?

2024-11-01 13:55 UTC, msokolov commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/Lucene99MemorySegmentScalarQuantizedVectorScorer.java
> +/*
lmk

2024-11-04 20:48 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Stack overflow thread:
ok! removed in the next revision.

2024-11-05 00:36 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Q1. Why did we enable the native code path here if its inefficient ? A1. So that it can be
makes sense!  The changes here were undone and `TestVectorUtilSupport`, `BaseVectorizationTestCase` were modified in the next revision to exercise the native code path

2024-11-05 00:40 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +   * <p>Q3. Should JMH benchmarks measure the performance of this method? A3. No, because they would
The `assert false:...` won't be necessary after undoing the changes as the old code wraps input `byte[]` into on-heap MemorySegment and native implementation is not exercised with that condition.

2024-11-05 00:42 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +  public static MemorySegment offHeapByteVector(int numBytes) {
I changed the implementation slightly to simply copy the input `byte[]` to off-heap MemorySegment. The process of populating the `byte[]` with random bytes will happen outside this method in the next revision.

2024-11-05 00:45 UTC, goankur commented on lucene/core/src/java21/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.java
> +      } catch (Throwable ex$) {
`WrongMethodTypeException` and anything else (`Throwable`) propagated by underlying method handle.  `WrongMethodTypeException` is a subclass of Throwable.

2024-11-07 01:54 UTC, goankur commented
#### Quick Update

1. Changes to use native dot-product for both `int7` scalar-quantized and raw vectors have been integrated in `core/src/java21`
2. `Lucene99ScalarQuantizedVectorScorer` was modified to use `Lucene99MemorySegmentFlatVectorScorer` when PanamaVectorizationProvider is enabled.
3. Unit tests in `TestVectorUtilSupport` have been expanded to exercise native dot-product code. 
4. JMH benchmarks contain methods to benchmark performance of compiler auto-vectorized implementation and manually vectorized implementation. 
5. `test.native.dotProduct` system property has been added to `gradle/testing/randomization.gradle` to enable randomized testing of native code.
6. Running using `KnnPerfTest` tool (in luceneutil) on 768 dimensional mpnet vectors show ~25% reduction in latency compared to baseline.


#### What's next
A lot of code in `Lucene99MemorySegmentScalarQuantizedVectorScorer` was duplicated from `Lucene99ScalarQuantizedVectorScorer`. This is because the native code only works with off-heap memory and new implementation needs to pass vectors as off-heap MemorySegment to native dotProduct.

It is for this (and performance) reasons that a MemorySegment slice containing vector bytes is obtained from underlying MemorySegmentAccessInput and passed to native dotProduct. A flip side is that query vector has to be copied to an off-heap buffer.

I don't like the fact that so much code had to be duplicated to make this work, so I am going to take a stab to see if there is an opportunity to minimize the duplication. 

I will also try to improve the coverage of unit tests although the changes in `Lucene99ScalarQuantizedVectorScorer` are gated behind flag -`Constants.NATIVE_DOT_PRODUCT_ENABLED` which is toggled by randomized testing so it should exercise the existing tests for raw and scalar quantized vectors.

2025-07-08 10:13 UTC, shubhamvishu commented
Hi, we see some good performance gains with this PR as we see above in the conversations. I ran the `luceneutil` benchmarks with this PR to measure the overall impact and below are the benchmark results on Graviton2 machine I used :

#### Setup :

- **Baseline** : current Apache lucene **main**
- **Candidate** : current Apache lucene **main** + [PR#13572](https://github.com/apache/lucene/pull/13572)
- Dataset : Cohere (768 dim)


#### Summary :

- We observe `~42-47%` reduction in latency and `~50%` reduction in CPUTime (*though little slow indexing?, maybe its not apple-apple comparison or we are missing something in squeezing the complete SIMD gains*) 


#### Baseline (with `-reindex` and `-numSearchThread` as 1) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.873  | 10.045      | 10.024 | 0.998        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |   641.24 |         779.74 |             3 |         1870.95 |       1832.962 |       368.118 | HNSW      |

&nbsp;
#### Candidate (with baseline index and `-numSearchThread` as 1) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.873  | 5.323       | 5.159  | 0.969        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |    0.00   |       Infinity |             3 |         1870.95 |       1832.962 |       368.118 | HNSW      |

&nbsp;
#### Baseline (with `-reindex` and `-numSearchThread` as CPU cores) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.875  | 5.696       | 10.052 | 1.765        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |   633.99 |         788.66 |             3 |         1871.02 |       1832.962 |       368.118 | HNSW      |

&nbsp;
#### Candidate (with baseline index and `-numSearchThread` as CPU cores) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.875  | 3.262       | 5.242  | 1.607        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |    0.00   |       Infinity |             3 |         1871.02 |       1832.962 |       368.118 | HNSW      |

&nbsp;
-----------------------------------------------
#### Some other runs :

&nbsp;
#### Candidate (with `-reindex` and `-numSearchThread` as 1) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.870  | 4.348       | 4.208  | 0.968        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |   808.15 |         618.70 |             2 |         1871.61 |       1832.962 |       368.118 | HNSW      |

&nbsp;
#### Candidate (with `-reindex` and `-numSearchThread` as CPU cores) :

| recall | latency(ms) | netCPU | avgCpuCount |  nDoc   | topK | fanout | maxConn | beamWidth | quantized | index(s) | index_docs/s | num_segments | index_size(MB) | vec_disk(MB) | vec_RAM(MB) | indexType |
|--------|-------------|--------|--------------|--------:|-----:|--------:|---------:|-----------:|-----------|----------:|---------------:|--------------:|----------------:|---------------:|--------------:|-----------|
| 0.872  | 3.355       | 4.434  | 1.322        | 500000 |  100 |     50 |       64 |        250 | 7 bits    |   802.49 |         623.06 |             2 |         1872.37 |       1832.962 |       368.118 | HNSW      |


I'm curious if there is anyway forward with this change here in Lucene, obviously not in the core but are we ok or not ok with having it in `misc` module? Thanks!

2025-07-08 12:23 UTC, msokolov commented
Thanks for bringing this up again! Now that Lucene main branch is requiring JDK24 we should be able to simplify a lot of the java interface (no more need for mrjar, I think?) and we should try to find a way to go forward.  The performance improvement is just too good; if we don't include this in Lucene, consumers are all going to build local forks to shoehorn it in.  it seems to me the main concerns from a user/consumer perspective are:

1. Building the C code must be optional, so platforms that don't support or need it can skip it. 
2.  The Java interface needs to gracefully fall back when the native module is not present
3. Instructions for linking to the native module need to be clearly documented

From a maintainer's POV I think we basically don't want to maintain a complex system of fallbacks and conditional loading that goes beyond what we already have (SPI, mrjars).  Hopefully w/JDK24 this is now possible?

As a side note, why are we maintaining lucene/core/src/java24 if JDK24 is now the required version?

2025-07-08 12:24 UTC, msokolov commented
@shubhamvishu are you interested to get this merged up to the latest on main branch? It will be a bit of a project since things have moved away from lucene/core/src/java21 and there may be other changes

2025-07-08 19:23 UTC, mikemccand commented
Thanks @shubhamvishu -- these results look incredible, if they hold up.  Odd that Panama Vector API (which Lucene uses for `dotProduct`) is so much slower on Graviton2.  It's also odd that indexing throughput got a bit slower with the change?  Much of the indexing cost for HNSW is actually searching (each insert is searching for top K vectors in the graph, so far, and adding those as edges for this vector's node)?

Oh, actually, in one run (baseline) you had 3 segments, and then later with candidate 2 segments, odd.

I really want the simple Python tool that I can run in my prod env and it tells me "yes, Lucene HNSW Is using optimal SIMD instructions in your JDK, Lucene version, OS, CPU architecture/revision, virtualized environment, etc." -- I opened luceneutil issue to try to make progress on this: https://github.com/mikemccand/luceneutil/issues/421 ... maybe `perf` tool can give us counters of how many of which CPU asm instructions are used or so?

2025-07-09 07:50 UTC, shubhamvishu commented
> are you interested to get this merged up to the latest on main branch? It will be a bit of a project since things have moved away from lucene/core/src/java21 and there may be other changes

Thanks for reviewing @msokolov! I agree the performance benefits look huge to just ignore the extra burden of maintaining native code in some module etc and yes I'm looking for getting this merged in main if the community agrees to do so(hence more eyes welcome). 

&nbsp;
> It will be a bit of a project since things have moved away from lucene/core/src/java21 and there may be other changes

I'm happy to rebase these changes and open a separate PR or update this one against the current main branch code

2025-07-09 09:53 UTC, shubhamvishu commented
> I really want the simple Python tool that I can run in my prod env and it tells me "yes, Lucene HNSW Is using optimal SIMD instructions in your JDK, Lucene version, OS, CPU architecture/revision, virtualized environment, etc.

@mikemccand I think we can rely on the what Uwe pointed out about the info message, we can take that as a definitive indicator (as it mention if its enabled or not and also the bit size for that machine). 

I opened https://github.com/mikemccand/luceneutil/pull/423 to add the functionality to get back the disassembled code using `perf` tool. It helps to see into what instructions got executed (and even more events that we like to look into). I used it to verify that for 7-bit case in this PR the `SDOT` instruction is getting used as expected like below :

**Baseline :**

```
>> PAGER=cat perf annotate -i perf1.data -f --stdio | head -100000 | grep "sdot"  // nothing
```

**Candidate :**

```
>> PAGER=cat perf annotate -i perf2.data -f --stdio | head -100000 | grep "sdot"        
    0.00 :   79c:    sdot    v0.4s, v2.16b, v4.16b
    0.00 :   7a8:    sdot    v7.4s, v6.16b, v5.16b
    0.00 :   7b0:    sdot    v22.4s, v3.16b, v16.16b
    0.00 :   7bc:    sdot    v21.4s, v18.16b, v17.16b
    0.28 :   7e4:    sdot    v0.4s, v19.16b, v20.16b
    0.55 :   7ec:    sdot    v7.4s, v23.16b, v30.16b
    0.44 :   7f4:    sdot    v22.4s, v24.16b, v31.16b
    1.81 :   7fc:    sdot    v21.4s, v25.16b, v1.16b
    0.34 :   804:    sdot    v0.4s, v26.16b, v2.16b
    0.58 :   80c:    sdot    v7.4s, v27.16b, v4.16b
    0.61 :   814:    sdot    v22.4s, v28.16b, v5.16b
    1.80 :   81c:    sdot    v21.4s, v29.16b, v3.16b
    0.00 :   8b4:    sdot    v0.4s, v22.16b, v16.16b
    0.00 :   8c0:    sdot    v0.4s, v17.16b, v18.16b
    0.00 :   8cc:    sdot    v0.4s, v19.16b, v23.16b
    0.00 :   8d8:    sdot    v0.4s, v24.16b, v25.16b
    0.00 :   8e4:    sdot    v0.4s, v26.16b, v27.16b
    0.00 :   8f0:    sdot    v0.4s, v28.16b, v29.16b
    0.00 :   914:    sdot    v0.4s, v20.16b, v30.16b
    0.00 :   928:    sdot    v0.4s, v31.16b, v6.16b
    0.00 :   94c:    sdot    v0.4s, v16.16b, v22.16b
    0.00 :   950:    sdot    v0.4s, v21.16b, v17.16b
    0.00 :   954:    sdot    v0.4s, v5.16b, v18.16b
    0.00 :   958:    sdot    v0.4s, v4.16b, v19.16b
    0.00 :   95c:    sdot    v0.4s, v3.16b, v23.16b
    0.00 :   960:    sdot    v0.4s, v2.16b, v24.16b
    0.00 :   a04:    sdot    v25.4s, v28.16b, v29.16b
    0.00 :   a14:    sdot    v25.4s, v20.16b, v30.16b
    0.00 :   a24:    sdot    v25.4s, v31.16b, v21.16b
    0.00 :   a34:    sdot    v25.4s, v5.16b, v4.16b
    0.00 :   a44:    sdot    v25.4s, v3.16b, v2.16b
    0.00 :   a54:    sdot    v25.4s, v6.16b, v22.16b
    0.00 :   a88:    sdot    v25.4s, v16.16b, v17.16b
    0.00 :   aa0:    sdot    v25.4s, v23.16b, v24.16b
    0.00 :   aa4:    sdot    v25.4s, v18.16b, v19.16b
    0.00 :   ab0:    sdot    v25.4s, v0.16b, v7.16b
    0.00 :   abc:    sdot    v25.4s, v1.16b, v26.16b
    0.00 :   ac8:    sdot    v25.4s, v27.16b, v28.16b
    0.00 :   ad4:    sdot    v25.4s, v29.16b, v20.16b
    0.00 :   ae0:    sdot    v25.4s, v30.16b, v31.16b
    0.00 :   bf8:    sdot    v0.4s, v21.16b, v6.16b
    0.00 :   c0c:    sdot    v25.4s, v27.16b, v26.16b
```

2025-07-09 12:42 UTC, mikemccand commented
> I opened [mikemccand/luceneutil#423](https://github.com/mikemccand/luceneutil/pull/423) to add the functionality to get back the disassembled code using `perf` tool. It helps to see into what instructions got executed (and even more events that we like to look into). I used it to verify that for 7-bit case in this PR to ensure on ARM aarch the `SDOT` instruction (specifically for dot product calculations) is getting used in candidate as expected like below :

WHOA!  This looks awesome!  So it uses `perf` tool to execute `knnPerfTest`, recording a histogram of which instructions executed how many times or so?  And then we check for which instructions we think we know we want to see executed based on the current CPU arch / revision (`sdot` in this case)?

2025-12-12 18:36 UTC, shubhamvishu commented
Hi,

Here at Amazon (customer facing product search), we’ve been testing this native dot product implementation in our production environment(ARM - Graviton 2 and 3) and we see **5-14x** faster dot product computations in JMH benchmarks and we observed semantic latency improving from **62 msec** to **28 msec** (avg) for 4K embeddings(4.5 MM). Overall we saw **10-60%** improvement on end-end avg search latencies in different scenarios (different sized vectors, vector-focused search vs search combined with other workloads). We haven’t tested all other CPUs types yet. I'm working on a draft PR on top of this PR with following changes and planning to raise it soon :

- Removing the overhead from heap to off-heap copying by utilizing `Linker.Option.critical`, which eliminates unnecessary copying 
- Runtime dispatch using `IFUNC` to choose SVE vs NEON vs scalar implementation at runtime based on available intrinsics
- Build related changes to generate the binary

We kept the native code isolated in the misc package and not getting it in the core module which we know is highly discouraged. Additionally, PR #15285 would later help eliminate some code duplication and enable a cleaner implementation similar to `PanamaVectorUtilSupport` - potentially through a `NativeVectorUtilSupport` class?

Our benchmarking suggests substantial optimization potential for ARM-based deployments, and we believe this could benefit the broader Lucene community. We hope to make it easy for any Lucene user to opt-in to this alternative vector implementation ideally. We're committed to refining this implementation based on community feedback and addressing any concerns during the review process. I'm eager to hear the community's thoughts on this change, as there appears to be significant optimization potential for ARM architectures that could benefit many users. Thank you!

2025-12-13 00:47 UTC, goankur commented
Thanks Shubham for discovering `Linker.Option.critical(true)` that allows JVM to interoperate between off-heap and on-heap memory in a foreign (native) function.  This eliminates extra on-heap to off-heap copying which improves the efficiency  of this approach further as validated by our production environment at Amazon. 

As an introductory note, both Shubham and I work at Amazon in the team that designs, builds and operates Amazon's product search engine.

Given the compelling performance improvements we are observing in production, especially with large (1K+ dimension) vectors, we'd love to work with the community to contribute it back so that larger Lucene community can benefit from this change. As Shubham mentioned, we are committed to supporting this alongside rest of the Lucene community. Please advise how to proceed.

To reiterate, the credit for the original idea goes to this blog post from Elastic
https://www.elastic.co/search-labs/blog/vector-similarity-computations-ludicrous-speed

2025-12-15 15:28 UTC, msokolov requested changes
This issue has been open for some time now; thanks for refreshing it, @shubhamvishu, and sharing the test results.  For one thing -- the issue title is confusing -- this has morphed from a new benchmark to support for native dot-product in vector search.

There is a lot of change here, but most of it has been in review for some time now. I think we should go forward soon and merge this improvement. It looks like the PR here has some merge conflicts making it hard to tell what's new. Could you work on resolving those so we can have a clean change set here?

2025-12-15 15:28 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/util/VectorUtil.java
curious - is this part of the PR? Why did we have to remove this assert?

2025-12-17 03:40 UTC, shubhamvishu commented on lucene/core/src/java/org/apache/lucene/util/VectorUtil.java
This is not required actually. Maybe just some stale change.

2025-12-17 04:00 UTC, shubhamvishu commented
Thanks @msokolov and @goankur! I opened https://github.com/apache/lucene/pull/15508 with proposed changes and move ahead with this. I also shared the JMH benchmark results with the PR [here](https://github.com/apache/lucene/pull/15508#issuecomment-3663515114). Looking forward to your thoughts.

2025-12-17 18:07 UTC, shubhamvishu commented
Hi @ChrisHegarty, following up on [your comment](https://github.com/apache/lucene/pull/13572#issuecomment-2236530280) about opening a bug issue for this in OpenJDK. I heard from an OpenJDK contributor that there isn't a bug filed for this yet. Should we create one now?

2026-02-09 19:48 UTC, shubhamvishu commented
FYI we now have a bug/issue filed in OpenJDK to improve vector operation support on AArch64 machines : https://bugs.openjdk.org/browse/JDK-8377386

2026-09-10 00:16 UTC, closed without merging