Replace Map<String,Object> with IntObjectHashMap for KnnVectorsReader
apache/lucene pull request #13763
Opened 2024-09-11 13:00 UTC by bugmakerrrrrr

### Description
Following up on #13686.

2024-09-11 13:15 UTC, bugmakerrrrrr commented on lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldKnnVectorsFormat.java
>          return null;
According to the Javadoc of `KnnVectorsReader#getFloatVectorValues`:
> Returns the FloatVectorValues for the given field. The behavior is undefined if the given field doesn't have KNN vectors enabled on its FieldInfo. The return value is never null.

Maybe we should return an empty instance if the target field doesn't exists in the segment or we should correct the Javadoc.

2024-09-11 13:19 UTC, bugmakerrrrrr commented on lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene90/Lucene90HnswVectorsReader.java
> +    final FieldInfo info = fieldInfos.fieldInfo(field);
Yes, this is also what I want to discuss. You can ref to my comment below, if we all agree to check for `null`, I can fix this.

2024-09-11 13:24 UTC, jpountz commented on lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene90/Lucene90HnswVectorsReader.java
> +    final FieldInfo info = fieldInfos.fieldInfo(field);
In my opinion, the most important thing is to remove the leniency we have in some places, like `if (fieldEntry == null) return EMPTY_VECTOR_VALUES`, which could hide bugs. Checking for null explicitly is not required, though it's obviously nice.

2024-09-11 13:26 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldKnnVectorsFormat.java
>          return null;
The javadocs are correct. AssertingKnnVectorsReader checks for this.

2024-09-12 07:45 UTC, bugmakerrrrrr commented on lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldKnnVectorsFormat.java
>          return null;
forgive me if i misunderstand something, but the javadoc says that **the return value is never null**, and we do return null in `PerFieldKnnVectorsFormat`. If we check the field info in caller, `AssertingKnnVectorsReader` will always get the non-null value from the delegate.

2024-09-13 15:49 UTC, bugmakerrrrrr commented
@benwtrent @jpountz I have merged main branch into this one, can I get a review on this?

2024-09-17 11:38 UTC, benwtrent approved these changes

2024-09-18 15:28 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldKnnVectorsFormat.java
>          return null;
It's probably not worded as well as it could, it wants to say that the return value is never null when the field has vector enabled on its field infos.

2024-09-18 15:30 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldKnnVectorsFormat.java
>          return null;
These checks on info==null and reader == null are not hurting, but they are not needed either since KnnVectorsFormat#getFloatVectorValues should not be called when the field doesn't have vectors enabled on its infos.

2024-09-19 13:03 UTC, ChrisHegarty requested changes
Awaiting result of discussion #13805

2024-10-14 11:24 UTC, bugmakerrrrrr commented
hi @jpountz ,since we have moved to lucene 10, should we merge this and add back #13686?

2024-10-15 14:16 UTC, jpountz commented
Would you like to make this PR up-to-date and open a new one for the other change (a cherry-pick isn't clean due to other changes)?

2024-10-15 15:44 UTC, bugmakerrrrrr commented
> Would you like to make this PR up-to-date and open a new one for the other change (a cherry-pick isn't clean due to other changes)?

@jpountz sure, I‘d be happy to do this.

2024-10-16 13:12 UTC, bugmakerrrrrr commented
@jpountz I have merged main branch, PTAL:)

2024-10-25 13:18 UTC, jpountz approved these changes

2024-10-31 15:16 UTC, merged