Ensure stability of clause order for DisjunctionMaxQuery toString
apache/lucene pull request #13944
Opened 2024-10-22 21:06 UTC by ljak

Since https://github.com/apache/lucene/pull/110, the disjuncts elements of DisjunctionMaxQueries don't have an order anymore, which is impacting the `toString` method. In isolation, that does not matter. But, in Solr, when the debug component is needed for a distributed query, every shard can return a different toString representation of the same query... and the different toString keys of the debug response will have an array value, containing those different representations (instead of having one value for one same representation).

Example with the `parsedquery_toString` key (of a json response within Solr):
`parsedquery_toString":["((docIdentifiers:\"Okarandeep Osingh\" docIdentifiers:Otest) | (docTitle:\"Okarandeep Osingh\" docTitle:Otest) | (docBody:\"Okarandeep Osingh\" docBody:Otest))","((docBody:\"Okarandeep Osingh\" docBody:Otest) | (docTitle:\"Okarandeep Osingh\" docTitle:Otest) | (docIdentifiers:\"Okarandeep Osingh\" docIdentifiers:Otest))"]`

When PR110 was merged, Solr adapted its unit tests this way: https://github.com/apache/solr/pull/117 but, later on within Lucene, the toString method of DisjuctionIntervalsSource was adapted in prevision of a potential similar future change: https://github.com/apache/lucene/pull/193. 

I adapted the toString method of DisjunctionMaxQueries similarly to this PR.

2024-10-23 08:21 UTC, jpountz requested changes
I'm a bit unhappy about making `toString()` run in O(n log(n)) with the number of clauses. Could we instead save a list copy of the queries in the constructor and use the list for `toString()`? `BooleanQuery` does something similar.

2024-10-23 14:50 UTC, ljak commented
Thanks for the feedback. Looking at `BooleanQuery`, it "only" has one list `List<BooleanClause> clauses`. So, is the idea to have 2 structures for the `DisjunctionMaxQuery`, the unordered multiset of queries and a sorted list of queries, where the latter is only used for the `toString` method ? 

2024-10-23 14:56 UTC, jpountz commented
See `BooleanQuery#clauseSets`, which is used for equals()/hashcode() and `BooleanQuery#clauses`, which is used for toString().

2024-10-23 19:12 UTC, ljak commented
I needed to sort the `Query`s in some ways, so I compare them according to their toString representation:

`orderedQueries.sort(Comparator.comparing(Query::toString));`

Not sure if it's the right way.

2024-10-24 15:00 UTC, jpountz commented
I wouldn't sort them, and just rely on the order that the caller supplied?

2024-10-24 15:29 UTC, jpountz commented
Yes, exactly.

2024-10-24 16:22 UTC, jpountz approved these changes

2024-10-25 11:32 UTC, jpountz commented
Can you add an entry to `lucene/CHANGES.txt` under version 10.1.0? Then I'll merge.

2024-10-25 15:46 UTC, ljak commented
Done. Thanks for reviewing!

2024-10-25 16:21 UTC, merged

2024-10-27 19:39 UTC, dsmiley commented
Thanks for this!  I had to redo a bunch of tests over this matter at work.