Addresses the issue #13983 by adding filter to the toString() method of KnnFloatVectorQuery
apache/lucene pull request #13990
Opened 2024-11-12 13:29 UTC by viswanathk

2024-11-12 13:59 UTC, benwtrent requested changes
Could you update the byte knn query & DiversifyingChildern* knn queries as well?

2024-11-12 13:59 UTC, benwtrent commented on lucene/core/src/test/org/apache/lucene/search/TestKnnFloatVectorQuery.java
> +import org.apache.lucene.index.*;
Let's not collapse to `*`

2024-11-12 13:59 UTC, benwtrent commented on lucene/core/src/java/org/apache/lucene/search/KnnFloatVectorQuery.java
> +    }
```suggestion
    if (this.filter != null) {
      buffer.append("[" + this.filter + "]");
    }
```

I think that would be better.

2024-11-12 14:40 UTC, viswanathk commented
> Could you update the byte knn query & DiversifyingChildern* knn queries as well?

I made the changes fo DiversifyingChildren*, but by byteknn do you mean `ByteVectorSimilarityQuery`?

2024-11-12 15:00 UTC, jpountz commented
I believe that @benwtrent meant `KnnByteVectorQuery`.

2024-11-12 15:26 UTC, viswanathk commented
I hope I got all of them now.

2024-11-12 15:34 UTC, benwtrent commented on lucene/join/src/java/org/apache/lucene/search/join/DiversifyingChildrenByteKnnVectorQuery.java
> -    return getClass().getSimpleName() + ":" + this.field + "[" + query[0] + ",...][" + k + "]";
test updates for this and the float version? The tests are in: TestParentBlockJoinByteKnnVectorQuery and of course the float version as well.

2024-11-12 15:37 UTC, viswanathk commented on lucene/join/src/java/org/apache/lucene/search/join/DiversifyingChildrenByteKnnVectorQuery.java
> -    return getClass().getSimpleName() + ":" + this.field + "[" + query[0] + ",...][" + k + "]";
yeah, i did check them. they didn't have existing tests that cover `toString` so skipped them. will add that coverage though.

2024-11-12 15:57 UTC, viswanathk commented on lucene/join/src/java/org/apache/lucene/search/join/DiversifyingChildrenByteKnnVectorQuery.java
> -    return getClass().getSimpleName() + ":" + this.field + "[" + query[0] + ",...][" + k + "]";
@benwtrent for the Diversifying* does it make sense to capture the `childFilter` and `parentsFilter` in toString() as well?

2024-11-13 17:49 UTC, jpountz approved these changes

2024-11-13 17:49 UTC, jpountz commented on lucene/join/src/java/org/apache/lucene/search/join/DiversifyingChildrenByteKnnVectorQuery.java
> -    return getClass().getSimpleName() + ":" + this.field + "[" + query[0] + ",...][" + k + "]";
It's not obvious to me, `parentsFilter` is more a property of the index than of the query. You could have multiple levels of parents, which would make this property relevant to print, but at the same time I don't think they have proper toString() implementations. Let's leave it out for now.

2024-11-13 17:51 UTC, jpountz commented
> Could you update the byte knn query & DiversifyingChildern* knn queries as well?

Unrelated: I noticed that the `DiversifyingChildren*` queries don't use the filter to evaluate the query, is this a bug?

2024-11-13 20:35 UTC, benwtrent commented
> Unrelated: I noticed that the DiversifyingChildren* queries don't use the filter to evaluate the query, is this a bug?

I am unsure what you mean by this? The filter is utilized when building the accepted docs set in the super() classes.

2024-11-15 21:18 UTC, vigyasharma approved these changes

2024-11-18 13:56 UTC, benwtrent approved these changes
I think a `CHANGES` entry is in order. This seems like a nice little bug fix to aid folks in debugging issues.

@viswanathk once you add the changes entry, I can merge and backport to 10.x

2024-11-18 16:34 UTC, viswanathk commented
> I think a `CHANGES` entry is in order. This seems like a nice little bug fix to aid folks in debugging issues.
> 
> @viswanathk once you add the changes entry, I can merge and backport to 10.x

@benwtrent Added in `CHANGES` for 10.1. Also corrected some git history mess up.

2024-11-18 19:44 UTC, merged