Grammar and typo fixes
apache/lucene pull request #14019
Opened 2024-11-25 08:41 UTC by viliam-durina

A random collection while reading through the code.

2024-11-28 18:40 UTC, shubhamvishu commented on lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
> +   * @return <code>true</code>, iff the given DWPT has been removed. Otherwise <code>false</code>
Maybe fix /iff/if/ since you are at it?

2024-11-28 19:25 UTC, viliam-durina commented on lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
> +   * @return <code>true</code>, iff the given DWPT has been removed. Otherwise <code>false</code>
"Iff" is correct, it means "if and only if", see https://www.merriam-webster.com/dictionary/iff

2024-12-01 17:11 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
> +   * @return <code>true</code>, iff the given DWPT has been removed. Otherwise <code>false</code>
Since this is all about syntax, grammar, etc, we might as well italicize _iff_ since that is how it is generally done, as in the example you cited.

2024-12-01 17:22 UTC, msokolov reviewed
I started reviewing these one by one, but as I go I find that many of these changes insert unneeded commas and other agrammatical constructions that are sometimes worse than the original (which admittedly could stand to be improved). If you really want to work on this, I am happy to give out more grammar pedantry (it tickles some kind of weird obsession I have), but maybe it is not worth our time?

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
> +   * @return <code>true</code>, iff the given DWPT has been removed. Otherwise <code>false</code>
also, the comma you inserted is not correct (try replacing iff with "if and only if" - we wouldn't use a comma before "if").

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexCommit.java
> + * <p>Changes to the content of an index are made visible only after the writer which made that
sorry this is wrong. We could use `that`, but `who` is also correct - no need to "fix" it,

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexCommit.java
> + * change commits by writing a new segments file (<code>segments_N</code>). This point in time, when
OK this sentence is awkward, but what you've done here doesn't really address the core problem. I think it really would be most correct as:  "_The_ point in time (no comma) when ... is completed (no comma) is an index commit".

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexOptions.java
> +   * scoring, except phrase and other positional queries will throw an exception.
I think I would prefer to avoid this ambiiguity by using  `PhraseQuery` explicitly

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> + * index until they re-open. If {@link OpenMode#CREATE_OR_APPEND} is used, IndexWriter will create a
Again, not a great sentence, but fixing it requires a bigger rewrite; I don't think that this change is better (the "will" has no subject).

2024-12-01 17:22 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> + * usage with a large RAM buffer. In contrast to the other flush options, in case of {@link
let's leave this as it was. It was OK.

2024-12-02 09:34 UTC, viliam-durina commented
Thanks for the review :+1: 

I reverted all the disputed changes, agree we should not go into unproductive discussions. I added a few new ones, they are in a separate commit to simplify the review.

I'll only have note to the `writer ... who` (https://github.com/apache/lucene/pull/14019#discussion_r1864958353) - "who" should be used only for persons, this writer is not a person. But I reverted it anyway.

2024-12-02 14:00 UTC, msokolov approved these changes

2024-12-02 14:14 UTC, msokolov requested changes
Thank you for all the fixes! I reviewed them all this time, and I think there are just a couple of changes I'd like to see before merging.

2024-12-02 14:14 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
> + * commit deleted under their hands. The latter is necessary when multiple computers take turns
this sounds like an idiom of sort, but I've never heard it -- I think the existing phrasing is more idiomatic of the English I know anyway.

2024-12-02 14:14 UTC, msokolov commented on lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java
>     * <p>Currently there is no API support to un-delete a soft-deleted document. In oder to un-delete
Can we fix "In oder" to be "In order"?

2024-12-03 16:51 UTC, msokolov approved these changes
Looks good, thank you!

2024-12-03 16:51 UTC, merged

2024-12-03 17:00 UTC, msokolov commented
BTW I am fascinated by your github avatar pic! I feel like I have seen it before but not sure where? I tried image search but it does not find it. Is it something well known?

2024-12-03 17:31 UTC, viliam-durina commented
> BTW I am fascinated by your github avatar pic! I feel like I have seen it before but not sure where? I tried image search but it does not find it. Is it something well known?

It's an illustration from a children book by Albín Brunovský :smile:

2024-12-03 18:08 UTC, msokolov commented
wow those books would scare any child that I know!