LUCENE-10087 Disable numeric sort optim when needed
apache/lucene pull request #286
Opened 2021-09-07 15:44 UTC by mayya-sharipova

Add a method to SortField that allows to disable numeric sort optimization,
which is enabled by default from 9.0.

2021-09-08 07:44 UTC, romseygeek approved these changes
LGTM, thanks @mayya-sharipova

2021-09-08 08:24 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
I think we should be more specific regarding what optimization we are talking about. Maybe call it something like `pointSortOptimization` and update javadocs to say something like `Disable numeric sort optimization to use the Points index to skip over non-competitive documents`?

2021-09-08 08:24 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  public void disableSortOptimization() {
I wonder if we should mark it `@Deprecated` and highlight in javadocs that this should only be used for compatibility with 8.x indices that got created with inconsistent data across fields, or the wrong sort configuration in the index sort?

2021-09-08 12:13 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
Addressed in 9fe721c02ecefd5cee261da4c64b4b785a044f88

2021-09-08 12:13 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  public void disableSortOptimization() {
Addressed in 9fe721c02ecefd5cee261da4c64b4b785a044f88

2021-09-08 12:14 UTC, mayya-sharipova commented
@romseygeek Thanks for the review.

@jpountz I've addressed your comments. Can you please continue the review.

2021-09-08 12:17 UTC, jpountz approved these changes
:+1:

2021-09-08 12:17 UTC, jpountz commented on lucene/CHANGES.txt
> +* LUCENE-10089 Add a method to SortField that allows to disable numeric sort
```suggestion
* LUCENE-10089: Add a method to SortField that allows to disable numeric sort
```

2021-09-08 13:53 UTC, rmuir requested changes
I left some suggestions

2021-09-08 13:53 UTC, rmuir commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  private boolean pointSortOptimizationDisabled = false;
Can we make this "positive" to avoid double negatives? I suggest `private boolean optimizePoints = true;` It should also be deprecated.

2021-09-08 13:53 UTC, rmuir commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
Can we make this an ordinary setter? I suggest `setOptimizePoints(boolean)`.

2021-09-08 13:53 UTC, rmuir commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  protected boolean pointSortOptimizationDisabled() {
Can we make this an ordinary getter? I suggest `getOptimizePoints()`. It should be deprecated and public IMO.

2021-09-08 19:22 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
@rmuir Thanks for a suggestion.  What we wanted is to have sort optimization to be always enabled for a request, unless a user explicitly disables it.  We don't have a use case for `setOptimizePoints(true)`, that's why we decided to call this method `disablePointSortOptimization()`.

2021-09-08 20:02 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  private boolean pointSortOptimizationDisabled = false;
Thanks for comment, addressed in 23724f72057655ca51996570e6504f54d75af307

2021-09-08 20:02 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  protected boolean pointSortOptimizationDisabled() {
Thanks for comment, addressed in 23724f72057655ca51996570e6504f54d75af307

2021-09-08 22:25 UTC, rmuir commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
personally i think the default is handled by the boolean defaulting to `true` ? Just thinking that an ordinary getter/setter is the most obvious way to control it to have an intuitive API. It already looks much better

2021-09-09 11:27 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
I have a preference for a traditional getter/setter too.

2021-09-09 12:45 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/search/SortField.java
> +  }
Thanks @rmuir and @jpountz for the additional comments. Addressed in a355c172abb9b1ec3f202de31f74e710d5936d0c

2021-09-09 13:08 UTC, rmuir approved these changes

2021-09-09 13:22 UTC, jpountz approved these changes

2021-09-09 14:22 UTC, merged