LUCENE-9507 Custom order for leaves in IndexReader and IndexWriter
apache/lucene pull request #32
Opened 2021-03-22 15:56 UTC by mayya-sharipova

1. Add an option to supply a custom leaf sorter for IndexWriter.
A DirectoryReader opened from this IndexWriter will have its leaf
readers sorted with the provided leaf sorter. This is useful for
indices on which it is expected to run many queries with particular
sort criteria (e.g. for time-based indices this is usually a
descending sort on timestamp). Providing leafSorter allows
to speed up early termination for this particular type of
sort queries.

2. Add an option to supply a custom sub-readers sorter for
BaseCompositeReader. In this case sub-readers will be sorted 
according to the the provided leafSorter.

3. Add an option to supply a custom leaf sorter for
StandardDirectoryReader. The leaf readers of this
StandardDirectoryReader will be sorted according to
the the provided leaf sorter.

2021-03-23 14:08 UTC, mikemccand approved these changes
This looks like a nice feature!  Thank you @mayya-sharipova!

I left small comments that shouldn't block pushing this cool new feature.

One warning: our reader constructor/factory API is crazy complex and it's easy with an addition like this to accidentally break backwards compatibility in the public API.  From what I saw you succeeded in preserving backwards compatibility, except for internal / protected constructors, and so we could backport this to 8.x too, but maybe double check that ;)

2021-03-23 14:08 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java
> +  public enum OpenMode {
Silly java, why doesn't `javac` warn/tell us that `static` is pointless for `enum`?  Hmm, it is pointless, right?

Wow, we have tons of `static enum` in our codebase!  I'll open a separate PR, this is crazy.

2021-03-23 14:08 UTC, mikemccand commented on lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java
> +  protected Comparator<LeafReader> leafSorter = null;
No need for `= null` -- it is default already for java.

2021-03-23 21:13 UTC, jimczi commented on lucene/core/src/java/org/apache/lucene/index/DirectoryReader.java
> +   *     through segments and segments' documents.
It seems to work well in practice with the tiered merge policy and natural merging. The natural order of insertion seems to be preserved nicely in the levels. Things get complicated when sorting on descending order though. The big segments tend to have the data in ascending order. So in this scenario, it's much slower to retrieve the latest documents if the index was force merged to 1 segment or few big ones. In Elasticsearch we shuffle the order of the segments on force merge to alleviate this bias. 
In this PR we opted for a single sort per index so I like the idea of having a merge policy that is optimized for this use case. I think it's a good compromise for cases where index sorting is too costly at the document level.

2021-03-24 12:03 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java
> +    return subReadersSorter;
> .. if we wrap this reader in a FilterDirectoryReader, that wrapped reader will also sort its leaves the same way?

Thank you , that's a very good point, you are right, indeed the wrapped reader will already sort its leaves the same way.  Fixed by removing `sorter` in `FilterDirectoryReader` in 34da11d80d30c1d4a418066edfadce0dde3379ae

> .. why does the reader need to record its sorter? I guess maybe callers might want to "chain" the sorter -- have this reader remember what sorter was used, and on refresh, pull that sorter out and use it again for the next reader, ok.

Right, indeed.  In `StandardDirectoryReader::doOpenIfChanged`, we reuse sorter.

2021-03-24 12:03 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java
> +  protected Comparator<LeafReader> leafSorter = null;
Fixed in 34da11d80d30c1d4a418066edfadce0dde3379ae

2021-03-24 12:04 UTC, mayya-sharipova commented
@mikemccand Thanks a lot for your feedback, addressed in 34da11d80d30c1d4a418066edfadce0dde3379ae

2021-03-24 17:35 UTC, uschindler requested changes

2021-03-24 17:35 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java
> +  final Comparator<R> subReadersSorter;
Why is this package protected? This is a public class, so if it is needed by subclasses, it needs to be protected. If it is not needed by subclasses, make it private.

2021-03-24 18:59 UTC, mayya-sharipova commented on lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java
> +  final Comparator<R> subReadersSorter;
@uschindler Thank you for checking. That's a great observation. As the field is used by subclasses, I made it `protected` in d9159c7e13492d22acf0003e262074479314cf4b.

2021-03-24 20:54 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java
> +  final Comparator<R> subReadersSorter;
Thanks, much better now!

2021-03-26 13:56 UTC, merged