LUCENE-10260: Luke's about window no longer shows version number
apache/lucene pull request #473
Opened 2021-11-24 19:32 UTC by dweiss

2021-11-24 19:52 UTC, uschindler commented
Looks fine, although I think the class LucenePackage should possibly go away completely in 9.

We can add a getImplementationVersion to our standard Version class which looks like a better place.

2021-11-24 19:54 UTC, dweiss commented
Sure, nuke or move anything you want - I just wanted to show that this works.

2021-11-24 19:55 UTC, uschindler requested changes

2021-11-24 19:55 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
Better use try with resources

2021-11-24 20:03 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
NPE?

2021-11-24 20:04 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
(if manifest is not there for some reason).

2021-11-24 20:28 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
Try with resources works with null.

2021-11-24 20:31 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3

> A resource is closed only if it initialized to a non-null value.

2021-11-24 21:18 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/LucenePackage.java
> +          try {
Ah! You learn every day, thanks!

2021-11-25 07:45 UTC, dweiss commented
> We can add a static getImplementationVersion to our standard Version class which looks like a better place.

Done. I verified that both of these work and show the implementation version:

{code}
java -jar lucene/luke/build/lucene-luke-10.0.0-SNAPSHOT/lucene-luke-10.0.0-SNAPSHOT-standalone.jar
java --module-path lucene/luke/build/lucene-luke-10.0.0-SNAPSHOT --add-modules org.apache.logging.log4j -m lucene.luke
{code}

2021-11-25 07:48 UTC, dweiss commented
This is what is shows if started from the IDE (when no module and no manifest is preset). I think it's fine:
![image](https://user-images.githubusercontent.com/199470/143400661-6c1fe713-fdf1-4cc5-8f65-562c512e13cc.png)

2021-11-25 13:59 UTC, uschindler approved these changes

2021-11-25 14:07 UTC, uschindler commented
Hi,

this looks good to me. I am a bit hesitant about Version.getImplementationVersion(), as the Version class also has a LATEST and CURRENT_VERSION symbol. Mabye rename Version.getPackageImplementationVersion().

But I am happy of the functionality, but because of this as a new API addition, we should think about naming.

2021-11-25 14:31 UTC, uschindler commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
>            + (Objects.nonNull(LUCENE_IMPLEMENTATION_VERSION) ? LUCENE_IMPLEMENTATION_VERSION : "")
I think the nullcheck is not needed anymore.

2021-11-25 15:24 UTC, dweiss commented
The more I think about it, the more I'm wondering why this method is needed... Luke receives the same metadata (manifest) as the rest of Lucene - we could just display this instead (from our own module), remove the extra method from the core and, just in case, display Version.VERSION_CURRENT (or whatever it's called) to indicate which Lucene JAR Luke is working against. I'm not even sure a scenario of running Luke against a different Lucene version is supported, but just in case.

2021-11-25 15:35 UTC, uschindler commented
Hi Dawid,
i think the important thing was in former days of Luke to see the implementation version of lucene-core.jar. Also other projects like Elasticsearch or Solr want to show this. So I think the method in Version is fine.
We should at least add a cahenges entry that we removed the LucenePackage class and added a implementation version getter in lucene's core.
About luke: Of course luke could only show its version, but for the reasons above i tend to think that we should provide a way for external projects to show the lucene version they are linking to.
I think code is same, but having a Version.getImplementationVersion() is a good idea to have. We provided it for years (since Lucene v1.0).

2021-11-25 16:38 UTC, dweiss commented
ok, sure. please go ahead and commit those minor changes/ merge them in if you like - I'll be home late.

2021-11-26 02:16 UTC, mocobeta commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
> +      Version.getPackageImplementationVersion();
(Question) If Luke runs on module mode and `MANIFEST.MF` does not exist in lucene-core jar for some reason (on development?), Luke fails to start...?

2021-11-26 03:59 UTC, mocobeta commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
>        "<p>[Implementation Version]</p>"
Browsing through the conversation here:
Just to be more specific, how about changing this to `Lucene Implementation Version` if we see Luke is a standalone application strictly separated from the Lucene core module?

2021-11-26 04:12 UTC, mocobeta commented
> I'm not even sure a scenario of running Luke against a different Lucene version is supported, but just in case.

(Yes there are some needs like that - some people want to browse an old Lucene codec with the latest Luke - though I think supporting multiple Lucene API versions is not feasible.)

2021-11-26 06:20 UTC, dweiss commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
> +      Version.getPackageImplementationVersion();
Version.getPackageImplementationVersion will always return a non-null string - an "unknown" string is returned if manifest is not present.

2021-11-26 06:21 UTC, dweiss commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
>        "<p>[Implementation Version]</p>"
I think it makes sense.

2021-11-26 07:25 UTC, dweiss commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
>        "<p>[Implementation Version]</p>"
Done.

2021-11-26 07:32 UTC, merged

2021-11-26 09:02 UTC, mocobeta commented on lucene/luke/src/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/AboutDialogFactory.java
>        "<p>[Implementation Version]</p>"
Thanks!