Use the same analysis chain to StandardAnalyzer (a follow-up #480)
apache/lucene pull request #482
Opened 2021-11-27 14:16 UTC by mocobeta

This mimics the StandardAnalyzer.

https://github.com/apache/lucene/pull/480#pullrequestreview-817120063

2021-11-27 16:32 UTC, uschindler commented on lucene/luke/src/java/org/apache/lucene/luke/models/analysis/AnalysisImpl.java
> +          .withTokenizer(StandardTokenizerFactory.NAME, params)
You don't need a map. Customanalyzer takes a Varars of strings. We should use the code in the "official way" (see examples in Javadocs).

```
return CustomAnalyzer.builder()
          .withTokenizer(StandardTokenizerFactory.NAME, params), "maxTokenLength", Integer.toString(StandardAnalyzer.DEFAULT_MAX_TOKEN_LENGTH))...
```

2021-11-27 16:36 UTC, uschindler commented on lucene/luke/src/java/org/apache/lucene/luke/models/analysis/AnalysisImpl.java
> +          .withTokenizer(StandardTokenizerFactory.NAME, params)
Here's a quite complex example by Robert. Please also note the recommend formatting:

https://github.com/uschindler/german-decompounder#lucene-api-example

2021-11-27 16:41 UTC, uschindler requested changes
I left a minor comment on formatting and the recommend usage (no HashMaps needed).

My question (haven't tried): when you do it like that would the user interface also prefilled? If not, we can simply use StandardAnalyzer and don't need to use this code.

Otherwise I am ok.

2021-11-27 18:44 UTC, uschindler commented
Hi,
I did some quick tests. I was expecting to see the standard analyzer defaults already predefined in the UI.
As this is not the case, I would stay with `new StandardAnalyzer()`. It is easier and useful.

I had some other idea: You could also add a line to enter the class name of an Analyzer and add a button "Instantiate class (requires no-arg constructor)".

2021-11-27 23:37 UTC, mocobeta commented
I replaced the default to `StandardAnalyzer`.

> I did some quick tests. I was expecting to see the standard analyzer defaults already predefined in the UI.
> As this is not the case, I would stay with new StandardAnalyzer(). It is easier and useful.

Yes - while StandardAnalyzer is already used as the default (in 9.0), that is defined in the UI layer. My intention here is that set the default in the model layer; though the difference is not visible in the UI, this is more manageable and test-friendly. 

> I had some other idea: You could also add a line to enter the class name of an Analyzer and add a button "Instantiate class (requires no-arg constructor)".

This is definitely possible, but some work is needed (adding a UI component requires layout rebalancing and proper event handling); can come later.

Here is the default look of the Luke Analysis UI with the patch (no difference from 9.0, in terms of the user interface).
![Screenshot from 2021-11-28 08-32-48](https://user-images.githubusercontent.com/1825333/143723393-cc7ce7f5-92a3-425b-8bcb-ca26e0150fef.png)

I'll push it to the main soon.

2021-11-27 23:51 UTC, mocobeta commented on lucene/luke/src/java/org/apache/lucene/luke/models/analysis/AnalysisImpl.java
> +          .withTokenizer(StandardTokenizerFactory.NAME, params)
> You don't need a map. Customanalyzer takes a Varars of strings. We should use the code in the "official way" (see examples in Javadocs).

I know the builder interface with variable arguments. Ok, I'll keep in mind that.

2021-11-28 12:22 UTC, merged

2021-11-28 12:49 UTC, uschindler commented
Thanks 👍