LUCENE-10234: Change module prefix to org.apache.*
apache/lucene pull request #487
Opened 2021-11-29 18:31 UTC by dweiss

2021-11-29 18:39 UTC, uschindler requested changes

2021-11-29 18:39 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Can we do this like here, based on the Maven group?
https://github.com/apache/lucene/blob/main/gradle/maven/publications-maven.gradle#L59-L60

Of course, we would need to strip the ":lucene" from project path.

2021-11-29 19:27 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
The problem may be in the order of how all these properties are set (and when) - this is the dark pit I wouldn't want to go into... Manifest attributes should be resolved lazily but I've had mixed results with this. I'll see if it works.

2021-11-29 19:54 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Ok, take a look now. Try: gradlew showModuleNames

2021-11-29 19:57 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
There is a functional change piggybacked in the last commit - javadoc and source jars no longer receive automatic module name. I consider it a fix of something that wasn't right (these JARs are not modules).

2021-11-29 20:07 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Will check soon. I am not yet sure about how the local name should look like.

2021-11-29 20:11 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Sure. Let me know (or commit the changes to this PR).

2021-11-29 20:35 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Hi, so it looks like this:

```
> Task :showModuleNames
lucene-benchmark-10.0.0-SNAPSHOT.jar               -> org.apache.lucene.benchmark
lucene-backward-codecs-10.0.0-SNAPSHOT.jar         -> org.apache.lucene.backward_codecs
lucene-classification-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.classification
lucene-codecs-10.0.0-SNAPSHOT.jar                  -> org.apache.lucene.codecs
lucene-core-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.core
lucene-demo-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.demo
lucene-expressions-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.expressions
lucene-facet-10.0.0-SNAPSHOT.jar                   -> org.apache.lucene.facet
lucene-grouping-10.0.0-SNAPSHOT.jar                -> org.apache.lucene.grouping
lucene-highlighter-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.highlighter
lucene-join-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.join
lucene-luke-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.luke
lucene-memory-10.0.0-SNAPSHOT.jar                  -> org.apache.lucene.memory
lucene-misc-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.misc
lucene-monitor-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.monitor
lucene-queries-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.queries
lucene-queryparser-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.queryparser
lucene-replicator-10.0.0-SNAPSHOT.jar              -> org.apache.lucene.replicator
lucene-sandbox-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.sandbox
lucene-spatial-extras-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.spatial_extras
lucene-spatial3d-10.0.0-SNAPSHOT.jar               -> org.apache.lucene.spatial3d
lucene-suggest-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.suggest
lucene-test-framework-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.test_framework
lucene-analysis-common-10.0.0-SNAPSHOT.jar         -> org.apache.lucene.common
lucene-analysis-icu-10.0.0-SNAPSHOT.jar            -> org.apache.lucene.icu
lucene-analysis-kuromoji-10.0.0-SNAPSHOT.jar       -> org.apache.lucene.kuromoji
lucene-analysis-morfologik-10.0.0-SNAPSHOT.jar     -> org.apache.lucene.morfologik
lucene-analysis-nori-10.0.0-SNAPSHOT.jar           -> org.apache.lucene.nori
lucene-analysis-opennlp-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.opennlp
lucene-analysis-phonetic-10.0.0-SNAPSHOT.jar       -> org.apache.lucene.phonetic
lucene-analysis-smartcn-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.smartcn
lucene-analysis-stempel-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.stempel
```

I liked the previous names more, because now "analysis" is missing, @rmuir any suggestion. Maybe we should do something like this:

```
"${-> project.group.toString() + "." + project.path.replaceFirst(":lucene:", "").replace(':', '.').replace("-", "_")}"
```

So maybe ask others on mailing list.

2021-11-29 20:37 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Anyways, thanks for fixing the bug with the wrong manifest on non-library JARs (javadocs).

One thing to keep in mind: When we add module-info.java, we need to remove the attribute, otherwise we have a duplicate.

2021-11-29 20:39 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
With my change it would like this:

```
> Task :showModuleNames
lucene-benchmark-10.0.0-SNAPSHOT.jar               -> org.apache.lucene.benchmark
lucene-backward-codecs-10.0.0-SNAPSHOT.jar         -> org.apache.lucene.backward_codecs
lucene-classification-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.classification
lucene-codecs-10.0.0-SNAPSHOT.jar                  -> org.apache.lucene.codecs
lucene-core-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.core
lucene-demo-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.demo
lucene-expressions-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.expressions
lucene-facet-10.0.0-SNAPSHOT.jar                   -> org.apache.lucene.facet
lucene-grouping-10.0.0-SNAPSHOT.jar                -> org.apache.lucene.grouping
lucene-highlighter-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.highlighter
lucene-join-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.join
lucene-luke-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.luke
lucene-memory-10.0.0-SNAPSHOT.jar                  -> org.apache.lucene.memory
lucene-misc-10.0.0-SNAPSHOT.jar                    -> org.apache.lucene.misc
lucene-monitor-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.monitor
lucene-queries-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.queries
lucene-queryparser-10.0.0-SNAPSHOT.jar             -> org.apache.lucene.queryparser
lucene-replicator-10.0.0-SNAPSHOT.jar              -> org.apache.lucene.replicator
lucene-sandbox-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.sandbox
lucene-spatial-extras-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.spatial_extras
lucene-spatial3d-10.0.0-SNAPSHOT.jar               -> org.apache.lucene.spatial3d
lucene-suggest-10.0.0-SNAPSHOT.jar                 -> org.apache.lucene.suggest
lucene-test-framework-10.0.0-SNAPSHOT.jar          -> org.apache.lucene.test_framework
lucene-analysis-common-10.0.0-SNAPSHOT.jar         -> org.apache.lucene.analysis.common
lucene-analysis-icu-10.0.0-SNAPSHOT.jar            -> org.apache.lucene.analysis.icu
lucene-analysis-kuromoji-10.0.0-SNAPSHOT.jar       -> org.apache.lucene.analysis.kuromoji
lucene-analysis-morfologik-10.0.0-SNAPSHOT.jar     -> org.apache.lucene.analysis.morfologik
lucene-analysis-nori-10.0.0-SNAPSHOT.jar           -> org.apache.lucene.analysis.nori
lucene-analysis-opennlp-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.analysis.opennlp
lucene-analysis-phonetic-10.0.0-SNAPSHOT.jar       -> org.apache.lucene.analysis.phonetic
lucene-analysis-smartcn-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.analysis.smartcn
lucene-analysis-stempel-10.0.0-SNAPSHOT.jar        -> org.apache.lucene.analysis.stempel
```

2021-11-29 20:43 UTC, rmuir commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
hmm, for sure I'm unhappy about the "analysis" missing, because `org.apache.lucene.common` seems pretty ambiguous. But I'd be happy with `org.apache.lucene.analysis_common` which is what I think your suggestion would create?

But +1 to iterate here a little bit more (can we get "analysis" in the name some way or another), and then ping the mailing list with a printout just like what you showed here. If anyone has a strong opinion then they had a chance.

2021-11-29 20:48 UTC, rmuir commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
That's also great to me (in a way, preferred over the underscores for the analysis ones, but I didn't want to suggest special-casing it in the gradle build).

2021-11-29 20:48 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
We might have overlapped: I copypasted my idea. Thanks @dweiss for the printout possibility. This also helps when migrating to module-info.java.

2021-11-29 20:55 UTC, rmuir commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
by the way (sorry its offtopic) i just realized that in 9.0, we changed the maven names of all the analyzers from `lucene-analyzers-xxx` to `lucene-analysis-xxx`. Do we call this out somewhere bigtime / can we add a note here if we dont? I would anticipate lots of questions if anyone upgrades, because they may not expect to have to adjust this in their build. Sorry, just now thought of it, trying to reduce respins :)

2021-11-29 20:57 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Yes it was changed to be conform to the source directry names. The "analyzers" name was wrong.

But I agree, we should add a note to the MIGRATE.md file! Thanks @rmuir !

2021-11-29 21:02 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Artifact rename is mentioned in migration:
```
## Rename of binary artifacts from '**-analyzers-**' to '**-analysis-**' (LUCENE-9562)
```

So... what should I do about module names then?... I'm not sure what the outcome of the discussion is. Perhaps we should do this - tweak the names in a way you like it and commit (or provide a change suggestion)?

2021-11-29 21:02 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
I rewrote it a bit, if nobody objects, I'd replace the line in Dawids code with:

```
manifestAttrs["Automatic-Module-Name"] = "${->  project.path.replaceFirst(/^:lucene/, project.group as String).replace(':', '.').replace('-', '_')}"
```

2021-11-29 21:10 UTC, rmuir commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
> Artifact rename is mentioned in migration:
>
> ## Rename of binary artifacts from '**-analyzers-**' to '**-analysis-**' (LUCENE-9562)

OK I will make a separate PR with my suggestions. Sorry for creating noise on the issue, but Uwe's questions here had me snooping around maven doing inspections, and that's why I noticed it. I'd like to move this up "higher" in the file and just add a simple list of old/new maven coordinates for each affected jar. I think it would be a bit more verbose but useful to almost anyone upgrading the library.

2021-11-29 21:18 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
Sure, please do. It must have been at the top at some point... The structure of this file was never too clear to me - whether it's prioritized or just listed chronologically.

2021-11-29 21:21 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
I committed my change. I will post the output on mailing list to get the others informed.

Nevertheless we should still not make module system public for the 9.0 release, this may lead to too many questions. Once we have real module-info files and tested everything, we can make it public.

By my complaint I just wanted to make sure that at least the module names are according to community standards and suggestions by Oracle. I know, @dweiss does not agree but let's present this to the committers on ML.

2021-11-29 21:23 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +              "Automatic-Module-Name" : "org.apache.${-> project.path.replaceFirst(":", "").replace(':', '.').replace("-", "_")}"
That's fine, Uwe - I'll live with it. As for the module system - I think it can be mentioned that it is preliminary support but at least module names will remain the same. It's better than nothing...

2021-11-29 21:27 UTC, uschindler approved these changes

2021-11-29 21:50 UTC, uschindler commented
I added a change to the CHANGES.txt file to explain that the automatic module names are a preparation for full  module system support. This should be added, because we have not fully tested that everything works well with automatic module names.

Also I added a note that the module names should not be considered "stable". OK?

2021-11-29 23:02 UTC, rmuir approved these changes
looks good to me

2021-11-29 23:43 UTC, mocobeta commented
> Also I added a note that the module names should not be considered "stable". 

For what it's worth, I don't think this notice is needed. I've seen many small/large projects that have changed artifact names for various reasons; users have dealt with it (I don't much care about the artifacts/modules name is stable or not, I just search for the right artifacts I need on the Maven central and it works). While the frequent naming changes would be confusing, do we need to strictly define stable names somewhere in the future...? - It's not an opinion but my feeling.

2021-11-30 03:45 UTC, mocobeta commented
I checked `luke.sh` and `luke.bat` works for me, just in case.
+1.

From my experiences, launch scripts are the ones of the most fragile and often overlooked parts in software projects. I think Windows bundles PowerShell for years which supports shell scripts, could we discard `.cmd` somewhere in the near future releases...

2021-11-30 06:36 UTC, dweiss commented
@mocobeta the powershell scripts have much stricter isolation/ security checks and they would have to be signed. I'm not sure how this works but my experience on github actions infrastructure is that if you start messing with powershell, things stop working.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2

2021-11-30 06:39 UTC, dweiss reviewed
"Pull request authors can't approve their own pull requests". 

...but I do.

2021-11-30 06:39 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +configure(rootProject) {
I'll move this snippet to the dedicated jms section of the build (in the PR that adds full module support). It is useful.

2021-11-30 07:22 UTC, uschindler commented on gradle/java/jar-manifest.gradle
> +configure(rootProject) {
If we have full module support, the automatic module name attribute in manifest won't be there anymore. We may need other code to display this.

2021-11-30 07:26 UTC, mocobeta commented
> the powershell scripts have much stricter isolation/ security checks and they would have to be signed. I'm not sure how this works but my experience on github actions infrastructure is that if you start messing with powershell, things stop working.

ah, okay... anyway thanks for maintaining it correctly.
I don't think we want to repeat the manual tests for the luke start scripts every release or receive bug reports from users right after publishing the artifacts. If we need them for future releases to come, I'd like to seek a way to integrate a sanity check for it into our smoke test or CI.

2021-11-30 07:33 UTC, dweiss commented on gradle/java/jar-manifest.gradle
> +configure(rootProject) {
Yes, I know. It still belongs over there though.

2021-11-30 07:34 UTC, dweiss commented
> I'd like to seek a way to integrate a sanity check for it into our smoke test or CI.

I know how to do it - I am doing it elsewhere. I just need to get to this part. Track that jms pr, please!

2021-11-30 07:35 UTC, dweiss commented
@uschindler Let me know when you think it's ready and I'll merge/ backport.

2021-11-30 07:57 UTC, uschindler commented
> I don't think we want to repeat the manual tests for the luke start scripts every release or receive bug reports from users right after publishing the artifacts. If we need them for future releases to come, I'd like to seek a way to integrate a sanity check for it into our smoke test or CI.

This was also always an issue with Solr, which stopped working on Windows or Linux from time to time. Solr's Smoketester checks this (although not the whitespaces), but Solr does not need a GUI. For Luke it is harder, because we can't easily check a GUI. One idea would be to add some command line parameter to Luke's main class like `--sanity-check`. If you pass this to script it is justpassing to main function which does some tests if all works.

2021-11-30 08:11 UTC, mocobeta commented
> I know how to do it - I am doing it elsewhere. I just need to get to this part. Track that jms pr, please!

> One idea would be to add some command line parameter to Luke's main class like --sanity-check. If you pass this to script it is justpassing to main function which does some tests if all works.

Thanks, I would not like to do further thread hijacking here, but to continue the conversation on another issue or PR.

2021-11-30 08:20 UTC, uschindler commented
> @uschindler Let me know when you think it's ready and I'll merge/ backport.

Let's wait till this evening to get everybody a chance to bring in hisher opinion. Christian Stein from OpenJDK/JUnit/Maven already answered on the issue.

I sent a HEADS UP as suggested by Adrien to the Mailing list yesterday evening.

2021-11-30 12:19 UTC, dweiss commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This in a first step to enable full Java
```suggestion
* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
```

2021-11-30 13:20 UTC, mocobeta commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
I just browsed through the CHANGES and found there is `Build` section in the 9.0 changes.
https://github.com/apache/lucene/blob/749b744c0c2fcc5de709c3b48fa8ef802af010f4/lucene/CHANGES.txt#L473

Does it make sense to move this entry to there, what do you think?
Also, it seems to me LUCENE-9077 should appear at the top of the Build section, and LUCENE-8768 can be there too.

2021-11-30 13:24 UTC, mocobeta commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
If you don't mind, can I edit the CHANGES.txt here ...?

2021-11-30 14:42 UTC, uschindler commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
You can add dawid's github as upstream and checkout his branch, edit it and push.

If you just want to change a bit of text, go into the diff view of the PR, scroll to the file (CHANGES.txt) and press on the three dots top-right and choose "Edit file".

2021-11-30 14:48 UTC, uschindler commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
But to come back to your original question: This is an "improvement" (we have module names now) and not a "build change" (yes it is a build change technically, but it does not improve our build system).

So I would leave it where it is.

2021-11-30 14:59 UTC, mocobeta commented on lucene/CHANGES.txt
> +* LUCENE-10234: Added Automatic-Module-Name to all JARs. This is the first step to enable full Java
Yes, I know I can edit that, I just wanted to ask the author's thoughts.

> So I would leave it where it is.

Ok, thanks.

After writing this suggestion, I noticed re-organizing CHANGES could complicate back-port; it could be better to untouch the file after cutting the release branches (unless it should be really fixed).

2021-11-30 17:55 UTC, uschindler commented
There was positive review, also from Elasticsearch people, on the dev mailing list, so I think we can merge this. Maybe later this evening or tomorrow morning?

So my +1 to merge soon.

2021-11-30 21:03 UTC, merged