LUCENE-10002 Replace simple usages of TotalHitCountCollector with IndexSearcher#count
apache/lucene pull request #612
Opened 2022-01-18 15:38 UTC by javanna

This is one of the many steps required to resolve LUCENE-10002

In case only number of documents are collected, `IndexSearcher#search(Query, Collector)` is commonly used, which does not use the executor that's been eventually set to the searcher. Calling `IndexSearcher#count(Query)` makes the code more concise and is also more correct as it honours the executor that's been set to the searcher instance.

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

2022-01-20 12:49 UTC, jpountz requested changes
I found a couple changes that we probably don't want to do but otherwise it's a nice cleanup!

2022-01-20 12:49 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/search/TotalHitCountCollector.java
> + * Collector)} which will automatically create an instance of this collector internally
I would make this statement stronger since IndexSearcher#count is sometimes going to be faster, e.g. by returning the match count directly from index statistics.

2022-01-20 12:49 UTC, jpountz commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +      searcher.count(new MatchAllDocsQuery());
Hmm these changes look like they could change the behavior since `IndexSearcher#count` might by-pass the query cache entirely when it can get counts from index statistics.

2022-01-20 12:49 UTC, jpountz commented on lucene/core/src/test/org/apache/lucene/search/TestTermQuery.java
> +    assertEquals(1, searcher.count(query));
See the above comment, we want to keep calling the collector here.

2022-01-25 09:28 UTC, javanna commented on lucene/core/src/java/org/apache/lucene/search/TotalHitCountCollector.java
> + * Collector)} which will automatically create an instance of this collector internally
definitely, I had misread the collector used by count, I will clarify.

2022-01-25 09:31 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestTermQuery.java
> +    assertEquals(1, searcher.count(query));
oh boy I did not notice the comment which said exactly that :)

2022-01-25 09:40 UTC, javanna commented
I pushed an update that address your comments @jpountz , thanks for your review!

2022-01-25 09:45 UTC, jpountz requested changes

2022-01-25 09:45 UTC, jpountz commented on lucene/core/src/java/org/apache/lucene/search/TotalHitCountCollector.java
> + * Collector)} as the former is faster whenever the match can be returned directly from the index
Did you mean s/match/count/?

```suggestion
 * Collector)} as the former is faster whenever the count can be returned directly from the index
```

2022-01-25 09:45 UTC, jpountz commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +    searcher.count(query.build());
I think this one should use TotalHitCountCollector too.

2022-01-25 10:14 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +    searcher.count(query.build());
yes, I missed reverting it, thanks!

2022-01-25 10:15 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +    searcher.search(query, new TotalHitCountCollector());
looks like this was already using count, I guess I should revert this bit? I meant to revert the other usage above but I got confused.

2022-01-25 10:15 UTC, javanna commented on lucene/core/src/java/org/apache/lucene/search/TotalHitCountCollector.java
> + * Collector)} as the former is faster whenever the match can be returned directly from the index
I meant match count, but count is fine too.

2022-01-25 10:23 UTC, jpountz commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +    searcher.search(query, new TotalHitCountCollector());
I think it makes the assumption that since BadQuery doesn't implement Weight#count then it will interact with caching. My gut feeling is that it's better to use TotalHitCountCollector which is more explicit.

2022-01-25 10:27 UTC, javanna commented on lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
> +    searcher.search(query, new TotalHitCountCollector());
great then

2022-01-25 10:39 UTC, javanna commented
Thanks @jpountz it should be ready for now, for real this time ;)

2022-01-25 15:11 UTC, jpountz approved these changes

2022-01-25 15:11 UTC, merged