LUCENE-10400: revise to load dictionary resources in kuromoji
apache/lucene pull request #643
Opened 2022-02-03 16:06 UTC by mocobeta

I drafted an idea to revise the dictionary constructors.

Main changes:
1. always use Class.getResourceAsStream() to load class resources. (don't delegate it to the parent class)
2. deprecate the constructors that switch the resource location (classpath/file path). 
    - instead, break it down into two constructors - one for the classpath (non-arg constructor) and another (one-arg constructor) for the file path.
    - the two constructors are exactly the same except for the way to locate the resource, I introduced an internal constructor that takes `Supplier`s that returns InputStream.

2022-02-04 02:59 UTC, mocobeta commented
@uschindler @msokolov 
Would you take a look at the revised constructors' API design when you have some time? If this gains basic consensus, I will add tests for the newly introduced APIs.

2022-02-04 09:52 UTC, uschindler commented
Hi, I am a bit busy, let me check later! Could take over weekend.

2022-02-04 09:54 UTC, uschindler requested changes
Not my full review, just something I already noticed last night:

2022-02-04 09:54 UTC, uschindler commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/ConnectionCosts.java
> +  public ConnectionCosts(String resourceLocation) throws IOException {
This should take `Path`as Parameter, no String. According to Robert, `Paths.get()` should be put on forbidden list, as it makes testing with custom path impls impossible.

2022-02-04 10:21 UTC, uschindler commented
One thing that I wanted to add: We should add @Deprecated(forRemoval=true), this makes builds very noisy if you use the deprecated API. By adding a since="9.1" tag we may also remove it earlier than 10.0.

Of course the deprecated APIs should not merged into "main", but maybe it is easier to keep them in in first commit and rmove in a secondary PR afterwards only in main.

2022-02-04 10:27 UTC, mocobeta commented
> One thing that I wanted to add: We should add @deprecated(forRemoval=true), this makes builds very noisy if you use the deprecated API. By adding a since="9.1" tag we may also remove it earlier than 10.0.

> Of course the deprecated APIs should not merged into "main", but maybe it is easier to keep them in in first commit and rmove in a secondary PR afterwards only in main.

Thanks, I was thinking the same thing. Deprecates the two-args constructors for removal on branch_9x, and removes them on main.

2022-02-04 15:34 UTC, msokolov commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      throws RuntimeException {
Let's use `IOExceptionUnchecked`

2022-02-04 15:34 UTC, msokolov commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      targetMap = new int[in.readVInt()];
can we read the targetMap in a separate function for better readability/modularity?

2022-02-04 15:34 UTC, msokolov commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +    int[] targetMapOffsets = null, targetMap = null;
is it necessary to assign nulls to these? Could we assign directly to members below?

2022-02-04 15:34 UTC, msokolov commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      in = new InputStreamDataInput(posIS);
same here - can we split out into a separate function? I guess Java's handling of final makes it annoying to assign to these members in a function called from the constructor. Perhaps we can return a String[][] ?

2022-02-04 15:34 UTC, msokolov commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +    int[] targetMapOffsets = null, targetMap = null;
Hmm now I see we basically just copy-paste the big ugly method that was here before. I wonder if it's possible to share the same implementation -- in other words can we make the old constructor call this one?

2022-02-04 16:02 UTC, uschindler commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      throws RuntimeException {
`UncheckedIOException` :-)

2022-02-05 04:02 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      throws RuntimeException {
Changed to throw UncheckedException. Also, I added a utility interface to wrap the try-catch clauses here and there.
https://github.com/apache/lucene/pull/643/commits/cb1c5498f7563883d0b619137a36b56f01f491b0

2022-02-05 04:05 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/ConnectionCosts.java
> +  public ConnectionCosts(String resourceLocation) throws IOException {
I changed the interfaces to take the valid Path objects.
https://github.com/apache/lucene/pull/643/commits/78418176c39f03cbc04402822da2875f1dd0661e

2022-02-05 04:23 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +    int[] targetMapOffsets = null, targetMap = null;
Unfortunately, we can't call/delegate to other `this()` from the old constructor. A kind of chicken-egg problem is there -  `getClass()` in it -  this is needed to delegate to the newly added constructor that takes input streams, but it's a constructor so `getClass()` can't be invoked before `this()`.

Instead, we can retire the old constructor and call `this()` instead of `super()` in the implementation classes. Anyway, it's not great to have the if-else for resource switching; I think it is okay to remove the old constructor in the abstract `BinaryDictionary` right now?
https://github.com/apache/lucene/pull/643/commits/9c2c971fae0cba6762fbbb0a7c62d1115e50b33d

2022-02-05 08:38 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      in = new InputStreamDataInput(posIS);
I'd do this.
https://github.com/apache/lucene/pull/643/commits/8bfc984390666dc4e044beec206aee1f85fb6d9a

2022-02-05 10:08 UTC, uschindler commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      in = new InputStreamDataInput(posIS);
The synchronized is not needed if the method is private and *only* called from ctor.

Problematic are methods tha are public or public to subclasses or those which have sideeffects.

2022-02-05 10:11 UTC, mocobeta commented
Encountered an issue with `@Deprecated(forRemoval = true)`. We can't call them even from test cases since `@SuppressWarnings("deprecation")` doesn't work when it is marked as "for removal", and then test compilation fails with warnings.

```
> Task :lucene:analysis:kuromoji:compileTestJava FAILED
/mnt/hdd/repo/lucene/lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/dict/TestTokenInfoDictionary.java:81: warning: [removal] TokenInfoDictionary(ResourceScheme,String) in TokenInfoDictionary has been deprecated and marked for removal
    return new TokenInfoDictionary(ResourceScheme.FILE, dir.resolve(dictionaryPath).toString());
```
Do we have to change tests to get rid of the deprecated method calls?

2022-02-05 10:23 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/BinaryDictionary.java
> +      in = new InputStreamDataInput(posIS);
> The synchronized is not needed if the method is private and only called from ctor.

I will remove "synchronized" here again.

2022-02-05 10:54 UTC, uschindler commented
> Encountered an issue with `@Deprecated(forRemoval = true)`. We can't call them even from test cases since `@SuppressWarnings("deprecation")` doesn't work when it is marked as "for removal", and then test compilation fails with warnings.
> 
> ```
> > Task :lucene:analysis:kuromoji:compileTestJava FAILED
> /mnt/hdd/repo/lucene/lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/dict/TestTokenInfoDictionary.java:81: warning: [removal] TokenInfoDictionary(ResourceScheme,String) in TokenInfoDictionary has been deprecated and marked for removal
>     return new TokenInfoDictionary(ResourceScheme.FILE, dir.resolve(dictionaryPath).toString());
> ```
> 
> Do we have to change tests to get rid of the deprecated method calls?

Hi,

as we want to remove the methods anyway (at least in master), fixing the tests would be a good idea. If we need to maintain test in 9.x testing the old methods, a `@SuppressWarnings("removal")` would be applicable.

2022-02-05 11:02 UTC, uschindler commented
In general  I like the idea here, but I would do one change: You already defined a new functional interface, but the public methods taking Supplyier. I am against uselessly wrapping exceptions just because the stupid old Java concept of "checked" exceptions.

My proposal would be:
- Define a `@FunctionalInterface public interface ResourceSupplier<T> { T get() throws IOException; }` in Lucene's core module next to IOUtils (or maybe inside IOUtils). I say this, because we may use the supplier pattern now more often and when Nori is also changed, we would need the interface again.
- The constructors take `ResourceSupplier<InputStream>`

If you still want to go the wrapping, you may also have a look at https://twitter.com/thetaph1/status/1487397163718135812
This shows that you can trick out Java compiler and convert functional interfaces (by casting them using generics) to allow them to throw checked exceptions. I had a similar problem like this in some large codebase using `SQLException` and many `Function`, `Supplier`, `Consumer`. The trick was to just make the exceptions invisible to the stupid javac compiler :-) - it is perfectly legal code and won't break as it follows the laguage spec. It is just casting Exceptions away.

2022-02-05 12:24 UTC, mocobeta commented
I added `@SuppressWarnings("removal")` to tests that invoke deprecated methods for now - to keep the tests as-is on branch_9x. I will remove the obsolete methods and change tests in a separate patch (after backporting this).

Also, the suggested `ResourceSupplier<T>` interface works very well, thanks. 
As for the wrapping checked exception trick (type erasure plays the main role there, maybe?), it's cool but seems too much for me.

2022-02-05 12:44 UTC, uschindler requested changes

2022-02-05 12:44 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  public interface ResourceSupplier<T> {
Maybe rename this to `IOSupplier<T>` to be inline with the other interfaces before. I wasn't aware that there were already interfaces like this.

2022-02-05 12:48 UTC, uschindler commented
> I added `@SuppressWarnings("removal")` to tests that invoke deprecated methods for now - to keep the tests as-is on branch_9x. I will remove the obsolete methods and change tests in a separate patch (after backporting this).

OK.

> Also, the suggested `ResourceSupplier<T>` interface works very well, thanks.

Let's rename it. I wasn't aware that we have Function and Consumer already in IOUtils. With the correct name its a great addition!

> As for the wrapping checked exception trick (type erasure plays the main role there, maybe?), it's cool but seems too much for me.

Haha, IOSupplier is much better. The wrappers is mostly a cool trick, but should be used sparingly (when you want to use APIs like Java's stream API, that allows no checked Exceptions. The downside is also that you remove the checked exception and you can't catch it anymore.

It was just funny that you stumbled on the same stuff like I did. BTW: It is once per year when I invent a new Sneaky implementation. That's the third one, this time for functional interfaces. I have to hold my nickname "Generics Policeman"!

2022-02-05 12:50 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +   * A resource supplier function that may throw an IOException
I think we should add a note that the consumer has to close the resource (eg., use try-with-resources) and the supplier can count on this.

2022-02-05 13:16 UTC, mocobeta commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +   * A resource supplier function that may throw an IOException
I added a note here. https://github.com/apache/lucene/pull/643/commits/4e96ed49f5b107fcb9fe5862496e8a630e734206

2022-02-05 16:49 UTC, dweiss commented
> The trick was to just make the exceptions invisible to the stupid javac compiler :-) - it is perfectly legal code and won't break as it follows the laguage spec. It is just casting Exceptions away.

This isn't exactly right - it is legal bytecode but it isn't exactly playing well with the language. The calling code may expect your interface to never throw a checked exception and thus only catch a selected subset of unchecked ones - a checked rethrown exception violates this semantics. To be a bit more concrete, imagine if the library code had this:

```
void foo(Supplier<T> t) {
  try {
    doSomething(t.get());
    processed = true;
  } catch (RuntimeException | Error e) {
    exceptionHappened = true;
  }
}
```

From the Java language point of view this either returns normally or sets the exception flag - it is not possible to write Java code that bypasses both processed and exceptionHappened. But the sneaky-rethrows hack does allow the supplier to go directly up the stack, up until an exception handler for a checked exception is found. This is where the problem is - it may leave the library code in inconsistent state.

I agree the lack of any exception signature on streams is terrible but I prefer to have wrappers that rethrow an unchecked exception, with the original one as the cause - this is legal and leaves no space for surprises like the one above.

2022-02-06 10:54 UTC, mocobeta commented
Assuming this is close to being ready for merge, I'm going to prepare a changes entry for 9.1 (for deprecated APIs with removal.) Once this is backported I will open another pull request for main to remove the obsolete APIs with another changes entry (for removed APIs.) Then will need to repeat the same for Nori.
I will keep this open for one or two days for further review.

2022-02-06 10:54 UTC, uschindler commented
> This isn't exactly right - it is legal bytecode but it isn't exactly playing well with the language. 

Hi @dweiss: Let's not discuss this here, the whole thing does not apply to this PR. My recommendation was to add another functional interface to IOUtils (we already created them there).

I would never design my APIs in a way like Java streams API was done, so having a separate functional interface for IO actions is a good idea. The above tweet is more about working around problems with Java Streams API. We know for sure that Java Streams API internally handles exception in a correct way (using finally blocks), so the code example you posted does not apply there. To me, checked exceptions are a misconception of Java, but you can start flamewars about that. Another misconception was to let MethodHandles.invoke throw Throwable. Thats another case where sneaky rethoring must be done to have nice behaviour. But there it is no problem because you left Java Type System already. So inside methods that call MethodHandles it is recommended and perfectly fine to use rethrow, as long as you make sure the caller form public API gets correct exceptions (means you sneaky rethrow all excepions, but you declare the method to have the checked exceptions you know of). BTW, Java internally also rethrows like this in the lamda bootstraps (I rewrote it for Elasticsearch Painless language).

In general: Every cast is a misuse of the Java language, and so is this one.  What we do here is just casting the exception type. So it is a misuse of type system (like every cast is), but it is not a misuse of the language. Its perfectly legal to do it. If you try out my above Sneaky class and look (with eclipse) at the types introduced for the generics type arguments, it is funny how intelligent the Java compiler is: If you have a functional interface throwing `E extends Exception` and the code does not throw any checked exception, Javac inserts `RuntimeException` into the type argument.

I already talked too much, my problem with Sneaky is that if you use such type casting, the Java Compiler won't allow you to catch checked Exceptions anymore, that's the worst thing that happens - but Sneaky works grell if you make sure that the method itsself calling your erased Java streams is redeclaring `throws IOException`. The try...catch posted above is.... bad code anyways. Better use finally blocks to ensure something is executed for sure.

2022-02-06 11:19 UTC, uschindler approved these changes
Looks fine now. I am glad that the horrible API is going away.

2022-02-06 11:19 UTC, uschindler commented on lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/TestJapaneseTokenizer.java
> +  @SuppressWarnings("removal")
This test will be obsolete in main, so we can remove it completely. It does not test anything useful. We may need to adda test that really loads a resource from a file.

2022-02-06 11:35 UTC, mocobeta commented on lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/TestJapaneseTokenizer.java
> +  @SuppressWarnings("removal")
Yes, I am going to handle this in the following PR.

2022-02-06 12:53 UTC, dweiss commented
> The try...catch posted above is.... bad code anyways. Better use finally blocks to ensure something is executed for sure.

I know it can be written differently, but that's not the point, Uwe - I just showed an example of what can be lurking in the code you can't/ don't control (including the streams implementation). Like I said, I got burnt on this once and I tried not to abuse the type system's loopholes ever since.

2022-02-06 13:48 UTC, uschindler commented
> > The try...catch posted above is.... bad code anyways. Better use finally blocks to ensure something is executed for sure.
> 
> I know it can be written differently, but that's not the point, Uwe - I just showed an example of what can be lurking in the code you can't/ don't control (including the streams implementation). Like I said, I got burnt on this once and I tried not to abuse the type system's loopholes ever since.

That's OK. I just wanted to say: When working with MethopdHandles the general rule, also internally followed by the JDK code is to rethrow the original exception. If you have a methodHandle you know from the content which Exceptions it really throws.

If you would me to enforce not use rethrow or type casting here, I'd like you to open many bug reports in Elasticsearch Painless and the JDK source code's implementations of StringConcatFactory and LambdaMetaFactory. Both of those just rethrow exceptions everywhere. When working with MethodHandles you have to accept that you have left the type system -- sorry.

2022-02-06 15:48 UTC, mocobeta commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/TokenInfoDictionary.java
> +    final String resourcePath = TokenInfoDictionary.class.getSimpleName() + suffix;
This "simple name + suffix" naming convention is ubiquitous in kuromoji (and nori). I am wondering if this is an appropriate method to locate resources. I think this question could pop up again when we closely look at BinaryDictionaryWriter#write().

2022-02-06 16:11 UTC, uschindler commented on lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/TokenInfoDictionary.java
> +    final String resourcePath = TokenInfoDictionary.class.getSimpleName() + suffix;
I think this is at least fine for the "default loading" for our own resources. It should not be used for public resources (there we now only have constructors taking file streams, as it makes no sense for external files).

2022-02-07 10:30 UTC, mocobeta commented
Thanks for reviewing, I'm going to merge this. I will open another pull request to remove the obsolete methods on main.

2022-02-07 10:31 UTC, merged

2022-02-09 05:43 UTC, dsmiley commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
What about`org.apache.lucene.util.IOSupplier` that already exists?

2022-02-09 12:21 UTC, mocobeta commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
I didn't notice there is `o.a.l.util.IOSupplier`. It's confusing to have two interfaces with the same signature.

Also, there are other functional interfaces in `o.a.l.util.IOUtils` corresponding to Java stdlib's Consumer and Function.
I think it might be better to move all functional interfaces in `o.a.l.util.IOUtils` to top-level interfaces? @uschindler

2022-02-09 12:41 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
I was also not aware that this interface already existed. Because all others were in IOUtils, so this was inconsistent before.

IMHO, I agree with @mocobeta - Move all of them to IOUtils. Separate classes bloat the Javadocs.

2022-02-09 12:42 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
Let's open a separate issue and remove the top-level one.

2022-02-09 13:27 UTC, mocobeta commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
I slightly prefer to have top-level functional interfaces `o.a.l.util.[IOSupplier|IOConsumer|IOFunction]` for visibility since we will use them more frequently in the future. And there are only two such existing functional interfaces in `IOUtils`, so moving them to top-level would not be difficult -  what do you think about it? 
But I'm not so familiar with the convention in there, and am fine with having all of them under `o.a.l.util.IOUtils`.

2022-02-09 13:28 UTC, dweiss commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
I'm leaning towards class-per-file convention as well. Too many nested (public) classes makes my head spin.

2022-02-09 15:35 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
Yes, both is fine. Actually the nested ones have a naming problem: "IOUtils.IOSupplier" has two times IO, so either "IOSupplier" or "IOUtils.Supplier".

> so moving them to top-level would not be difficult - what do you think about it?

In most cases you don't even need to change the import statements, because there are none (at least for consumers of APIs implementing the functional interfaces with lambdas or method references). You only need to change import statements in API definitions, but for consumers it is still "source code" compatible (but not "binary/class file" compatible).

2022-02-09 15:51 UTC, mocobeta commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
It seems there is a bit of disagreement in the API design. I think we'd need to solve this inconsistency in the core util's API to proceed with LUCENE-10400, I will open an issue.

2022-02-09 15:59 UTC, mocobeta commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
> Yes, both is fine. Actually the nested ones have a naming problem: "IOUtils.IOSupplier" has two times IO, so either "IOSupplier" or "IOUtils.Supplier".

Excuse me, I wrote the previous comment before seeing your comment.

2022-02-09 16:41 UTC, uschindler commented on lucene/core/src/java/org/apache/lucene/util/IOUtils.java
> +  @FunctionalInterface
> I'm leaning towards class-per-file convention as well. Too many nested (public) classes makes my head spin.

I think this depends on the use case. If the functional interface should be used by many classes throughout Lucene's API, I agree with that.

The ones in IOUtils were originally only meant to be part of method signatures inside IOUtils. In this case, it is better to hide them inside the IOUtils class, because nobody would refer to them in import statements! You call a method in IOUtils and use the functional interface implicitely, the name does not matter as you never import or use the interface name directly). But as soon as many APIs like kuromoji use the functional interface, then it is better to place them as top-level classes. Full agreement.

I think that happened with IOUtils: At beginning the interfaces were meant as method parameters to some methods only, but now they graduated to top-level citicens.