support binary search in PointValues
apache/lucene pull request #687
Opened 2022-02-17 12:37 UTC by wjp719

add common function for caller to binary search in bkdPointTree.

One possible use case is:  for log data, when indexd sort in ascend order by @timestamp field, when we want to run count aggregation query to find the count of document in many time interval, we can use the binary search to find out the min/max docId in on  time interval, and the doc count=max docId- min docId +1

2022-02-23 13:38 UTC, jpountz commented
This looks very similar to the implementation of `Weight#count` on `PointRangeQuery` and should only perform marginally faster?
It's uncreal to me whether this PR buys us much.

2022-02-27 05:52 UTC, wjp719 commented
> This looks very similar to the implementation of `Weight#count` on `PointRangeQuery` and should only perform marginally faster? It's uncreal to me whether this PR buys us much.

Hi, @jpountz, I refactor the code, now if conditions meet, I use the bkd binary search to find out the min/max docId, to create the **IndexSortSortedNumericDocValuesRangeQuery.BoundedDocSetIdIterator** when create **Scorer** instead of using docvalue to binary search to find out min/max docId. 

As we known, docvalue can only advance forward, but binary search may need to walk back to get the docValue of the middle doc, so every search operation in binary search using docvalue, it needs to create a new **SortedNumericDocValues** instance and advance from the first doc, so it will be more cpu and IO consuming.

### benchmark result
I also test this pr performance with main branch: 
#### dataset
I use two dataset, the small dataset is the [httpLog](https://github.com/elastic/rally-tracks/tree/master/http_logs) with about 200million doc
the big one is our application log with 1.4billion doc
#### query
query is a boolean query with a range query clause and a term query clause, for the small dataset, the query is
```
"query": {
    "bool": {
      "must": [
        {
          "range": {
            "@timestamp": {
             "gte": "1998-06-08T05:00:01Z",
              "lt": "1998-06-15T00:00:00Z"
            }
          }
        },
        {
          "match": {
            "status": "200"
          }
        }
      ]
    }
  }
```
#### result
1. with es rally tool. (it run many times, so the disk data is cached)
```
|                                                        Metric |          Task |    Baseline |   Contender |     Diff |   Unit |
|                                                Min Throughput | 200s-in-range |     9.92683 |     10.0551 |  0.12825 |  ops/s |
|                                               Mean Throughput | 200s-in-range |     9.94556 |     10.0642 |  0.11868 |  ops/s |
|                                             Median Throughput | 200s-in-range |     9.94556 |     10.0633 |   0.1177 |  ops/s |
|                                                Max Throughput | 200s-in-range |     9.96398 |     10.0737 |  0.10974 |  ops/s |
|                                       50th percentile latency | 200s-in-range |     38664.7 |     38022.7 | -641.967 |     ms |
|                                       90th percentile latency | 200s-in-range |     41349.8 |       40704 | -645.858 |     ms |
|                                       99th percentile latency | 200s-in-range |     41954.2 |     41308.7 | -645.491 |     ms |
|                                      100th percentile latency | 200s-in-range |     42021.6 |     41377.6 | -643.989 |     ms |
```
2. manually run one time（clear all  cache） 
```
|            dataSet|main branch latency|this pr latency|latency improvement|
|            httpLog|              267ms|          167ms|               -38%|
|our application log|             2829ms|         1093ms|               -62%|
```

2022-02-28 07:53 UTC, iverase commented
I like this idea but I agree with Adrien that the API change does not look right. More over, I don't think we need to add it to PointValues as this is something specific for Index sorting and it won't apply in all situation. I think it makes little sense when we use the kd-tree as an effective r-tree like in range fields.

I think it is possible to add a specific implementation on `IndexSortSortedNumericDocValuesRangeQuery` that does not require on an API change. I came up with this implementation, something closer to that should work?

```
  /**
   * Returns the first document whose packed value is greater than or equal to the provided packed value
   * or -1 if all packed values are smaller than the provided one,
   */
  public final int nextDoc(PointValues values, byte[] packedValue) throws IOException {
      final int numIndexDimensions = values.getNumIndexDimensions();
      final int bytesPerDim = values.getBytesPerDimension();
      final ByteArrayComparator comparator = ArrayUtil.getUnsignedComparator(bytesPerDim);
      final Predicate<byte[]> biggerThan = testPackedValue -> {
          for (int dim = 0; dim < numIndexDimensions; dim++) {
              final int offset = dim * bytesPerDim;
              if (comparator.compare(packedValue, offset, testPackedValue, offset) <= 0) {
                  return false;
              }
          }
          return true;
      };
      return nextDoc(values.getPointTree(), biggerThan);
  }
    
  private int nextDoc(PointValues.PointTree pointTree, Predicate<byte[]> biggerThan) throws IOException {
      if (biggerThan.test(pointTree.getMaxPackedValue())) {
          // doc is before us
          return -1;
      } else if (pointTree.moveToChild()) {
          // navigate down
          do {
              final int doc = nextDoc(pointTree, biggerThan);
              if (doc != -1) {
                  return doc;
              }
          } while (pointTree.moveToSibling());
          pointTree.moveToParent();
          return -1;
      } else {
          // doc is in this leaf
          final int[] doc = {-1};
          pointTree.visitDocValues(new IntersectVisitor() {
              @Override
              public void visit(int docID) {
                  throw new AssertionError("Invalid call to visit(docID)");
              }

              @Override
              public void visit(int docID, byte[] packedValue) {
                  if (doc[0] == -1 && biggerThan.test(packedValue) == false) {
                      doc[0] = docID;
                  }
              }

              @Override
              public Relation compare(byte[] minPackedValue, byte[] maxPackedValue) {
                  return Relation.CELL_CROSSES_QUERY;
              }
          });
          assert doc[0] != -1;
          return doc[0];
      }
  }
```

2022-02-28 13:14 UTC, wjp719 commented
@iverase , Hi I move the bkd binary to the IndexSortSortedNumericDocValuesRangeQuery as you suggested, please help to review it, thanks.

2022-02-28 14:15 UTC, iverase requested changes
this looks less invasive and efficient. What do you think @jpountz?

2022-02-28 14:15 UTC, iverase commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +      if(!allDocExist) {
We prefer to explicitly equal to false than to use the `!` operator for readability.

2022-02-28 14:15 UTC, iverase commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +          && !indexSort.getSort()[0].getReverse()) {
We prefer to explicitly equal to false than to use the `!` operator for readability.

2022-02-28 14:15 UTC, iverase commented on lucene/sandbox/src/test/org/apache/lucene/sandbox/search/TestIndexSortSortedNumericDocValuesRangeQuery.java
> +  public void testCountWithBkd() throws IOException {
I think we should add a stronger random test case to cover as many cases as possible?

2022-03-01 02:37 UTC, wjp719 commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +      if(!allDocExist) {
done

2022-03-01 02:37 UTC, wjp719 commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +          && !indexSort.getSort()[0].getReverse()) {
done

2022-03-01 02:38 UTC, wjp719 commented
@iverase I add a random test, please review it again

2022-03-01 08:13 UTC, iverase commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +              final int offset = dim * bytesPerDim;
Test seems to be always with one dimension and I think this query can only be used in the 1D case. Can we simplify here and everywhere where we loop through dimensions?

2022-03-01 09:12 UTC, wjp719 commented
@iverase I have simplify dimensions to 1, please review again

2022-03-01 13:48 UTC, jpountz commented
One thing I'm not totally happy with is that the change assumes that the field is either not indexed or indexed with `LongPoint` while this query would previousy also work with `IntPoint`. Things like this would be easier to do once we know more about both how the field is indexed and how doc values have been created, e.g. via [LUCENE-10162](https://issues.apache.org/jira/browse/LUCENE-10162).

2022-03-03 02:47 UTC, wjp719 commented
> One thing I'm not totally happy with is that the change assumes that the field is either not indexed or indexed with `LongPoint` while this query would previousy also work with `IntPoint`. Things like this would be easier to do once we know more about both how the field is indexed and how doc values have been created, e.g. via [LUCENE-10162](https://issues.apache.org/jira/browse/LUCENE-10162).

@jpountz Hi, what else should I do for this pr?

2022-03-15 15:19 UTC, wjp719 commented
@jpountz Hi, please help to  take some time to review this pr again, thanks

2022-03-29 02:42 UTC, wjp719 commented
@jpountz  @iverase Hi, is this pr ok now?

2022-09-20 13:57 UTC, jpountz reviewed
Very (very very) sorry for the long delay, I left some minor comments, IMO we should get this in.

2022-09-20 13:57 UTC, jpountz commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +        byte[] queryLowerPoint = LongPoint.pack(lowerValue).bytes;
Maybe disable this optimization if the number of bytes per dimensions is not 8, so that it doesn't fail on integer fields?

2022-09-20 13:57 UTC, jpountz commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +          return new BoundedDocIdSetIterator(-1, -1, delegate);
Nit: I would prefer passing 0 and 0 rather than -1 and -1 since -1 is not a valid doc ID.

2022-09-20 13:57 UTC, jpountz commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +          return new BoundedDocIdSetIterator(0, points.getDocCount(), delegate);
This doesn't look correct for me on sparse fields, where there might be matching doc IDs between `points.getDocCount()` and `reader.maxDoc()`?

2022-09-20 13:57 UTC, jpountz commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +        return new BoundedDocIdSetIterator(minDocId, maxDocId + 1, delegate);
could we remove the `+ 1` here as well as the two `- 1` in the above `if/else` blocks?

2022-09-21 08:02 UTC, wjp719 commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +        byte[] queryLowerPoint = LongPoint.pack(lowerValue).bytes;
I check bytes per dimensions 8 or 4, and pack to bytes from long or integer

2022-09-21 15:55 UTC, jpountz approved these changes
Thanks, this looks good to me! Can you add a CHANGES entry with your name under 9.5?

2022-09-22 01:59 UTC, wjp719 commented
> Thanks, this looks good to me! Can you add a CHANGES entry with your name under 9.5?

Thanks a lot, I have added the Change entry.

And This PR has a limitation that only index sorting by ascend order can use bkd binary search to get min/max docId. The main reason is that bkd now sorts point  by two dimension (point value, docId) both in ascend order. If doc is index-sorted by ascend order, then all the docId of all leaf point will be monotone increasing, so we can use bkd binay search.

In our local work, if doc is index-sorted by descend order, we modify the bkd sorting logic by (point value in ascend order , docId in descend order), so that all the docId of all leaf point will be monotone decreasing, then we can use bkd binay search again. 

So May I open another PR to add an option that BKD can sort by (point value in ascend order , docId in descend order)? then the bkd binary search can work in both ascend/descend index sorting

2022-09-22 06:47 UTC, jpountz commented
I was wondering about descending sorts too! Do we actually need to make this configurable on BKD trees, I would rather not add this option and make the binary search logic a bit more complex/inefficient.

2022-09-22 06:51 UTC, merged

2022-09-22 07:16 UTC, wjp719 commented
> I would rather not add this option and make the binary search logic a bit more complex/inefficient.

OK thanks, when index sorts on descending order,  I have tried bkd binary search  when with origin bkd, but when the count of same point value is up to  100 thousand, the bkd binary search time is equal to docvalue binary search. In my trial, I need to load all same maximum point value to get the min/max docId, maybe there are other opimizations.

2022-09-22 09:39 UTC, wjp719 commented
> I'm (maybe naively) assuming that we could work around this case at the inner node level by skipping inner nodes whose max value is equal to the min value if we have already seen this value before?

sure, the inner node can be skipped , but for the boundary value, such as the range is from 1663837201000 to 1663839001000. we need to load all leaf block that with point value is 1663839001000 or 1663837201000. if there are 100 thousand doc with point value is 1663839001000 or 1663837201000, we need to load many leaf block to get the min/max docId. these block maybe cannot be skipped?

this case is the real data that there are  60 billion doc per day, and the timestamp is second precision, the average doc per second is 100 thousand.

2022-09-23 06:53 UTC, LuXugang commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +  }
Sorry for later jump in, does `matchAll` could be simplified as ?

```java
for (int dim = 0; dim < points.getNumDimensions(); dim++) {
      int offset = dim * points.getBytesPerDimension();
      if(comparator.compare(points.getMinPackedValue(), offset, queryLowerPoint, offset) >= 0
          &&  comparator.compare(points.getMaxPackedValue(), offset, queryUpperPoint, offset) <= 0) {
        return true;
      }
 }
return false;
```

2022-09-23 07:20 UTC, LuXugang commented on lucene/sandbox/src/java/org/apache/lucene/sandbox/search/IndexSortSortedNumericDocValuesRangeQuery.java
> +          return new BoundedDocIdSetIterator(minDocId, maxDocId, delegate);
I saw Test did not cover this branch, maybe `(points.getDocCount() == context.reader().maxDoc())` is always true, we do not need this branch?